// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ConcernUsage")]
public partial class ConcernUsage : RequirementUsage
{
    private ReferenceTarget? _concernDefinition = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ConcernUsage-concernDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public ConcernDefinition? ConcernDefinition { get => ReferenceTargetNonNullTarget<ConcernDefinition>(_concernDefinition, SysmlLanguage.Instance.ConcernUsage_concernDefinition); set => SetConcernDefinition(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetConcernDefinition([NotNullWhenAttribute(true)] out ConcernDefinition? concernDefinition)
    {
        concernDefinition = ReferenceTargetNullableTarget<ConcernDefinition>(_concernDefinition, SysmlLanguage.Instance.ConcernUsage_concernDefinition);
        return concernDefinition != null;
    }

    private ConcernUsage SetConcernDefinition(ReferenceTarget? value)
    {
        SetOptionalSingleReference<ConcernDefinition>(value, SysmlLanguage.Instance.ConcernUsage_concernDefinition, _concernDefinition, SetConcernDefinitionRaw);
        return this;
    }

    private bool SetConcernDefinitionRaw(ReferenceTarget? value)
    {
        if (value == _concernDefinition)
            return false;
        _concernDefinition = value;
        return true;
    }

    /// <remarks>Optional Single Reference</remarks>
    public ConcernUsage SetConcernDefinition(ConcernDefinition? value)
    {
        return SetConcernDefinition(ReferenceTarget.FromNodeOptional(value));
    }

    public ConcernUsage(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ConcernUsage;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ConcernUsage_concernDefinition.EqualsIdentity(feature))
        {
            result = ConcernDefinition;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ConcernUsage_concernDefinition.EqualsIdentity(feature))
        {
            result = _concernDefinition;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ConcernUsage_concernDefinition.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.ConcernDefinition)
            {
                SetConcernDefinition((LionWeb.Demo.SysMl2.Languages.SysMl2.ConcernDefinition? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetConcernDefinition(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ConcernUsage_concernDefinition.EqualsIdentity(feature))
            return SetConcernDefinitionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetConcernDefinition(out _))
            result.Add(SysmlLanguage.Instance.ConcernUsage_concernDefinition);
        return result;
    }
}

