// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ConjugatedPortTyping")]
public partial class ConjugatedPortTyping : FeatureTyping
{
    private ReferenceTarget? _conjugatedPortDefinition = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If ConjugatedPortDefinition has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ConjugatedPortTyping-conjugatedPortDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public ConjugatedPortDefinition ConjugatedPortDefinition { get => ReferenceTargetNonNullTarget<ConjugatedPortDefinition>(_conjugatedPortDefinition, SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition); set => SetConjugatedPortDefinition(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetConjugatedPortDefinition([NotNullWhenAttribute(true)] out ConjugatedPortDefinition? conjugatedPortDefinition)
    {
        conjugatedPortDefinition = ReferenceTargetNullableTarget<ConjugatedPortDefinition>(_conjugatedPortDefinition, SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition);
        return conjugatedPortDefinition != null;
    }

    private ConjugatedPortTyping SetConjugatedPortDefinition(ReferenceTarget? value)
    {
        SetRequiredSingleReference<ConjugatedPortDefinition>(value, SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition, _conjugatedPortDefinition, SetConjugatedPortDefinitionRaw);
        return this;
    }

    private bool SetConjugatedPortDefinitionRaw(ReferenceTarget? value)
    {
        if (value == _conjugatedPortDefinition)
            return false;
        _conjugatedPortDefinition = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ConjugatedPortTyping SetConjugatedPortDefinition(ConjugatedPortDefinition value)
    {
        return SetConjugatedPortDefinition(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _portDefinition = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If PortDefinition has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ConjugatedPortTyping-portDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public PortDefinition PortDefinition { get => ReferenceTargetNonNullTarget<PortDefinition>(_portDefinition, SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition); set => SetPortDefinition(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetPortDefinition([NotNullWhenAttribute(true)] out PortDefinition? portDefinition)
    {
        portDefinition = ReferenceTargetNullableTarget<PortDefinition>(_portDefinition, SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition);
        return portDefinition != null;
    }

    private ConjugatedPortTyping SetPortDefinition(ReferenceTarget? value)
    {
        SetRequiredSingleReference<PortDefinition>(value, SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition, _portDefinition, SetPortDefinitionRaw);
        return this;
    }

    private bool SetPortDefinitionRaw(ReferenceTarget? value)
    {
        if (value == _portDefinition)
            return false;
        _portDefinition = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ConjugatedPortTyping SetPortDefinition(PortDefinition value)
    {
        return SetPortDefinition(ReferenceTarget.FromNodeOptional(value));
    }

    public ConjugatedPortTyping(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ConjugatedPortTyping;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition.EqualsIdentity(feature))
        {
            result = ConjugatedPortDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition.EqualsIdentity(feature))
        {
            result = PortDefinition;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition.EqualsIdentity(feature))
        {
            result = _conjugatedPortDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition.EqualsIdentity(feature))
        {
            result = _portDefinition;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.ConjugatedPortDefinition v)
            {
                SetConjugatedPortDefinition(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetConjugatedPortDefinition(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.PortDefinition v)
            {
                SetPortDefinition(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetPortDefinition(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition.EqualsIdentity(feature))
            return SetConjugatedPortDefinitionRaw(value);
        if (SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition.EqualsIdentity(feature))
            return SetPortDefinitionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetConjugatedPortDefinition(out _))
            result.Add(SysmlLanguage.Instance.ConjugatedPortTyping_conjugatedPortDefinition);
        if (TryGetPortDefinition(out _))
            result.Add(SysmlLanguage.Instance.ConjugatedPortTyping_portDefinition);
        return result;
    }
}

