// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-FlowConnectionUsage")]
public partial class FlowConnectionUsage : ConnectorAsUsage, IActionUsage, IItemFlow
{
    private readonly List<ReferenceTarget> _flowConnectionDefinition = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-FlowConnectionUsage-flowConnectionDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IInteraction> FlowConnectionDefinition { get => ReferenceTargetNonNullTargets<IInteraction>(_flowConnectionDefinition, SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition); init => AddFlowConnectionDefinition(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetFlowConnectionDefinition([NotNullWhenAttribute(true)] out IReadOnlyList<IInteraction> flowConnectionDefinition) => TryGetReference<IInteraction>(_flowConnectionDefinition, out flowConnectionDefinition);
    private bool SetFlowConnectionDefinitionRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _flowConnectionDefinition);
    private bool AddFlowConnectionDefinitionRaw(ReferenceTarget target) => AddReferencesRaw(target, _flowConnectionDefinition);
    private bool InsertFlowConnectionDefinitionRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _flowConnectionDefinition);
    private bool RemoveFlowConnectionDefinitionRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _flowConnectionDefinition);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddFlowConnectionDefinition(IEnumerable<IInteraction> nodes)
    {
        AddOptionalMultipleReference<IInteraction>(nodes, SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition, _flowConnectionDefinition, AddFlowConnectionDefinitionRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertFlowConnectionDefinition(int index, IEnumerable<IInteraction> nodes)
    {
        InsertOptionalMultipleReference<IInteraction>(index, nodes, SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition, _flowConnectionDefinition, InsertFlowConnectionDefinitionRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveFlowConnectionDefinition(IEnumerable<IInteraction> nodes)
    {
        RemoveOptionalMultipleReference<IInteraction>(nodes, SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition, _flowConnectionDefinition, RemoveFlowConnectionDefinitionRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _actionDefinition = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IActionUsage-actionDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IBehavior> ActionDefinition { get => ReferenceTargetNonNullTargets<IBehavior>(_actionDefinition, SysmlLanguage.Instance.IActionUsage_actionDefinition); init => AddActionDefinition(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetActionDefinition([NotNullWhenAttribute(true)] out IReadOnlyList<IBehavior> actionDefinition) => TryGetReference<IBehavior>(_actionDefinition, out actionDefinition);
    private bool SetActionDefinitionRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _actionDefinition);
    private bool AddActionDefinitionRaw(ReferenceTarget target) => AddReferencesRaw(target, _actionDefinition);
    private bool InsertActionDefinitionRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _actionDefinition);
    private bool RemoveActionDefinitionRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _actionDefinition);
/// <remarks>Optional Multiple Reference</remarks>
    IActionUsage IActionUsage.AddActionDefinition(IEnumerable<IBehavior> nodes) => AddActionDefinition(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddActionDefinition(IEnumerable<IBehavior> nodes)
    {
        AddOptionalMultipleReference<IBehavior>(nodes, SysmlLanguage.Instance.IActionUsage_actionDefinition, _actionDefinition, AddActionDefinitionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IActionUsage IActionUsage.InsertActionDefinition(int index, IEnumerable<IBehavior> nodes) => InsertActionDefinition(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertActionDefinition(int index, IEnumerable<IBehavior> nodes)
    {
        InsertOptionalMultipleReference<IBehavior>(index, nodes, SysmlLanguage.Instance.IActionUsage_actionDefinition, _actionDefinition, InsertActionDefinitionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IActionUsage IActionUsage.RemoveActionDefinition(IEnumerable<IBehavior> nodes) => RemoveActionDefinition(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveActionDefinition(IEnumerable<IBehavior> nodes)
    {
        RemoveOptionalMultipleReference<IBehavior>(nodes, SysmlLanguage.Instance.IActionUsage_actionDefinition, _actionDefinition, RemoveActionDefinitionRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _interaction = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IItemFlow-interaction")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IInteraction> Interaction { get => ReferenceTargetNonNullTargets<IInteraction>(_interaction, SysmlLanguage.Instance.IItemFlow_interaction); init => AddInteraction(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetInteraction([NotNullWhenAttribute(true)] out IReadOnlyList<IInteraction> interaction) => TryGetReference<IInteraction>(_interaction, out interaction);
    private bool SetInteractionRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _interaction);
    private bool AddInteractionRaw(ReferenceTarget target) => AddReferencesRaw(target, _interaction);
    private bool InsertInteractionRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _interaction);
    private bool RemoveInteractionRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _interaction);
/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.AddInteraction(IEnumerable<IInteraction> nodes) => AddInteraction(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddInteraction(IEnumerable<IInteraction> nodes)
    {
        AddOptionalMultipleReference<IInteraction>(nodes, SysmlLanguage.Instance.IItemFlow_interaction, _interaction, AddInteractionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.InsertInteraction(int index, IEnumerable<IInteraction> nodes) => InsertInteraction(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertInteraction(int index, IEnumerable<IInteraction> nodes)
    {
        InsertOptionalMultipleReference<IInteraction>(index, nodes, SysmlLanguage.Instance.IItemFlow_interaction, _interaction, InsertInteractionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.RemoveInteraction(IEnumerable<IInteraction> nodes) => RemoveInteraction(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveInteraction(IEnumerable<IInteraction> nodes)
    {
        RemoveOptionalMultipleReference<IInteraction>(nodes, SysmlLanguage.Instance.IItemFlow_interaction, _interaction, RemoveInteractionRaw);
        return this;
    }

    private ReferenceTarget? _itemFeature = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IItemFlow-itemFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public ItemFeature? ItemFeature { get => ReferenceTargetNonNullTarget<ItemFeature>(_itemFeature, SysmlLanguage.Instance.IItemFlow_itemFeature); set => SetItemFeature(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetItemFeature([NotNullWhenAttribute(true)] out ItemFeature? itemFeature)
    {
        itemFeature = ReferenceTargetNullableTarget<ItemFeature>(_itemFeature, SysmlLanguage.Instance.IItemFlow_itemFeature);
        return itemFeature != null;
    }

    private FlowConnectionUsage SetItemFeature(ReferenceTarget? value)
    {
        SetOptionalSingleReference<ItemFeature>(value, SysmlLanguage.Instance.IItemFlow_itemFeature, _itemFeature, SetItemFeatureRaw);
        return this;
    }

    private bool SetItemFeatureRaw(ReferenceTarget? value)
    {
        if (value == _itemFeature)
            return false;
        _itemFeature = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IItemFlow IItemFlow.SetItemFeature(ItemFeature? value) => SetItemFeature(value);
    /// <remarks>Optional Single Reference</remarks>
    public FlowConnectionUsage SetItemFeature(ItemFeature? value)
    {
        return SetItemFeature(ReferenceTarget.FromNodeOptional(value));
    }

    private readonly List<ReferenceTarget> _itemFlowEnd = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IItemFlow-itemFlowEnd")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<ItemFlowEnd> ItemFlowEnd { get => ReferenceTargetNonNullTargets<ItemFlowEnd>(_itemFlowEnd, SysmlLanguage.Instance.IItemFlow_itemFlowEnd); init => AddItemFlowEnd(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetItemFlowEnd([NotNullWhenAttribute(true)] out IReadOnlyList<ItemFlowEnd> itemFlowEnd) => TryGetReference<ItemFlowEnd>(_itemFlowEnd, out itemFlowEnd);
    private bool SetItemFlowEndRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _itemFlowEnd);
    private bool AddItemFlowEndRaw(ReferenceTarget target) => AddReferencesRaw(target, _itemFlowEnd);
    private bool InsertItemFlowEndRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _itemFlowEnd);
    private bool RemoveItemFlowEndRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _itemFlowEnd);
/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.AddItemFlowEnd(IEnumerable<ItemFlowEnd> nodes) => AddItemFlowEnd(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddItemFlowEnd(IEnumerable<ItemFlowEnd> nodes)
    {
        AddOptionalMultipleReference<ItemFlowEnd>(nodes, SysmlLanguage.Instance.IItemFlow_itemFlowEnd, _itemFlowEnd, AddItemFlowEndRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.InsertItemFlowEnd(int index, IEnumerable<ItemFlowEnd> nodes) => InsertItemFlowEnd(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertItemFlowEnd(int index, IEnumerable<ItemFlowEnd> nodes)
    {
        InsertOptionalMultipleReference<ItemFlowEnd>(index, nodes, SysmlLanguage.Instance.IItemFlow_itemFlowEnd, _itemFlowEnd, InsertItemFlowEndRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.RemoveItemFlowEnd(IEnumerable<ItemFlowEnd> nodes) => RemoveItemFlowEnd(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveItemFlowEnd(IEnumerable<ItemFlowEnd> nodes)
    {
        RemoveOptionalMultipleReference<ItemFlowEnd>(nodes, SysmlLanguage.Instance.IItemFlow_itemFlowEnd, _itemFlowEnd, RemoveItemFlowEndRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _itemType = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IItemFlow-itemType")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IClassifier> ItemType { get => ReferenceTargetNonNullTargets<IClassifier>(_itemType, SysmlLanguage.Instance.IItemFlow_itemType); init => AddItemType(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetItemType([NotNullWhenAttribute(true)] out IReadOnlyList<IClassifier> itemType) => TryGetReference<IClassifier>(_itemType, out itemType);
    private bool SetItemTypeRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _itemType);
    private bool AddItemTypeRaw(ReferenceTarget target) => AddReferencesRaw(target, _itemType);
    private bool InsertItemTypeRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _itemType);
    private bool RemoveItemTypeRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _itemType);
/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.AddItemType(IEnumerable<IClassifier> nodes) => AddItemType(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddItemType(IEnumerable<IClassifier> nodes)
    {
        AddOptionalMultipleReference<IClassifier>(nodes, SysmlLanguage.Instance.IItemFlow_itemType, _itemType, AddItemTypeRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.InsertItemType(int index, IEnumerable<IClassifier> nodes) => InsertItemType(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertItemType(int index, IEnumerable<IClassifier> nodes)
    {
        InsertOptionalMultipleReference<IClassifier>(index, nodes, SysmlLanguage.Instance.IItemFlow_itemType, _itemType, InsertItemTypeRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IItemFlow IItemFlow.RemoveItemType(IEnumerable<IClassifier> nodes) => RemoveItemType(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveItemType(IEnumerable<IClassifier> nodes)
    {
        RemoveOptionalMultipleReference<IClassifier>(nodes, SysmlLanguage.Instance.IItemFlow_itemType, _itemType, RemoveItemTypeRaw);
        return this;
    }

    private ReferenceTarget? _sourceOutputFeature = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IItemFlow-sourceOutputFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IFeature? SourceOutputFeature { get => ReferenceTargetNonNullTarget<IFeature>(_sourceOutputFeature, SysmlLanguage.Instance.IItemFlow_sourceOutputFeature); set => SetSourceOutputFeature(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetSourceOutputFeature([NotNullWhenAttribute(true)] out IFeature? sourceOutputFeature)
    {
        sourceOutputFeature = ReferenceTargetNullableTarget<IFeature>(_sourceOutputFeature, SysmlLanguage.Instance.IItemFlow_sourceOutputFeature);
        return sourceOutputFeature != null;
    }

    private FlowConnectionUsage SetSourceOutputFeature(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IFeature>(value, SysmlLanguage.Instance.IItemFlow_sourceOutputFeature, _sourceOutputFeature, SetSourceOutputFeatureRaw);
        return this;
    }

    private bool SetSourceOutputFeatureRaw(ReferenceTarget? value)
    {
        if (value == _sourceOutputFeature)
            return false;
        _sourceOutputFeature = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IItemFlow IItemFlow.SetSourceOutputFeature(IFeature? value) => SetSourceOutputFeature(value);
    /// <remarks>Optional Single Reference</remarks>
    public FlowConnectionUsage SetSourceOutputFeature(IFeature? value)
    {
        return SetSourceOutputFeature(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _targetInputFeature = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IItemFlow-targetInputFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IFeature? TargetInputFeature { get => ReferenceTargetNonNullTarget<IFeature>(_targetInputFeature, SysmlLanguage.Instance.IItemFlow_targetInputFeature); set => SetTargetInputFeature(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetTargetInputFeature([NotNullWhenAttribute(true)] out IFeature? targetInputFeature)
    {
        targetInputFeature = ReferenceTargetNullableTarget<IFeature>(_targetInputFeature, SysmlLanguage.Instance.IItemFlow_targetInputFeature);
        return targetInputFeature != null;
    }

    private FlowConnectionUsage SetTargetInputFeature(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IFeature>(value, SysmlLanguage.Instance.IItemFlow_targetInputFeature, _targetInputFeature, SetTargetInputFeatureRaw);
        return this;
    }

    private bool SetTargetInputFeatureRaw(ReferenceTarget? value)
    {
        if (value == _targetInputFeature)
            return false;
        _targetInputFeature = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IItemFlow IItemFlow.SetTargetInputFeature(IFeature? value) => SetTargetInputFeature(value);
    /// <remarks>Optional Single Reference</remarks>
    public FlowConnectionUsage SetTargetInputFeature(IFeature? value)
    {
        return SetTargetInputFeature(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _individualDefinition = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-individualDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public OccurrenceDefinition? IndividualDefinition { get => ReferenceTargetNonNullTarget<OccurrenceDefinition>(_individualDefinition, SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition); set => SetIndividualDefinition(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetIndividualDefinition([NotNullWhenAttribute(true)] out OccurrenceDefinition? individualDefinition)
    {
        individualDefinition = ReferenceTargetNullableTarget<OccurrenceDefinition>(_individualDefinition, SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition);
        return individualDefinition != null;
    }

    private FlowConnectionUsage SetIndividualDefinition(ReferenceTarget? value)
    {
        SetOptionalSingleReference<OccurrenceDefinition>(value, SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition, _individualDefinition, SetIndividualDefinitionRaw);
        return this;
    }

    private bool SetIndividualDefinitionRaw(ReferenceTarget? value)
    {
        if (value == _individualDefinition)
            return false;
        _individualDefinition = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IOccurrenceUsage IOccurrenceUsage.SetIndividualDefinition(OccurrenceDefinition? value) => SetIndividualDefinition(value);
    /// <remarks>Optional Single Reference</remarks>
    public FlowConnectionUsage SetIndividualDefinition(OccurrenceDefinition? value)
    {
        return SetIndividualDefinition(ReferenceTarget.FromNodeOptional(value));
    }

    private bool? _isIndividual = null;
    private bool SetIsIndividualRaw(bool? value)
    {
        if (value is null && _isIndividual is null || value is not null && value.Equals(_isIndividual))
            return false;
        _isIndividual = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsIndividual has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-isIndividual")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsIndividual { get => _isIndividual ?? throw new UnsetFeatureException(SysmlLanguage.Instance.IOccurrenceUsage_isIndividual); set => SetIsIndividual(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsIndividual([NotNullWhenAttribute(true)] out bool? isIndividual)
    {
        isIndividual = _isIndividual;
        return isIndividual != null;
    }

/// <remarks>Required Property</remarks>
    IOccurrenceUsage IOccurrenceUsage.SetIsIndividual(bool value) => SetIsIndividual(value);
    /// <remarks>Required Property</remarks>
    public FlowConnectionUsage SetIsIndividual(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, SysmlLanguage.Instance.IOccurrenceUsage_isIndividual, _isIndividual, SetIsIndividualRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _occurrenceDefinition = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-occurrenceDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IClass> OccurrenceDefinition { get => ReferenceTargetNonNullTargets<IClass>(_occurrenceDefinition, SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition); init => AddOccurrenceDefinition(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetOccurrenceDefinition([NotNullWhenAttribute(true)] out IReadOnlyList<IClass> occurrenceDefinition) => TryGetReference<IClass>(_occurrenceDefinition, out occurrenceDefinition);
    private bool SetOccurrenceDefinitionRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _occurrenceDefinition);
    private bool AddOccurrenceDefinitionRaw(ReferenceTarget target) => AddReferencesRaw(target, _occurrenceDefinition);
    private bool InsertOccurrenceDefinitionRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _occurrenceDefinition);
    private bool RemoveOccurrenceDefinitionRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _occurrenceDefinition);
/// <remarks>Optional Multiple Reference</remarks>
    IOccurrenceUsage IOccurrenceUsage.AddOccurrenceDefinition(IEnumerable<IClass> nodes) => AddOccurrenceDefinition(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddOccurrenceDefinition(IEnumerable<IClass> nodes)
    {
        AddOptionalMultipleReference<IClass>(nodes, SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition, _occurrenceDefinition, AddOccurrenceDefinitionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IOccurrenceUsage IOccurrenceUsage.InsertOccurrenceDefinition(int index, IEnumerable<IClass> nodes) => InsertOccurrenceDefinition(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertOccurrenceDefinition(int index, IEnumerable<IClass> nodes)
    {
        InsertOptionalMultipleReference<IClass>(index, nodes, SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition, _occurrenceDefinition, InsertOccurrenceDefinitionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IOccurrenceUsage IOccurrenceUsage.RemoveOccurrenceDefinition(IEnumerable<IClass> nodes) => RemoveOccurrenceDefinition(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveOccurrenceDefinition(IEnumerable<IClass> nodes)
    {
        RemoveOptionalMultipleReference<IClass>(nodes, SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition, _occurrenceDefinition, RemoveOccurrenceDefinitionRaw);
        return this;
    }

    private PortionKind? _portionKind = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-portionKind")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public PortionKind? PortionKind { get => _portionKind; set => SetPortionKind(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetPortionKind([NotNullWhenAttribute(true)] out PortionKind? portionKind)
    {
        portionKind = _portionKind;
        return portionKind != null;
    }

    private bool SetPortionKindRaw(PortionKind? value)
    {
        if (value == _portionKind)
            return false;
        _portionKind = value;
        return true;
    }

/// <remarks>Optional Property</remarks>
    IOccurrenceUsage IOccurrenceUsage.SetPortionKind(PortionKind? value) => SetPortionKind(value);
    /// <remarks>Optional Property</remarks>
    public FlowConnectionUsage SetPortionKind(PortionKind? value)
    {
        SetOptionalValueTypeProperty<PortionKind>(value, SysmlLanguage.Instance.IOccurrenceUsage_portionKind, _portionKind, SetPortionKindRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _behavior = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IStep-behavior")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IBehavior> Behavior { get => ReferenceTargetNonNullTargets<IBehavior>(_behavior, SysmlLanguage.Instance.IStep_behavior); init => AddBehavior(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetBehavior([NotNullWhenAttribute(true)] out IReadOnlyList<IBehavior> behavior) => TryGetReference<IBehavior>(_behavior, out behavior);
    private bool SetBehaviorRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _behavior);
    private bool AddBehaviorRaw(ReferenceTarget target) => AddReferencesRaw(target, _behavior);
    private bool InsertBehaviorRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _behavior);
    private bool RemoveBehaviorRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _behavior);
/// <remarks>Optional Multiple Reference</remarks>
    IStep IStep.AddBehavior(IEnumerable<IBehavior> nodes) => AddBehavior(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddBehavior(IEnumerable<IBehavior> nodes)
    {
        AddOptionalMultipleReference<IBehavior>(nodes, SysmlLanguage.Instance.IStep_behavior, _behavior, AddBehaviorRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IStep IStep.InsertBehavior(int index, IEnumerable<IBehavior> nodes) => InsertBehavior(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertBehavior(int index, IEnumerable<IBehavior> nodes)
    {
        InsertOptionalMultipleReference<IBehavior>(index, nodes, SysmlLanguage.Instance.IStep_behavior, _behavior, InsertBehaviorRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IStep IStep.RemoveBehavior(IEnumerable<IBehavior> nodes) => RemoveBehavior(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveBehavior(IEnumerable<IBehavior> nodes)
    {
        RemoveOptionalMultipleReference<IBehavior>(nodes, SysmlLanguage.Instance.IStep_behavior, _behavior, RemoveBehaviorRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _parameter = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IStep-parameter")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IFeature> Parameter { get => ReferenceTargetNonNullTargets<IFeature>(_parameter, SysmlLanguage.Instance.IStep_parameter); init => AddParameter(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetParameter([NotNullWhenAttribute(true)] out IReadOnlyList<IFeature> parameter) => TryGetReference<IFeature>(_parameter, out parameter);
    private bool SetParameterRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _parameter);
    private bool AddParameterRaw(ReferenceTarget target) => AddReferencesRaw(target, _parameter);
    private bool InsertParameterRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _parameter);
    private bool RemoveParameterRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _parameter);
/// <remarks>Optional Multiple Reference</remarks>
    IStep IStep.AddParameter(IEnumerable<IFeature> nodes) => AddParameter(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage AddParameter(IEnumerable<IFeature> nodes)
    {
        AddOptionalMultipleReference<IFeature>(nodes, SysmlLanguage.Instance.IStep_parameter, _parameter, AddParameterRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IStep IStep.InsertParameter(int index, IEnumerable<IFeature> nodes) => InsertParameter(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage InsertParameter(int index, IEnumerable<IFeature> nodes)
    {
        InsertOptionalMultipleReference<IFeature>(index, nodes, SysmlLanguage.Instance.IStep_parameter, _parameter, InsertParameterRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IStep IStep.RemoveParameter(IEnumerable<IFeature> nodes) => RemoveParameter(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public FlowConnectionUsage RemoveParameter(IEnumerable<IFeature> nodes)
    {
        RemoveOptionalMultipleReference<IFeature>(nodes, SysmlLanguage.Instance.IStep_parameter, _parameter, RemoveParameterRaw);
        return this;
    }

    public FlowConnectionUsage(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.FlowConnectionUsage;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(feature))
        {
            result = FlowConnectionDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(feature))
        {
            result = ActionDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(feature))
        {
            result = Interaction;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFeature.EqualsIdentity(feature))
        {
            result = ItemFeature;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(feature))
        {
            result = ItemFlowEnd;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(feature))
        {
            result = ItemType;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_sourceOutputFeature.EqualsIdentity(feature))
        {
            result = SourceOutputFeature;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_targetInputFeature.EqualsIdentity(feature))
        {
            result = TargetInputFeature;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition.EqualsIdentity(feature))
        {
            result = IndividualDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_isIndividual.EqualsIdentity(feature))
        {
            result = IsIndividual;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(feature))
        {
            result = OccurrenceDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_portionKind.EqualsIdentity(feature))
        {
            result = PortionKind;
            return true;
        }

        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(feature))
        {
            result = Behavior;
            return true;
        }

        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(feature))
        {
            result = Parameter;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IOccurrenceUsage_isIndividual.EqualsIdentity(feature))
        {
            result = _isIndividual;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_portionKind.EqualsIdentity(feature))
        {
            result = _portionKind;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IItemFlow_itemFeature.EqualsIdentity(feature))
        {
            result = _itemFeature;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_sourceOutputFeature.EqualsIdentity(feature))
        {
            result = _sourceOutputFeature;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_targetInputFeature.EqualsIdentity(feature))
        {
            result = _targetInputFeature;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition.EqualsIdentity(feature))
        {
            result = _individualDefinition;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(feature))
        {
            result = _flowConnectionDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(feature))
        {
            result = _actionDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(feature))
        {
            result = _interaction;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(feature))
        {
            result = _itemFlowEnd;
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(feature))
        {
            result = _itemType;
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(feature))
        {
            result = _occurrenceDefinition;
            return true;
        }

        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(feature))
        {
            result = _behavior;
            return true;
        }

        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(feature))
        {
            result = _parameter;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IInteraction>(value, SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition, _flowConnectionDefinition, SetFlowConnectionDefinitionRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IBehavior>(value, SysmlLanguage.Instance.IActionUsage_actionDefinition, _actionDefinition, SetActionDefinitionRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IInteraction>(value, SysmlLanguage.Instance.IItemFlow_interaction, _interaction, SetInteractionRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFeature.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.ItemFeature)
            {
                SetItemFeature((LionWeb.Demo.SysMl2.Languages.SysMl2.ItemFeature? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetItemFeature(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<ItemFlowEnd>(value, SysmlLanguage.Instance.IItemFlow_itemFlowEnd, _itemFlowEnd, SetItemFlowEndRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IClassifier>(value, SysmlLanguage.Instance.IItemFlow_itemType, _itemType, SetItemTypeRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_sourceOutputFeature.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature)
            {
                SetSourceOutputFeature((LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetSourceOutputFeature(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IItemFlow_targetInputFeature.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature)
            {
                SetTargetInputFeature((LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetTargetInputFeature(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.OccurrenceDefinition)
            {
                SetIndividualDefinition((LionWeb.Demo.SysMl2.Languages.SysMl2.OccurrenceDefinition? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetIndividualDefinition(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_isIndividual.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsIndividual(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IClass>(value, SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition, _occurrenceDefinition, SetOccurrenceDefinitionRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_portionKind.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.PortionKind)
            {
                SetPortionKind((LionWeb.Demo.SysMl2.Languages.SysMl2.PortionKind? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IBehavior>(value, SysmlLanguage.Instance.IStep_behavior, _behavior, SetBehaviorRaw);
            return true;
        }

        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IFeature>(value, SysmlLanguage.Instance.IStep_parameter, _parameter, SetParameterRaw);
            return true;
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.IOccurrenceUsage_isIndividual.EqualsIdentity(feature) && value is null or bool)
            return SetIsIndividualRaw((bool? )value);
        if (SysmlLanguage.Instance.IOccurrenceUsage_portionKind.EqualsIdentity(feature) && value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.PortionKind)
            return SetPortionKindRaw((LionWeb.Demo.SysMl2.Languages.SysMl2.PortionKind? )value);
        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.IItemFlow_itemFeature.EqualsIdentity(feature))
            return SetItemFeatureRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_sourceOutputFeature.EqualsIdentity(feature))
            return SetSourceOutputFeatureRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_targetInputFeature.EqualsIdentity(feature))
            return SetTargetInputFeatureRaw(value);
        if (SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition.EqualsIdentity(feature))
            return SetIndividualDefinitionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetFlowConnectionDefinition(out _))
            result.Add(SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition);
        if (TryGetActionDefinition(out _))
            result.Add(SysmlLanguage.Instance.IActionUsage_actionDefinition);
        if (TryGetInteraction(out _))
            result.Add(SysmlLanguage.Instance.IItemFlow_interaction);
        if (TryGetItemFeature(out _))
            result.Add(SysmlLanguage.Instance.IItemFlow_itemFeature);
        if (TryGetItemFlowEnd(out _))
            result.Add(SysmlLanguage.Instance.IItemFlow_itemFlowEnd);
        if (TryGetItemType(out _))
            result.Add(SysmlLanguage.Instance.IItemFlow_itemType);
        if (TryGetSourceOutputFeature(out _))
            result.Add(SysmlLanguage.Instance.IItemFlow_sourceOutputFeature);
        if (TryGetTargetInputFeature(out _))
            result.Add(SysmlLanguage.Instance.IItemFlow_targetInputFeature);
        if (TryGetIndividualDefinition(out _))
            result.Add(SysmlLanguage.Instance.IOccurrenceUsage_individualDefinition);
        if (TryGetIsIndividual(out _))
            result.Add(SysmlLanguage.Instance.IOccurrenceUsage_isIndividual);
        if (TryGetOccurrenceDefinition(out _))
            result.Add(SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition);
        if (TryGetPortionKind(out _))
            result.Add(SysmlLanguage.Instance.IOccurrenceUsage_portionKind);
        if (TryGetBehavior(out _))
            result.Add(SysmlLanguage.Instance.IStep_behavior);
        if (TryGetParameter(out _))
            result.Add(SysmlLanguage.Instance.IStep_parameter);
        return result;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(feature))
            return AddFlowConnectionDefinitionRaw(value);
        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(feature))
            return AddActionDefinitionRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(feature))
            return AddInteractionRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(feature))
            return AddItemFlowEndRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(feature))
            return AddItemTypeRaw(value);
        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(feature))
            return AddOccurrenceDefinitionRaw(value);
        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(feature))
            return AddBehaviorRaw(value);
        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(feature))
            return AddParameterRaw(value);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(feature))
            return InsertFlowConnectionDefinitionRaw(index, value);
        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(feature))
            return InsertActionDefinitionRaw(index, value);
        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(feature))
            return InsertInteractionRaw(index, value);
        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(feature))
            return InsertItemFlowEndRaw(index, value);
        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(feature))
            return InsertItemTypeRaw(index, value);
        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(feature))
            return InsertOccurrenceDefinitionRaw(index, value);
        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(feature))
            return InsertBehaviorRaw(index, value);
        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(feature))
            return InsertParameterRaw(index, value);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(feature))
            return RemoveFlowConnectionDefinitionRaw(value);
        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(feature))
            return RemoveActionDefinitionRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(feature))
            return RemoveInteractionRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(feature))
            return RemoveItemFlowEndRaw(value);
        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(feature))
            return RemoveItemTypeRaw(value);
        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(feature))
            return RemoveOccurrenceDefinitionRaw(value);
        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(feature))
            return RemoveBehaviorRaw(value);
        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(feature))
            return RemoveParameterRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(link))
        {
            AddFlowConnectionDefinition(SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IInteraction>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(link))
        {
            AddActionDefinition(SysmlLanguage.Instance.IActionUsage_actionDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IBehavior>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(link))
        {
            AddInteraction(SysmlLanguage.Instance.IItemFlow_interaction.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IInteraction>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(link))
        {
            AddItemFlowEnd(SysmlLanguage.Instance.IItemFlow_itemFlowEnd.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ItemFlowEnd>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(link))
        {
            AddItemType(SysmlLanguage.Instance.IItemFlow_itemType.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IClassifier>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(link))
        {
            AddOccurrenceDefinition(SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IClass>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(link))
        {
            AddBehavior(SysmlLanguage.Instance.IStep_behavior.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IBehavior>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(link))
        {
            AddParameter(SysmlLanguage.Instance.IStep_parameter.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(link))
        {
            InsertFlowConnectionDefinition(index, SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IInteraction>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(link))
        {
            InsertActionDefinition(index, SysmlLanguage.Instance.IActionUsage_actionDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IBehavior>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(link))
        {
            InsertInteraction(index, SysmlLanguage.Instance.IItemFlow_interaction.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IInteraction>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(link))
        {
            InsertItemFlowEnd(index, SysmlLanguage.Instance.IItemFlow_itemFlowEnd.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ItemFlowEnd>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(link))
        {
            InsertItemType(index, SysmlLanguage.Instance.IItemFlow_itemType.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IClassifier>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(link))
        {
            InsertOccurrenceDefinition(index, SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IClass>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(link))
        {
            InsertBehavior(index, SysmlLanguage.Instance.IStep_behavior.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IBehavior>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(link))
        {
            InsertParameter(index, SysmlLanguage.Instance.IStep_parameter.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.EqualsIdentity(link))
        {
            RemoveFlowConnectionDefinition(SysmlLanguage.Instance.FlowConnectionUsage_flowConnectionDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IInteraction>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IActionUsage_actionDefinition.EqualsIdentity(link))
        {
            RemoveActionDefinition(SysmlLanguage.Instance.IActionUsage_actionDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IBehavior>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_interaction.EqualsIdentity(link))
        {
            RemoveInteraction(SysmlLanguage.Instance.IItemFlow_interaction.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IInteraction>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemFlowEnd.EqualsIdentity(link))
        {
            RemoveItemFlowEnd(SysmlLanguage.Instance.IItemFlow_itemFlowEnd.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ItemFlowEnd>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IItemFlow_itemType.EqualsIdentity(link))
        {
            RemoveItemType(SysmlLanguage.Instance.IItemFlow_itemType.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IClassifier>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.EqualsIdentity(link))
        {
            RemoveOccurrenceDefinition(SysmlLanguage.Instance.IOccurrenceUsage_occurrenceDefinition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IClass>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IStep_behavior.EqualsIdentity(link))
        {
            RemoveBehavior(SysmlLanguage.Instance.IStep_behavior.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IBehavior>(value));
            return true;
        }

        if (SysmlLanguage.Instance.IStep_parameter.EqualsIdentity(link))
        {
            RemoveParameter(SysmlLanguage.Instance.IStep_parameter.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature>(value));
            return true;
        }

        return false;
    }
}

