// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ForLoopActionUsage")]
public partial class ForLoopActionUsage : LoopActionUsage
{
    private ReferenceTarget? _loopVariable = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If LoopVariable has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ForLoopActionUsage-loopVariable")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public ReferenceUsage LoopVariable { get => ReferenceTargetNonNullTarget<ReferenceUsage>(_loopVariable, SysmlLanguage.Instance.ForLoopActionUsage_loopVariable) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ForLoopActionUsage_loopVariable); set => SetLoopVariable(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetLoopVariable([NotNullWhenAttribute(true)] out ReferenceUsage? loopVariable)
    {
        loopVariable = ReferenceTargetNullableTarget<ReferenceUsage>(_loopVariable, SysmlLanguage.Instance.ForLoopActionUsage_loopVariable);
        return loopVariable != null;
    }

    private ForLoopActionUsage SetLoopVariable(ReferenceTarget? value)
    {
        SetRequiredSingleReference<ReferenceUsage>(value, SysmlLanguage.Instance.ForLoopActionUsage_loopVariable, _loopVariable, SetLoopVariableRaw);
        return this;
    }

    private bool SetLoopVariableRaw(ReferenceTarget? value)
    {
        if (value == _loopVariable)
            return false;
        _loopVariable = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ForLoopActionUsage SetLoopVariable(ReferenceUsage value)
    {
        return SetLoopVariable(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _seqArgument = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If SeqArgument has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ForLoopActionUsage-seqArgument")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IExpression SeqArgument { get => ReferenceTargetNonNullTarget<IExpression>(_seqArgument, SysmlLanguage.Instance.ForLoopActionUsage_seqArgument) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ForLoopActionUsage_seqArgument); set => SetSeqArgument(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetSeqArgument([NotNullWhenAttribute(true)] out IExpression? seqArgument)
    {
        seqArgument = ReferenceTargetNullableTarget<IExpression>(_seqArgument, SysmlLanguage.Instance.ForLoopActionUsage_seqArgument);
        return seqArgument != null;
    }

    private ForLoopActionUsage SetSeqArgument(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IExpression>(value, SysmlLanguage.Instance.ForLoopActionUsage_seqArgument, _seqArgument, SetSeqArgumentRaw);
        return this;
    }

    private bool SetSeqArgumentRaw(ReferenceTarget? value)
    {
        if (value == _seqArgument)
            return false;
        _seqArgument = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ForLoopActionUsage SetSeqArgument(IExpression value)
    {
        return SetSeqArgument(ReferenceTarget.FromNodeOptional(value));
    }

    public ForLoopActionUsage(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ForLoopActionUsage;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ForLoopActionUsage_loopVariable.EqualsIdentity(feature))
        {
            result = LoopVariable;
            return true;
        }

        if (SysmlLanguage.Instance.ForLoopActionUsage_seqArgument.EqualsIdentity(feature))
        {
            result = SeqArgument;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ForLoopActionUsage_loopVariable.EqualsIdentity(feature))
        {
            result = _loopVariable;
            return true;
        }

        if (SysmlLanguage.Instance.ForLoopActionUsage_seqArgument.EqualsIdentity(feature))
        {
            result = _seqArgument;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ForLoopActionUsage_loopVariable.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.ReferenceUsage v)
            {
                SetLoopVariable(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetLoopVariable(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.ForLoopActionUsage_seqArgument.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IExpression v)
            {
                SetSeqArgument(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetSeqArgument(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ForLoopActionUsage_loopVariable.EqualsIdentity(feature))
            return SetLoopVariableRaw(value);
        if (SysmlLanguage.Instance.ForLoopActionUsage_seqArgument.EqualsIdentity(feature))
            return SetSeqArgumentRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetLoopVariable(out _))
            result.Add(SysmlLanguage.Instance.ForLoopActionUsage_loopVariable);
        if (TryGetSeqArgument(out _))
            result.Add(SysmlLanguage.Instance.ForLoopActionUsage_seqArgument);
        return result;
    }
}

