// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IBehavior")]
public partial interface IBehavior : IClass
{
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IBehavior-parameter")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IFeature> Parameter { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IBehavior AddParameter(IEnumerable<IFeature> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IBehavior InsertParameter(int index, IEnumerable<IFeature> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IBehavior RemoveParameter(IEnumerable<IFeature> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IBehavior-step")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IStep> Step { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IBehavior AddStep(IEnumerable<IStep> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IBehavior InsertStep(int index, IEnumerable<IStep> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IBehavior RemoveStep(IEnumerable<IStep> nodes);
}

