// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement")]
public partial interface IElement : INode
{
    /// <remarks>Optional Multiple Containment</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-aliasIdsContainer")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
    public IReadOnlyList<AliasIdsContainer> AliasIdsContainer { get; init; }

    /// <remarks>Optional Multiple Containment</remarks>
    public IElement AddAliasIdsContainer(IEnumerable<AliasIdsContainer> nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public IElement InsertAliasIdsContainer(int index, IEnumerable<AliasIdsContainer> nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public IElement RemoveAliasIdsContainer(IEnumerable<AliasIdsContainer> nodes);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-declaredName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? DeclaredName { get; set; }

    /// <remarks>Optional Property</remarks>
    public IElement SetDeclaredName(string? value);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-declaredShortName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? DeclaredShortName { get; set; }

    /// <remarks>Optional Property</remarks>
    public IElement SetDeclaredShortName(string? value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-documentation")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Documentation> Documentation_ { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IElement AddDocumentation(IEnumerable<Documentation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement InsertDocumentation(int index, IEnumerable<Documentation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement RemoveDocumentation(IEnumerable<Documentation> nodes);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-elementId")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public string ElementId { get; set; }

    /// <remarks>Required Property</remarks>
    public IElement SetElementId(string value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-isImpliedIncluded")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsImpliedIncluded { get; set; }

    /// <remarks>Required Property</remarks>
    public IElement SetIsImpliedIncluded(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-isLibraryElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsLibraryElement { get; set; }

    /// <remarks>Required Property</remarks>
    public IElement SetIsLibraryElement(bool value);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-name")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? Name { get; set; }

    /// <remarks>Optional Property</remarks>
    public IElement SetName(string? value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-ownedAnnotation")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Annotation> OwnedAnnotation { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IElement AddOwnedAnnotation(IEnumerable<Annotation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement InsertOwnedAnnotation(int index, IEnumerable<Annotation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement RemoveOwnedAnnotation(IEnumerable<Annotation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-ownedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IElement> OwnedElement { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IElement AddOwnedElement(IEnumerable<IElement> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement InsertOwnedElement(int index, IEnumerable<IElement> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement RemoveOwnedElement(IEnumerable<IElement> nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-ownedRelationship")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
    public IReadOnlyList<IRelationship> OwnedRelationship { get; init; }

    /// <remarks>Optional Multiple Containment</remarks>
    public IElement AddOwnedRelationship(IEnumerable<IRelationship> nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public IElement InsertOwnedRelationship(int index, IEnumerable<IRelationship> nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public IElement RemoveOwnedRelationship(IEnumerable<IRelationship> nodes);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-owner")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IElement? Owner { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IElement SetOwner(IElement? value);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-owningMembership")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public OwningMembership? OwningMembership_ { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IElement SetOwningMembership(OwningMembership? value);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-owningNamespace")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public INamespace? OwningNamespace { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IElement SetOwningNamespace(INamespace? value);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-owningRelationship")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IRelationship? OwningRelationship { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IElement SetOwningRelationship(IRelationship? value);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-qualifiedName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? QualifiedName { get; set; }

    /// <remarks>Optional Property</remarks>
    public IElement SetQualifiedName(string? value);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-shortName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? ShortName { get; set; }

    /// <remarks>Optional Property</remarks>
    public IElement SetShortName(string? value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IElement-textualRepresentation")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<TextualRepresentation> TextualRepresentation_ { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IElement AddTextualRepresentation(IEnumerable<TextualRepresentation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement InsertTextualRepresentation(int index, IEnumerable<TextualRepresentation> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IElement RemoveTextualRepresentation(IEnumerable<TextualRepresentation> nodes);
}

