// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature")]
public partial interface IFeature : IType
{
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-chainingFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IFeature> ChainingFeature { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddChainingFeature(IEnumerable<IFeature> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertChainingFeature(int index, IEnumerable<IFeature> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveChainingFeature(IEnumerable<IFeature> nodes);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-crossFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IFeature? CrossFeature { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IFeature SetCrossFeature(IFeature? value);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-direction")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public FeatureDirectionKind? Direction { get; set; }

    /// <remarks>Optional Property</remarks>
    public IFeature SetDirection(FeatureDirectionKind? value);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-endOwningType")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IType? EndOwningType { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IFeature SetEndOwningType(IType? value);
    /// <remarks>Required Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-featureTarget")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature FeatureTarget { get; set; }

    /// <remarks>Required Single Reference</remarks>
    public IFeature SetFeatureTarget(IFeature value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-featuringType")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IType> FeaturingType { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddFeaturingType(IEnumerable<IType> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertFeaturingType(int index, IEnumerable<IType> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveFeaturingType(IEnumerable<IType> nodes);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isComposite")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsComposite { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsComposite(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isDerived")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsDerived { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsDerived(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isEnd")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsEnd { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsEnd(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isNonunique")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsNonunique { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsNonunique(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isOrdered")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsOrdered { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsOrdered(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isPortion")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsPortion { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsPortion(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isReadOnly")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsReadOnly { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsReadOnly(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-isUnique")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsUnique { get; set; }

    /// <remarks>Required Property</remarks>
    public IFeature SetIsUnique(bool value);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedCrossSubsetting")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public CrossSubsetting? OwnedCrossSubsetting { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IFeature SetOwnedCrossSubsetting(CrossSubsetting? value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedFeatureChaining")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<FeatureChaining> OwnedFeatureChaining { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddOwnedFeatureChaining(IEnumerable<FeatureChaining> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertOwnedFeatureChaining(int index, IEnumerable<FeatureChaining> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveOwnedFeatureChaining(IEnumerable<FeatureChaining> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedFeatureInverting")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<FeatureInverting> OwnedFeatureInverting { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddOwnedFeatureInverting(IEnumerable<FeatureInverting> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertOwnedFeatureInverting(int index, IEnumerable<FeatureInverting> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveOwnedFeatureInverting(IEnumerable<FeatureInverting> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedRedefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Redefinition> OwnedRedefinition { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddOwnedRedefinition(IEnumerable<Redefinition> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertOwnedRedefinition(int index, IEnumerable<Redefinition> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveOwnedRedefinition(IEnumerable<Redefinition> nodes);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedReferenceSubsetting")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public ReferenceSubsetting? OwnedReferenceSubsetting { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IFeature SetOwnedReferenceSubsetting(ReferenceSubsetting? value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedSubsetting")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Subsetting> OwnedSubsetting { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddOwnedSubsetting(IEnumerable<Subsetting> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertOwnedSubsetting(int index, IEnumerable<Subsetting> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveOwnedSubsetting(IEnumerable<Subsetting> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedTypeFeaturing")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<TypeFeaturing> OwnedTypeFeaturing { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddOwnedTypeFeaturing(IEnumerable<TypeFeaturing> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertOwnedTypeFeaturing(int index, IEnumerable<TypeFeaturing> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveOwnedTypeFeaturing(IEnumerable<TypeFeaturing> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-ownedTyping")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<FeatureTyping> OwnedTyping { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddOwnedTyping(IEnumerable<FeatureTyping> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertOwnedTyping(int index, IEnumerable<FeatureTyping> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveOwnedTyping(IEnumerable<FeatureTyping> nodes);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-owningFeatureMembership")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public FeatureMembership? OwningFeatureMembership { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IFeature SetOwningFeatureMembership(FeatureMembership? value);
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-owningType")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IType? OwningType { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IFeature SetOwningType(IType? value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IFeature-type")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IType> Type { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature AddType(IEnumerable<IType> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature InsertType(int index, IEnumerable<IType> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IFeature RemoveType(IEnumerable<IType> nodes);
}

