// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IImport")]
public partial interface IImport : IRelationship
{
    /// <remarks>Required Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IImport-importedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IElement ImportedElement { get; set; }

    /// <remarks>Required Single Reference</remarks>
    public IImport SetImportedElement(IElement value);
    /// <remarks>Required Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IImport-importOwningNamespace")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public INamespace ImportOwningNamespace { get; set; }

    /// <remarks>Required Single Reference</remarks>
    public IImport SetImportOwningNamespace(INamespace value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IImport-isImportAll")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsImportAll { get; set; }

    /// <remarks>Required Property</remarks>
    public IImport SetIsImportAll(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IImport-isRecursive")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsRecursive { get; set; }

    /// <remarks>Required Property</remarks>
    public IImport SetIsRecursive(bool value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IImport-visibility")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public VisibilityKind Visibility { get; set; }

    /// <remarks>Required Property</remarks>
    public IImport SetVisibility(VisibilityKind value);
}

