// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IncludeUseCaseUsage")]
public partial class IncludeUseCaseUsage : UseCaseUsage, IPerformActionUsage
{
    private ReferenceTarget? _eventOccurrence = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If EventOccurrence has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IEventOccurrenceUsage-eventOccurrence")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IOccurrenceUsage EventOccurrence { get => ReferenceTargetNonNullTarget<IOccurrenceUsage>(_eventOccurrence, SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence); set => SetEventOccurrence(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetEventOccurrence([NotNullWhenAttribute(true)] out IOccurrenceUsage? eventOccurrence)
    {
        eventOccurrence = ReferenceTargetNullableTarget<IOccurrenceUsage>(_eventOccurrence, SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence);
        return eventOccurrence != null;
    }

    private IncludeUseCaseUsage SetEventOccurrence(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IOccurrenceUsage>(value, SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence, _eventOccurrence, SetEventOccurrenceRaw);
        return this;
    }

    private bool SetEventOccurrenceRaw(ReferenceTarget? value)
    {
        if (value == _eventOccurrence)
            return false;
        _eventOccurrence = value;
        return true;
    }

/// <remarks>Required Single Reference</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
    IEventOccurrenceUsage IEventOccurrenceUsage.SetEventOccurrence(IOccurrenceUsage value) => SetEventOccurrence(value);
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public IncludeUseCaseUsage SetEventOccurrence(IOccurrenceUsage value)
    {
        return SetEventOccurrence(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _useCaseIncluded = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If UseCaseIncluded has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IncludeUseCaseUsage-useCaseIncluded")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public UseCaseUsage UseCaseIncluded { get => ReferenceTargetNonNullTarget<UseCaseUsage>(_useCaseIncluded, SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded); set => SetUseCaseIncluded(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetUseCaseIncluded([NotNullWhenAttribute(true)] out UseCaseUsage? useCaseIncluded)
    {
        useCaseIncluded = ReferenceTargetNullableTarget<UseCaseUsage>(_useCaseIncluded, SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded);
        return useCaseIncluded != null;
    }

    private IncludeUseCaseUsage SetUseCaseIncluded(ReferenceTarget? value)
    {
        SetRequiredSingleReference<UseCaseUsage>(value, SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded, _useCaseIncluded, SetUseCaseIncludedRaw);
        return this;
    }

    private bool SetUseCaseIncludedRaw(ReferenceTarget? value)
    {
        if (value == _useCaseIncluded)
            return false;
        _useCaseIncluded = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public IncludeUseCaseUsage SetUseCaseIncluded(UseCaseUsage value)
    {
        return SetUseCaseIncluded(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _performedAction = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If PerformedAction has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IPerformActionUsage-performedAction")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IActionUsage PerformedAction { get => ReferenceTargetNonNullTarget<IActionUsage>(_performedAction, SysmlLanguage.Instance.IPerformActionUsage_performedAction) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.IPerformActionUsage_performedAction); set => SetPerformedAction(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetPerformedAction([NotNullWhenAttribute(true)] out IActionUsage? performedAction)
    {
        performedAction = ReferenceTargetNullableTarget<IActionUsage>(_performedAction, SysmlLanguage.Instance.IPerformActionUsage_performedAction);
        return performedAction != null;
    }

    private IncludeUseCaseUsage SetPerformedAction(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IActionUsage>(value, SysmlLanguage.Instance.IPerformActionUsage_performedAction, _performedAction, SetPerformedActionRaw);
        return this;
    }

    private bool SetPerformedActionRaw(ReferenceTarget? value)
    {
        if (value == _performedAction)
            return false;
        _performedAction = value;
        return true;
    }

/// <remarks>Required Single Reference</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
    IPerformActionUsage IPerformActionUsage.SetPerformedAction(IActionUsage value) => SetPerformedAction(value);
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public IncludeUseCaseUsage SetPerformedAction(IActionUsage value)
    {
        return SetPerformedAction(ReferenceTarget.FromNodeOptional(value));
    }

    public IncludeUseCaseUsage(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.IncludeUseCaseUsage;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence.EqualsIdentity(feature))
        {
            result = EventOccurrence;
            return true;
        }

        if (SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded.EqualsIdentity(feature))
        {
            result = UseCaseIncluded;
            return true;
        }

        if (SysmlLanguage.Instance.IPerformActionUsage_performedAction.EqualsIdentity(feature))
        {
            result = PerformedAction;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence.EqualsIdentity(feature))
        {
            result = _eventOccurrence;
            return true;
        }

        if (SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded.EqualsIdentity(feature))
        {
            result = _useCaseIncluded;
            return true;
        }

        if (SysmlLanguage.Instance.IPerformActionUsage_performedAction.EqualsIdentity(feature))
        {
            result = _performedAction;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IOccurrenceUsage v)
            {
                SetEventOccurrence(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetEventOccurrence(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.UseCaseUsage v)
            {
                SetUseCaseIncluded(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetUseCaseIncluded(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IPerformActionUsage_performedAction.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IActionUsage v)
            {
                SetPerformedAction(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetPerformedAction(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence.EqualsIdentity(feature))
            return SetEventOccurrenceRaw(value);
        if (SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded.EqualsIdentity(feature))
            return SetUseCaseIncludedRaw(value);
        if (SysmlLanguage.Instance.IPerformActionUsage_performedAction.EqualsIdentity(feature))
            return SetPerformedActionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetEventOccurrence(out _))
            result.Add(SysmlLanguage.Instance.IEventOccurrenceUsage_eventOccurrence);
        if (TryGetUseCaseIncluded(out _))
            result.Add(SysmlLanguage.Instance.IncludeUseCaseUsage_useCaseIncluded);
        if (TryGetPerformedAction(out _))
            result.Add(SysmlLanguage.Instance.IPerformActionUsage_performedAction);
        return result;
    }
}

