// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage")]
public partial interface IOccurrenceUsage : IUsage
{
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-individualDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public OccurrenceDefinition? IndividualDefinition { get; set; }

    /// <remarks>Optional Single Reference</remarks>
    public IOccurrenceUsage SetIndividualDefinition(OccurrenceDefinition? value);
    /// <remarks>Required Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-isIndividual")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsIndividual { get; set; }

    /// <remarks>Required Property</remarks>
    public IOccurrenceUsage SetIsIndividual(bool value);
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-occurrenceDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IClass> OccurrenceDefinition { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IOccurrenceUsage AddOccurrenceDefinition(IEnumerable<IClass> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IOccurrenceUsage InsertOccurrenceDefinition(int index, IEnumerable<IClass> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IOccurrenceUsage RemoveOccurrenceDefinition(IEnumerable<IClass> nodes);
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IOccurrenceUsage-portionKind")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public PortionKind? PortionKind { get; set; }

    /// <remarks>Optional Property</remarks>
    public IOccurrenceUsage SetPortionKind(PortionKind? value);
}

