// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-LiteralRational")]
public partial class LiteralRational : LiteralExpression
{
    private decimal? _value = null;
    private bool SetValueRaw(decimal? value)
    {
        if (value == _value)
            return false;
        _value = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If Value has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-LiteralRational-value")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public decimal Value { get => _value ?? throw new UnsetFeatureException(SysmlLanguage.Instance.LiteralRational_value); set => SetValue(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetValue([NotNullWhenAttribute(true)] out decimal? value)
    {
        value = _value;
        return value != null;
    }

    /// <remarks>Required Property</remarks>
    public LiteralRational SetValue(decimal value)
    {
        SetRequiredValueTypeProperty<decimal>(value, SysmlLanguage.Instance.LiteralRational_value, _value, SetValueRaw);
        return this;
    }

    public LiteralRational(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.LiteralRational;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.LiteralRational_value.EqualsIdentity(feature))
        {
            result = Value;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.LiteralRational_value.EqualsIdentity(feature))
        {
            result = _value;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.LiteralRational_value.EqualsIdentity(feature))
        {
            if (value is decimal v)
            {
                SetValue(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.LiteralRational_value.EqualsIdentity(feature) && value is null or decimal)
            return SetValueRaw((decimal? )value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetValue(out _))
            result.Add(SysmlLanguage.Instance.LiteralRational_value);
        return result;
    }
}

