// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-OperatorExpression")]
public partial class OperatorExpression : InvocationExpression
{
    private string? _operator = null;
    private bool SetOperatorRaw(string? value)
    {
        if (value == _operator)
            return false;
        _operator = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If Operator has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-OperatorExpression-operator")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public string Operator { get => _operator ?? throw new UnsetFeatureException(SysmlLanguage.Instance.OperatorExpression_operator); set => SetOperator(value); }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public bool TryGetOperator([NotNullWhenAttribute(true)] out string? @operator)
    {
        @operator = _operator;
        return @operator != null;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public OperatorExpression SetOperator(string value)
    {
        SetRequiredReferenceTypeProperty<string>(value, SysmlLanguage.Instance.OperatorExpression_operator, _operator, SetOperatorRaw);
        return this;
    }

    public OperatorExpression(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.OperatorExpression;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.OperatorExpression_operator.EqualsIdentity(feature))
        {
            result = Operator;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.OperatorExpression_operator.EqualsIdentity(feature))
        {
            result = _operator;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.OperatorExpression_operator.EqualsIdentity(feature))
        {
            if (value is string v)
            {
                SetOperator(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.OperatorExpression_operator.EqualsIdentity(feature) && value is null or string)
            return SetOperatorRaw((string? )value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetOperator(out _))
            result.Add(SysmlLanguage.Instance.OperatorExpression_operator);
        return result;
    }
}

