// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-PortDefinition")]
public partial class PortDefinition : OccurrenceDefinition, IStructure
{
    private ReferenceTarget? _conjugatedPortDefinition_ = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-PortDefinition-conjugatedPortDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public ConjugatedPortDefinition? ConjugatedPortDefinition_ { get => ReferenceTargetNonNullTarget<ConjugatedPortDefinition>(_conjugatedPortDefinition_, SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition); set => SetConjugatedPortDefinition(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetConjugatedPortDefinition([NotNullWhenAttribute(true)] out ConjugatedPortDefinition? conjugatedPortDefinition_)
    {
        conjugatedPortDefinition_ = ReferenceTargetNullableTarget<ConjugatedPortDefinition>(_conjugatedPortDefinition_, SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition);
        return conjugatedPortDefinition_ != null;
    }

    private PortDefinition SetConjugatedPortDefinition(ReferenceTarget? value)
    {
        SetOptionalSingleReference<ConjugatedPortDefinition>(value, SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition, _conjugatedPortDefinition_, SetConjugatedPortDefinitionRaw);
        return this;
    }

    private bool SetConjugatedPortDefinitionRaw(ReferenceTarget? value)
    {
        if (value == _conjugatedPortDefinition_)
            return false;
        _conjugatedPortDefinition_ = value;
        return true;
    }

    /// <remarks>Optional Single Reference</remarks>
    public PortDefinition SetConjugatedPortDefinition(ConjugatedPortDefinition? value)
    {
        return SetConjugatedPortDefinition(ReferenceTarget.FromNodeOptional(value));
    }

    public PortDefinition(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.PortDefinition;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition.EqualsIdentity(feature))
        {
            result = ConjugatedPortDefinition_;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition.EqualsIdentity(feature))
        {
            result = _conjugatedPortDefinition_;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.ConjugatedPortDefinition)
            {
                SetConjugatedPortDefinition((LionWeb.Demo.SysMl2.Languages.SysMl2.ConjugatedPortDefinition? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetConjugatedPortDefinition(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition.EqualsIdentity(feature))
            return SetConjugatedPortDefinitionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetConjugatedPortDefinition(out _))
            result.Add(SysmlLanguage.Instance.PortDefinition_conjugatedPortDefinition);
        return result;
    }
}

