// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ReferenceSubsetting")]
public partial class ReferenceSubsetting : Subsetting
{
    private ReferenceTarget? _referencedFeature = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If ReferencedFeature has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ReferenceSubsetting-referencedFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature ReferencedFeature { get => ReferenceTargetNonNullTarget<IFeature>(_referencedFeature, SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature); set => SetReferencedFeature(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetReferencedFeature([NotNullWhenAttribute(true)] out IFeature? referencedFeature)
    {
        referencedFeature = ReferenceTargetNullableTarget<IFeature>(_referencedFeature, SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature);
        return referencedFeature != null;
    }

    private ReferenceSubsetting SetReferencedFeature(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IFeature>(value, SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature, _referencedFeature, SetReferencedFeatureRaw);
        return this;
    }

    private bool SetReferencedFeatureRaw(ReferenceTarget? value)
    {
        if (value == _referencedFeature)
            return false;
        _referencedFeature = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ReferenceSubsetting SetReferencedFeature(IFeature value)
    {
        return SetReferencedFeature(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _referencingFeature = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If ReferencingFeature has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ReferenceSubsetting-referencingFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature ReferencingFeature { get => ReferenceTargetNonNullTarget<IFeature>(_referencingFeature, SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature); set => SetReferencingFeature(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetReferencingFeature([NotNullWhenAttribute(true)] out IFeature? referencingFeature)
    {
        referencingFeature = ReferenceTargetNullableTarget<IFeature>(_referencingFeature, SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature);
        return referencingFeature != null;
    }

    private ReferenceSubsetting SetReferencingFeature(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IFeature>(value, SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature, _referencingFeature, SetReferencingFeatureRaw);
        return this;
    }

    private bool SetReferencingFeatureRaw(ReferenceTarget? value)
    {
        if (value == _referencingFeature)
            return false;
        _referencingFeature = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ReferenceSubsetting SetReferencingFeature(IFeature value)
    {
        return SetReferencingFeature(ReferenceTarget.FromNodeOptional(value));
    }

    public ReferenceSubsetting(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ReferenceSubsetting;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature.EqualsIdentity(feature))
        {
            result = ReferencedFeature;
            return true;
        }

        if (SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature.EqualsIdentity(feature))
        {
            result = ReferencingFeature;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature.EqualsIdentity(feature))
        {
            result = _referencedFeature;
            return true;
        }

        if (SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature.EqualsIdentity(feature))
        {
            result = _referencingFeature;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature v)
            {
                SetReferencedFeature(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetReferencedFeature(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature v)
            {
                SetReferencingFeature(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetReferencingFeature(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature.EqualsIdentity(feature))
            return SetReferencedFeatureRaw(value);
        if (SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature.EqualsIdentity(feature))
            return SetReferencingFeatureRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetReferencedFeature(out _))
            result.Add(SysmlLanguage.Instance.ReferenceSubsetting_referencedFeature);
        if (TryGetReferencingFeature(out _))
            result.Add(SysmlLanguage.Instance.ReferenceSubsetting_referencingFeature);
        return result;
    }
}

