// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-RenderingDefinition")]
public partial class RenderingDefinition : PartDefinition
{
    private readonly List<ReferenceTarget> _rendering = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-RenderingDefinition-rendering")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<RenderingUsage> Rendering { get => ReferenceTargetNonNullTargets<RenderingUsage>(_rendering, SysmlLanguage.Instance.RenderingDefinition_rendering); init => AddRendering(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetRendering([NotNullWhenAttribute(true)] out IReadOnlyList<RenderingUsage> rendering) => TryGetReference<RenderingUsage>(_rendering, out rendering);
    private bool SetRenderingRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _rendering);
    private bool AddRenderingRaw(ReferenceTarget target) => AddReferencesRaw(target, _rendering);
    private bool InsertRenderingRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _rendering);
    private bool RemoveRenderingRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _rendering);
    /// <remarks>Optional Multiple Reference</remarks>
    public RenderingDefinition AddRendering(IEnumerable<RenderingUsage> nodes)
    {
        AddOptionalMultipleReference<RenderingUsage>(nodes, SysmlLanguage.Instance.RenderingDefinition_rendering, _rendering, AddRenderingRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public RenderingDefinition InsertRendering(int index, IEnumerable<RenderingUsage> nodes)
    {
        InsertOptionalMultipleReference<RenderingUsage>(index, nodes, SysmlLanguage.Instance.RenderingDefinition_rendering, _rendering, InsertRenderingRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public RenderingDefinition RemoveRendering(IEnumerable<RenderingUsage> nodes)
    {
        RemoveOptionalMultipleReference<RenderingUsage>(nodes, SysmlLanguage.Instance.RenderingDefinition_rendering, _rendering, RemoveRenderingRaw);
        return this;
    }

    public RenderingDefinition(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.RenderingDefinition;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(feature))
        {
            result = Rendering;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(feature))
        {
            result = _rendering;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<RenderingUsage>(value, SysmlLanguage.Instance.RenderingDefinition_rendering, _rendering, SetRenderingRaw);
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetRendering(out _))
            result.Add(SysmlLanguage.Instance.RenderingDefinition_rendering);
        return result;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(feature))
            return AddRenderingRaw(value);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(feature))
            return InsertRenderingRaw(index, value);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(feature))
            return RemoveRenderingRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(link))
        {
            AddRendering(SysmlLanguage.Instance.RenderingDefinition_rendering.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(link))
        {
            InsertRendering(index, SysmlLanguage.Instance.RenderingDefinition_rendering.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.RenderingDefinition_rendering.EqualsIdentity(link))
        {
            RemoveRendering(SysmlLanguage.Instance.RenderingDefinition_rendering.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage>(value));
            return true;
        }

        return false;
    }
}

