// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-RequirementConstraintMembership")]
public partial class RequirementConstraintMembership : FeatureMembership
{
    private RequirementConstraintKind? _kind = null;
    private bool SetKindRaw(RequirementConstraintKind? value)
    {
        if (value == _kind)
            return false;
        _kind = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If Kind has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-RequirementConstraintMembership-kind")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public RequirementConstraintKind Kind { get => _kind ?? throw new UnsetFeatureException(SysmlLanguage.Instance.RequirementConstraintMembership_kind); set => SetKind(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetKind([NotNullWhenAttribute(true)] out RequirementConstraintKind? kind)
    {
        kind = _kind;
        return kind != null;
    }

    /// <remarks>Required Property</remarks>
    public RequirementConstraintMembership SetKind(RequirementConstraintKind value)
    {
        SetRequiredValueTypeProperty<RequirementConstraintKind>(value, SysmlLanguage.Instance.RequirementConstraintMembership_kind, _kind, SetKindRaw);
        return this;
    }

    private ReferenceTarget? _ownedConstraint = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If OwnedConstraint has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-RequirementConstraintMembership-ownedConstraint")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IConstraintUsage OwnedConstraint { get => ReferenceTargetNonNullTarget<IConstraintUsage>(_ownedConstraint, SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint); set => SetOwnedConstraint(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetOwnedConstraint([NotNullWhenAttribute(true)] out IConstraintUsage? ownedConstraint)
    {
        ownedConstraint = ReferenceTargetNullableTarget<IConstraintUsage>(_ownedConstraint, SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint);
        return ownedConstraint != null;
    }

    private RequirementConstraintMembership SetOwnedConstraint(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IConstraintUsage>(value, SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint, _ownedConstraint, SetOwnedConstraintRaw);
        return this;
    }

    private bool SetOwnedConstraintRaw(ReferenceTarget? value)
    {
        if (value == _ownedConstraint)
            return false;
        _ownedConstraint = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public RequirementConstraintMembership SetOwnedConstraint(IConstraintUsage value)
    {
        return SetOwnedConstraint(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _referencedConstraint = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If ReferencedConstraint has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-RequirementConstraintMembership-referencedConstraint")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IConstraintUsage ReferencedConstraint { get => ReferenceTargetNonNullTarget<IConstraintUsage>(_referencedConstraint, SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint); set => SetReferencedConstraint(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetReferencedConstraint([NotNullWhenAttribute(true)] out IConstraintUsage? referencedConstraint)
    {
        referencedConstraint = ReferenceTargetNullableTarget<IConstraintUsage>(_referencedConstraint, SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint);
        return referencedConstraint != null;
    }

    private RequirementConstraintMembership SetReferencedConstraint(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IConstraintUsage>(value, SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint, _referencedConstraint, SetReferencedConstraintRaw);
        return this;
    }

    private bool SetReferencedConstraintRaw(ReferenceTarget? value)
    {
        if (value == _referencedConstraint)
            return false;
        _referencedConstraint = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public RequirementConstraintMembership SetReferencedConstraint(IConstraintUsage value)
    {
        return SetReferencedConstraint(ReferenceTarget.FromNodeOptional(value));
    }

    public RequirementConstraintMembership(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.RequirementConstraintMembership;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.RequirementConstraintMembership_kind.EqualsIdentity(feature))
        {
            result = Kind;
            return true;
        }

        if (SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint.EqualsIdentity(feature))
        {
            result = OwnedConstraint;
            return true;
        }

        if (SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint.EqualsIdentity(feature))
        {
            result = ReferencedConstraint;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.RequirementConstraintMembership_kind.EqualsIdentity(feature))
        {
            result = _kind;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint.EqualsIdentity(feature))
        {
            result = _ownedConstraint;
            return true;
        }

        if (SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint.EqualsIdentity(feature))
        {
            result = _referencedConstraint;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.RequirementConstraintMembership_kind.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementConstraintKind v)
            {
                SetKind(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IConstraintUsage v)
            {
                SetOwnedConstraint(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwnedConstraint(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IConstraintUsage v)
            {
                SetReferencedConstraint(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetReferencedConstraint(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.RequirementConstraintMembership_kind.EqualsIdentity(feature) && value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementConstraintKind)
            return SetKindRaw((LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementConstraintKind? )value);
        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint.EqualsIdentity(feature))
            return SetOwnedConstraintRaw(value);
        if (SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint.EqualsIdentity(feature))
            return SetReferencedConstraintRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetKind(out _))
            result.Add(SysmlLanguage.Instance.RequirementConstraintMembership_kind);
        if (TryGetOwnedConstraint(out _))
            result.Add(SysmlLanguage.Instance.RequirementConstraintMembership_ownedConstraint);
        if (TryGetReferencedConstraint(out _))
            result.Add(SysmlLanguage.Instance.RequirementConstraintMembership_referencedConstraint);
        return result;
    }
}

