// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ResultExpressionMembership")]
public partial class ResultExpressionMembership : FeatureMembership
{
    private ReferenceTarget? _ownedResultExpression = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If OwnedResultExpression has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ResultExpressionMembership-ownedResultExpression")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IExpression OwnedResultExpression { get => ReferenceTargetNonNullTarget<IExpression>(_ownedResultExpression, SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression); set => SetOwnedResultExpression(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetOwnedResultExpression([NotNullWhenAttribute(true)] out IExpression? ownedResultExpression)
    {
        ownedResultExpression = ReferenceTargetNullableTarget<IExpression>(_ownedResultExpression, SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression);
        return ownedResultExpression != null;
    }

    private ResultExpressionMembership SetOwnedResultExpression(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IExpression>(value, SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression, _ownedResultExpression, SetOwnedResultExpressionRaw);
        return this;
    }

    private bool SetOwnedResultExpressionRaw(ReferenceTarget? value)
    {
        if (value == _ownedResultExpression)
            return false;
        _ownedResultExpression = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ResultExpressionMembership SetOwnedResultExpression(IExpression value)
    {
        return SetOwnedResultExpression(ReferenceTarget.FromNodeOptional(value));
    }

    public ResultExpressionMembership(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ResultExpressionMembership;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression.EqualsIdentity(feature))
        {
            result = OwnedResultExpression;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression.EqualsIdentity(feature))
        {
            result = _ownedResultExpression;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IExpression v)
            {
                SetOwnedResultExpression(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwnedResultExpression(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression.EqualsIdentity(feature))
            return SetOwnedResultExpressionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetOwnedResultExpression(out _))
            result.Add(SysmlLanguage.Instance.ResultExpressionMembership_ownedResultExpression);
        return result;
    }
}

