// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-SatisfyRequirementUsage")]
public partial class SatisfyRequirementUsage : RequirementUsage, IAssertConstraintUsage
{
    private ReferenceTarget? _assertedConstraint = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If AssertedConstraint has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IAssertConstraintUsage-assertedConstraint")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IConstraintUsage AssertedConstraint { get => ReferenceTargetNonNullTarget<IConstraintUsage>(_assertedConstraint, SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint); set => SetAssertedConstraint(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetAssertedConstraint([NotNullWhenAttribute(true)] out IConstraintUsage? assertedConstraint)
    {
        assertedConstraint = ReferenceTargetNullableTarget<IConstraintUsage>(_assertedConstraint, SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint);
        return assertedConstraint != null;
    }

    private SatisfyRequirementUsage SetAssertedConstraint(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IConstraintUsage>(value, SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint, _assertedConstraint, SetAssertedConstraintRaw);
        return this;
    }

    private bool SetAssertedConstraintRaw(ReferenceTarget? value)
    {
        if (value == _assertedConstraint)
            return false;
        _assertedConstraint = value;
        return true;
    }

/// <remarks>Required Single Reference</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
    IAssertConstraintUsage IAssertConstraintUsage.SetAssertedConstraint(IConstraintUsage value) => SetAssertedConstraint(value);
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public SatisfyRequirementUsage SetAssertedConstraint(IConstraintUsage value)
    {
        return SetAssertedConstraint(ReferenceTarget.FromNodeOptional(value));
    }

    private bool? _isNegated = null;
    private bool SetIsNegatedRaw(bool? value)
    {
        if (value is null && _isNegated is null || value is not null && value.Equals(_isNegated))
            return false;
        _isNegated = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsNegated has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-IInvariant-isNegated")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsNegated { get => _isNegated ?? throw new UnsetFeatureException(SysmlLanguage.Instance.IInvariant_isNegated); set => SetIsNegated(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsNegated([NotNullWhenAttribute(true)] out bool? isNegated)
    {
        isNegated = _isNegated;
        return isNegated != null;
    }

/// <remarks>Required Property</remarks>
    IInvariant IInvariant.SetIsNegated(bool value) => SetIsNegated(value);
    /// <remarks>Required Property</remarks>
    public SatisfyRequirementUsage SetIsNegated(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, SysmlLanguage.Instance.IInvariant_isNegated, _isNegated, SetIsNegatedRaw);
        return this;
    }

    private ReferenceTarget? _satisfiedRequirement = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If SatisfiedRequirement has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-SatisfyRequirementUsage-satisfiedRequirement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public RequirementUsage SatisfiedRequirement { get => ReferenceTargetNonNullTarget<RequirementUsage>(_satisfiedRequirement, SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement); set => SetSatisfiedRequirement(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetSatisfiedRequirement([NotNullWhenAttribute(true)] out RequirementUsage? satisfiedRequirement)
    {
        satisfiedRequirement = ReferenceTargetNullableTarget<RequirementUsage>(_satisfiedRequirement, SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement);
        return satisfiedRequirement != null;
    }

    private SatisfyRequirementUsage SetSatisfiedRequirement(ReferenceTarget? value)
    {
        SetRequiredSingleReference<RequirementUsage>(value, SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement, _satisfiedRequirement, SetSatisfiedRequirementRaw);
        return this;
    }

    private bool SetSatisfiedRequirementRaw(ReferenceTarget? value)
    {
        if (value == _satisfiedRequirement)
            return false;
        _satisfiedRequirement = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public SatisfyRequirementUsage SetSatisfiedRequirement(RequirementUsage value)
    {
        return SetSatisfiedRequirement(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _satisfyingFeature = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If SatisfyingFeature has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-SatisfyRequirementUsage-satisfyingFeature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature SatisfyingFeature { get => ReferenceTargetNonNullTarget<IFeature>(_satisfyingFeature, SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature); set => SetSatisfyingFeature(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetSatisfyingFeature([NotNullWhenAttribute(true)] out IFeature? satisfyingFeature)
    {
        satisfyingFeature = ReferenceTargetNullableTarget<IFeature>(_satisfyingFeature, SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature);
        return satisfyingFeature != null;
    }

    private SatisfyRequirementUsage SetSatisfyingFeature(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IFeature>(value, SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature, _satisfyingFeature, SetSatisfyingFeatureRaw);
        return this;
    }

    private bool SetSatisfyingFeatureRaw(ReferenceTarget? value)
    {
        if (value == _satisfyingFeature)
            return false;
        _satisfyingFeature = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public SatisfyRequirementUsage SetSatisfyingFeature(IFeature value)
    {
        return SetSatisfyingFeature(ReferenceTarget.FromNodeOptional(value));
    }

    public SatisfyRequirementUsage(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.SatisfyRequirementUsage;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint.EqualsIdentity(feature))
        {
            result = AssertedConstraint;
            return true;
        }

        if (SysmlLanguage.Instance.IInvariant_isNegated.EqualsIdentity(feature))
        {
            result = IsNegated;
            return true;
        }

        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement.EqualsIdentity(feature))
        {
            result = SatisfiedRequirement;
            return true;
        }

        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature.EqualsIdentity(feature))
        {
            result = SatisfyingFeature;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IInvariant_isNegated.EqualsIdentity(feature))
        {
            result = _isNegated;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint.EqualsIdentity(feature))
        {
            result = _assertedConstraint;
            return true;
        }

        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement.EqualsIdentity(feature))
        {
            result = _satisfiedRequirement;
            return true;
        }

        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature.EqualsIdentity(feature))
        {
            result = _satisfyingFeature;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IConstraintUsage v)
            {
                SetAssertedConstraint(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetAssertedConstraint(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.IInvariant_isNegated.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsNegated(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementUsage v)
            {
                SetSatisfiedRequirement(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetSatisfiedRequirement(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IFeature v)
            {
                SetSatisfyingFeature(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetSatisfyingFeature(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.IInvariant_isNegated.EqualsIdentity(feature) && value is null or bool)
            return SetIsNegatedRaw((bool? )value);
        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint.EqualsIdentity(feature))
            return SetAssertedConstraintRaw(value);
        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement.EqualsIdentity(feature))
            return SetSatisfiedRequirementRaw(value);
        if (SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature.EqualsIdentity(feature))
            return SetSatisfyingFeatureRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetAssertedConstraint(out _))
            result.Add(SysmlLanguage.Instance.IAssertConstraintUsage_assertedConstraint);
        if (TryGetIsNegated(out _))
            result.Add(SysmlLanguage.Instance.IInvariant_isNegated);
        if (TryGetSatisfiedRequirement(out _))
            result.Add(SysmlLanguage.Instance.SatisfyRequirementUsage_satisfiedRequirement);
        if (TryGetSatisfyingFeature(out _))
            result.Add(SysmlLanguage.Instance.SatisfyRequirementUsage_satisfyingFeature);
        return result;
    }
}

