// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-StakeholderMembership")]
public partial class StakeholderMembership : ParameterMembership
{
    private ReferenceTarget? _ownedStakeholderParameter = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If OwnedStakeholderParameter has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-StakeholderMembership-ownedStakeholderParameter")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IPartUsage OwnedStakeholderParameter { get => ReferenceTargetNonNullTarget<IPartUsage>(_ownedStakeholderParameter, SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter); set => SetOwnedStakeholderParameter(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetOwnedStakeholderParameter([NotNullWhenAttribute(true)] out IPartUsage? ownedStakeholderParameter)
    {
        ownedStakeholderParameter = ReferenceTargetNullableTarget<IPartUsage>(_ownedStakeholderParameter, SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter);
        return ownedStakeholderParameter != null;
    }

    private StakeholderMembership SetOwnedStakeholderParameter(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IPartUsage>(value, SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter, _ownedStakeholderParameter, SetOwnedStakeholderParameterRaw);
        return this;
    }

    private bool SetOwnedStakeholderParameterRaw(ReferenceTarget? value)
    {
        if (value == _ownedStakeholderParameter)
            return false;
        _ownedStakeholderParameter = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public StakeholderMembership SetOwnedStakeholderParameter(IPartUsage value)
    {
        return SetOwnedStakeholderParameter(ReferenceTarget.FromNodeOptional(value));
    }

    public StakeholderMembership(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.StakeholderMembership;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter.EqualsIdentity(feature))
        {
            result = OwnedStakeholderParameter;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter.EqualsIdentity(feature))
        {
            result = _ownedStakeholderParameter;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.IPartUsage v)
            {
                SetOwnedStakeholderParameter(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwnedStakeholderParameter(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter.EqualsIdentity(feature))
            return SetOwnedStakeholderParameterRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetOwnedStakeholderParameter(out _))
            result.Add(SysmlLanguage.Instance.StakeholderMembership_ownedStakeholderParameter);
        return result;
    }
}

