// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-UseCaseUsage")]
public partial class UseCaseUsage : CaseUsage
{
    private readonly List<ReferenceTarget> _includedUseCase = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-UseCaseUsage-includedUseCase")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<UseCaseUsage> IncludedUseCase { get => ReferenceTargetNonNullTargets<UseCaseUsage>(_includedUseCase, SysmlLanguage.Instance.UseCaseUsage_includedUseCase); init => AddIncludedUseCase(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetIncludedUseCase([NotNullWhenAttribute(true)] out IReadOnlyList<UseCaseUsage> includedUseCase) => TryGetReference<UseCaseUsage>(_includedUseCase, out includedUseCase);
    private bool SetIncludedUseCaseRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _includedUseCase);
    private bool AddIncludedUseCaseRaw(ReferenceTarget target) => AddReferencesRaw(target, _includedUseCase);
    private bool InsertIncludedUseCaseRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _includedUseCase);
    private bool RemoveIncludedUseCaseRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _includedUseCase);
    /// <remarks>Optional Multiple Reference</remarks>
    public UseCaseUsage AddIncludedUseCase(IEnumerable<UseCaseUsage> nodes)
    {
        AddOptionalMultipleReference<UseCaseUsage>(nodes, SysmlLanguage.Instance.UseCaseUsage_includedUseCase, _includedUseCase, AddIncludedUseCaseRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public UseCaseUsage InsertIncludedUseCase(int index, IEnumerable<UseCaseUsage> nodes)
    {
        InsertOptionalMultipleReference<UseCaseUsage>(index, nodes, SysmlLanguage.Instance.UseCaseUsage_includedUseCase, _includedUseCase, InsertIncludedUseCaseRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public UseCaseUsage RemoveIncludedUseCase(IEnumerable<UseCaseUsage> nodes)
    {
        RemoveOptionalMultipleReference<UseCaseUsage>(nodes, SysmlLanguage.Instance.UseCaseUsage_includedUseCase, _includedUseCase, RemoveIncludedUseCaseRaw);
        return this;
    }

    private ReferenceTarget? _useCaseDefinition = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-UseCaseUsage-useCaseDefinition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public UseCaseDefinition? UseCaseDefinition { get => ReferenceTargetNonNullTarget<UseCaseDefinition>(_useCaseDefinition, SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition); set => SetUseCaseDefinition(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetUseCaseDefinition([NotNullWhenAttribute(true)] out UseCaseDefinition? useCaseDefinition)
    {
        useCaseDefinition = ReferenceTargetNullableTarget<UseCaseDefinition>(_useCaseDefinition, SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition);
        return useCaseDefinition != null;
    }

    private UseCaseUsage SetUseCaseDefinition(ReferenceTarget? value)
    {
        SetOptionalSingleReference<UseCaseDefinition>(value, SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition, _useCaseDefinition, SetUseCaseDefinitionRaw);
        return this;
    }

    private bool SetUseCaseDefinitionRaw(ReferenceTarget? value)
    {
        if (value == _useCaseDefinition)
            return false;
        _useCaseDefinition = value;
        return true;
    }

    /// <remarks>Optional Single Reference</remarks>
    public UseCaseUsage SetUseCaseDefinition(UseCaseDefinition? value)
    {
        return SetUseCaseDefinition(ReferenceTarget.FromNodeOptional(value));
    }

    public UseCaseUsage(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.UseCaseUsage;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(feature))
        {
            result = IncludedUseCase;
            return true;
        }

        if (SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition.EqualsIdentity(feature))
        {
            result = UseCaseDefinition;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition.EqualsIdentity(feature))
        {
            result = _useCaseDefinition;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(feature))
        {
            result = _includedUseCase;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<UseCaseUsage>(value, SysmlLanguage.Instance.UseCaseUsage_includedUseCase, _includedUseCase, SetIncludedUseCaseRaw);
            return true;
        }

        if (SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.UseCaseDefinition)
            {
                SetUseCaseDefinition((LionWeb.Demo.SysMl2.Languages.SysMl2.UseCaseDefinition? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetUseCaseDefinition(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition.EqualsIdentity(feature))
            return SetUseCaseDefinitionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetIncludedUseCase(out _))
            result.Add(SysmlLanguage.Instance.UseCaseUsage_includedUseCase);
        if (TryGetUseCaseDefinition(out _))
            result.Add(SysmlLanguage.Instance.UseCaseUsage_useCaseDefinition);
        return result;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(feature))
            return AddIncludedUseCaseRaw(value);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(feature))
            return InsertIncludedUseCaseRaw(index, value);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(feature))
            return RemoveIncludedUseCaseRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(link))
        {
            AddIncludedUseCase(SysmlLanguage.Instance.UseCaseUsage_includedUseCase.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.UseCaseUsage>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(link))
        {
            InsertIncludedUseCase(index, SysmlLanguage.Instance.UseCaseUsage_includedUseCase.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.UseCaseUsage>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.UseCaseUsage_includedUseCase.EqualsIdentity(link))
        {
            RemoveIncludedUseCase(SysmlLanguage.Instance.UseCaseUsage_includedUseCase.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.UseCaseUsage>(value));
            return true;
        }

        return false;
    }
}

