// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-VerificationCaseDefinition")]
public partial class VerificationCaseDefinition : CaseDefinition
{
    private readonly List<ReferenceTarget> _verifiedRequirement = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-VerificationCaseDefinition-verifiedRequirement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<RequirementUsage> VerifiedRequirement { get => ReferenceTargetNonNullTargets<RequirementUsage>(_verifiedRequirement, SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement); init => AddVerifiedRequirement(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetVerifiedRequirement([NotNullWhenAttribute(true)] out IReadOnlyList<RequirementUsage> verifiedRequirement) => TryGetReference<RequirementUsage>(_verifiedRequirement, out verifiedRequirement);
    private bool SetVerifiedRequirementRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _verifiedRequirement);
    private bool AddVerifiedRequirementRaw(ReferenceTarget target) => AddReferencesRaw(target, _verifiedRequirement);
    private bool InsertVerifiedRequirementRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _verifiedRequirement);
    private bool RemoveVerifiedRequirementRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _verifiedRequirement);
    /// <remarks>Optional Multiple Reference</remarks>
    public VerificationCaseDefinition AddVerifiedRequirement(IEnumerable<RequirementUsage> nodes)
    {
        AddOptionalMultipleReference<RequirementUsage>(nodes, SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement, _verifiedRequirement, AddVerifiedRequirementRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public VerificationCaseDefinition InsertVerifiedRequirement(int index, IEnumerable<RequirementUsage> nodes)
    {
        InsertOptionalMultipleReference<RequirementUsage>(index, nodes, SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement, _verifiedRequirement, InsertVerifiedRequirementRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public VerificationCaseDefinition RemoveVerifiedRequirement(IEnumerable<RequirementUsage> nodes)
    {
        RemoveOptionalMultipleReference<RequirementUsage>(nodes, SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement, _verifiedRequirement, RemoveVerifiedRequirementRaw);
        return this;
    }

    public VerificationCaseDefinition(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.VerificationCaseDefinition;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(feature))
        {
            result = VerifiedRequirement;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(feature))
        {
            result = _verifiedRequirement;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<RequirementUsage>(value, SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement, _verifiedRequirement, SetVerifiedRequirementRaw);
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetVerifiedRequirement(out _))
            result.Add(SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement);
        return result;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(feature))
            return AddVerifiedRequirementRaw(value);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(feature))
            return InsertVerifiedRequirementRaw(index, value);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(feature))
            return RemoveVerifiedRequirementRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(link))
        {
            AddVerifiedRequirement(SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementUsage>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(link))
        {
            InsertVerifiedRequirement(index, SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementUsage>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.EqualsIdentity(link))
        {
            RemoveVerifiedRequirement(SysmlLanguage.Instance.VerificationCaseDefinition_verifiedRequirement.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.RequirementUsage>(value));
            return true;
        }

        return false;
    }
}

