// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewDefinition")]
public partial class ViewDefinition : PartDefinition
{
    private readonly List<ReferenceTarget> _satisfiedViewpoint = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewDefinition-satisfiedViewpoint")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<ViewpointUsage> SatisfiedViewpoint { get => ReferenceTargetNonNullTargets<ViewpointUsage>(_satisfiedViewpoint, SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint); init => AddSatisfiedViewpoint(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetSatisfiedViewpoint([NotNullWhenAttribute(true)] out IReadOnlyList<ViewpointUsage> satisfiedViewpoint) => TryGetReference<ViewpointUsage>(_satisfiedViewpoint, out satisfiedViewpoint);
    private bool SetSatisfiedViewpointRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _satisfiedViewpoint);
    private bool AddSatisfiedViewpointRaw(ReferenceTarget target) => AddReferencesRaw(target, _satisfiedViewpoint);
    private bool InsertSatisfiedViewpointRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _satisfiedViewpoint);
    private bool RemoveSatisfiedViewpointRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _satisfiedViewpoint);
    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition AddSatisfiedViewpoint(IEnumerable<ViewpointUsage> nodes)
    {
        AddOptionalMultipleReference<ViewpointUsage>(nodes, SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint, _satisfiedViewpoint, AddSatisfiedViewpointRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition InsertSatisfiedViewpoint(int index, IEnumerable<ViewpointUsage> nodes)
    {
        InsertOptionalMultipleReference<ViewpointUsage>(index, nodes, SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint, _satisfiedViewpoint, InsertSatisfiedViewpointRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition RemoveSatisfiedViewpoint(IEnumerable<ViewpointUsage> nodes)
    {
        RemoveOptionalMultipleReference<ViewpointUsage>(nodes, SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint, _satisfiedViewpoint, RemoveSatisfiedViewpointRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _view = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewDefinition-view")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<ViewUsage> View { get => ReferenceTargetNonNullTargets<ViewUsage>(_view, SysmlLanguage.Instance.ViewDefinition_view); init => AddView(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetView([NotNullWhenAttribute(true)] out IReadOnlyList<ViewUsage> view) => TryGetReference<ViewUsage>(_view, out view);
    private bool SetViewRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _view);
    private bool AddViewRaw(ReferenceTarget target) => AddReferencesRaw(target, _view);
    private bool InsertViewRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _view);
    private bool RemoveViewRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _view);
    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition AddView(IEnumerable<ViewUsage> nodes)
    {
        AddOptionalMultipleReference<ViewUsage>(nodes, SysmlLanguage.Instance.ViewDefinition_view, _view, AddViewRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition InsertView(int index, IEnumerable<ViewUsage> nodes)
    {
        InsertOptionalMultipleReference<ViewUsage>(index, nodes, SysmlLanguage.Instance.ViewDefinition_view, _view, InsertViewRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition RemoveView(IEnumerable<ViewUsage> nodes)
    {
        RemoveOptionalMultipleReference<ViewUsage>(nodes, SysmlLanguage.Instance.ViewDefinition_view, _view, RemoveViewRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _viewCondition = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewDefinition-viewCondition")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IExpression> ViewCondition { get => ReferenceTargetNonNullTargets<IExpression>(_viewCondition, SysmlLanguage.Instance.ViewDefinition_viewCondition); init => AddViewCondition(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetViewCondition([NotNullWhenAttribute(true)] out IReadOnlyList<IExpression> viewCondition) => TryGetReference<IExpression>(_viewCondition, out viewCondition);
    private bool SetViewConditionRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _viewCondition);
    private bool AddViewConditionRaw(ReferenceTarget target) => AddReferencesRaw(target, _viewCondition);
    private bool InsertViewConditionRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _viewCondition);
    private bool RemoveViewConditionRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _viewCondition);
    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition AddViewCondition(IEnumerable<IExpression> nodes)
    {
        AddOptionalMultipleReference<IExpression>(nodes, SysmlLanguage.Instance.ViewDefinition_viewCondition, _viewCondition, AddViewConditionRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition InsertViewCondition(int index, IEnumerable<IExpression> nodes)
    {
        InsertOptionalMultipleReference<IExpression>(index, nodes, SysmlLanguage.Instance.ViewDefinition_viewCondition, _viewCondition, InsertViewConditionRaw);
        return this;
    }

    /// <remarks>Optional Multiple Reference</remarks>
    public ViewDefinition RemoveViewCondition(IEnumerable<IExpression> nodes)
    {
        RemoveOptionalMultipleReference<IExpression>(nodes, SysmlLanguage.Instance.ViewDefinition_viewCondition, _viewCondition, RemoveViewConditionRaw);
        return this;
    }

    private ReferenceTarget? _viewRendering = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewDefinition-viewRendering")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public RenderingUsage? ViewRendering { get => ReferenceTargetNonNullTarget<RenderingUsage>(_viewRendering, SysmlLanguage.Instance.ViewDefinition_viewRendering); set => SetViewRendering(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetViewRendering([NotNullWhenAttribute(true)] out RenderingUsage? viewRendering)
    {
        viewRendering = ReferenceTargetNullableTarget<RenderingUsage>(_viewRendering, SysmlLanguage.Instance.ViewDefinition_viewRendering);
        return viewRendering != null;
    }

    private ViewDefinition SetViewRendering(ReferenceTarget? value)
    {
        SetOptionalSingleReference<RenderingUsage>(value, SysmlLanguage.Instance.ViewDefinition_viewRendering, _viewRendering, SetViewRenderingRaw);
        return this;
    }

    private bool SetViewRenderingRaw(ReferenceTarget? value)
    {
        if (value == _viewRendering)
            return false;
        _viewRendering = value;
        return true;
    }

    /// <remarks>Optional Single Reference</remarks>
    public ViewDefinition SetViewRendering(RenderingUsage? value)
    {
        return SetViewRendering(ReferenceTarget.FromNodeOptional(value));
    }

    public ViewDefinition(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ViewDefinition;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(feature))
        {
            result = SatisfiedViewpoint;
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(feature))
        {
            result = View;
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(feature))
        {
            result = ViewCondition;
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewRendering.EqualsIdentity(feature))
        {
            result = ViewRendering;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_viewRendering.EqualsIdentity(feature))
        {
            result = _viewRendering;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(feature))
        {
            result = _satisfiedViewpoint;
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(feature))
        {
            result = _view;
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(feature))
        {
            result = _viewCondition;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<ViewpointUsage>(value, SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint, _satisfiedViewpoint, SetSatisfiedViewpointRaw);
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<ViewUsage>(value, SysmlLanguage.Instance.ViewDefinition_view, _view, SetViewRaw);
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IExpression>(value, SysmlLanguage.Instance.ViewDefinition_viewCondition, _viewCondition, SetViewConditionRaw);
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewRendering.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage)
            {
                SetViewRendering((LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetViewRendering(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_viewRendering.EqualsIdentity(feature))
            return SetViewRenderingRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetSatisfiedViewpoint(out _))
            result.Add(SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint);
        if (TryGetView(out _))
            result.Add(SysmlLanguage.Instance.ViewDefinition_view);
        if (TryGetViewCondition(out _))
            result.Add(SysmlLanguage.Instance.ViewDefinition_viewCondition);
        if (TryGetViewRendering(out _))
            result.Add(SysmlLanguage.Instance.ViewDefinition_viewRendering);
        return result;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(feature))
            return AddSatisfiedViewpointRaw(value);
        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(feature))
            return AddViewRaw(value);
        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(feature))
            return AddViewConditionRaw(value);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(feature))
            return InsertSatisfiedViewpointRaw(index, value);
        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(feature))
            return InsertViewRaw(index, value);
        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(feature))
            return InsertViewConditionRaw(index, value);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(feature))
            return RemoveSatisfiedViewpointRaw(value);
        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(feature))
            return RemoveViewRaw(value);
        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(feature))
            return RemoveViewConditionRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(link))
        {
            AddSatisfiedViewpoint(SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ViewpointUsage>(value));
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(link))
        {
            AddView(SysmlLanguage.Instance.ViewDefinition_view.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ViewUsage>(value));
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(link))
        {
            AddViewCondition(SysmlLanguage.Instance.ViewDefinition_viewCondition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IExpression>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(link))
        {
            InsertSatisfiedViewpoint(index, SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ViewpointUsage>(value));
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(link))
        {
            InsertView(index, SysmlLanguage.Instance.ViewDefinition_view.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ViewUsage>(value));
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(link))
        {
            InsertViewCondition(index, SysmlLanguage.Instance.ViewDefinition_viewCondition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IExpression>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.EqualsIdentity(link))
        {
            RemoveSatisfiedViewpoint(SysmlLanguage.Instance.ViewDefinition_satisfiedViewpoint.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ViewpointUsage>(value));
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_view.EqualsIdentity(link))
        {
            RemoveView(SysmlLanguage.Instance.ViewDefinition_view.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.ViewUsage>(value));
            return true;
        }

        if (SysmlLanguage.Instance.ViewDefinition_viewCondition.EqualsIdentity(link))
        {
            RemoveViewCondition(SysmlLanguage.Instance.ViewDefinition_viewCondition.AsNodes<LionWeb.Demo.SysMl2.Languages.SysMl2.IExpression>(value));
            return true;
        }

        return false;
    }
}

