// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.SysMl2;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewRenderingMembership")]
public partial class ViewRenderingMembership : FeatureMembership
{
    private ReferenceTarget? _ownedRendering = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If OwnedRendering has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewRenderingMembership-ownedRendering")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public RenderingUsage OwnedRendering { get => ReferenceTargetNonNullTarget<RenderingUsage>(_ownedRendering, SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering); set => SetOwnedRendering(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetOwnedRendering([NotNullWhenAttribute(true)] out RenderingUsage? ownedRendering)
    {
        ownedRendering = ReferenceTargetNullableTarget<RenderingUsage>(_ownedRendering, SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering);
        return ownedRendering != null;
    }

    private ViewRenderingMembership SetOwnedRendering(ReferenceTarget? value)
    {
        SetRequiredSingleReference<RenderingUsage>(value, SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering, _ownedRendering, SetOwnedRenderingRaw);
        return this;
    }

    private bool SetOwnedRenderingRaw(ReferenceTarget? value)
    {
        if (value == _ownedRendering)
            return false;
        _ownedRendering = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ViewRenderingMembership SetOwnedRendering(RenderingUsage value)
    {
        return SetOwnedRendering(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _referencedRendering = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If ReferencedRendering has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(SysmlLanguage), Key = "sysml-ViewRenderingMembership-referencedRendering")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public RenderingUsage ReferencedRendering { get => ReferenceTargetNonNullTarget<RenderingUsage>(_referencedRendering, SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering) ?? throw new UnsetFeatureException(SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering); set => SetReferencedRendering(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetReferencedRendering([NotNullWhenAttribute(true)] out RenderingUsage? referencedRendering)
    {
        referencedRendering = ReferenceTargetNullableTarget<RenderingUsage>(_referencedRendering, SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering);
        return referencedRendering != null;
    }

    private ViewRenderingMembership SetReferencedRendering(ReferenceTarget? value)
    {
        SetRequiredSingleReference<RenderingUsage>(value, SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering, _referencedRendering, SetReferencedRenderingRaw);
        return this;
    }

    private bool SetReferencedRenderingRaw(ReferenceTarget? value)
    {
        if (value == _referencedRendering)
            return false;
        _referencedRendering = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public ViewRenderingMembership SetReferencedRendering(RenderingUsage value)
    {
        return SetReferencedRendering(ReferenceTarget.FromNodeOptional(value));
    }

    public ViewRenderingMembership(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => SysmlLanguage.Instance.ViewRenderingMembership;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering.EqualsIdentity(feature))
        {
            result = OwnedRendering;
            return true;
        }

        if (SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering.EqualsIdentity(feature))
        {
            result = ReferencedRendering;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering.EqualsIdentity(feature))
        {
            result = _ownedRendering;
            return true;
        }

        if (SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering.EqualsIdentity(feature))
        {
            result = _referencedRendering;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage v)
            {
                SetOwnedRendering(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwnedRendering(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.SysMl2.RenderingUsage v)
            {
                SetReferencedRendering(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetReferencedRendering(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering.EqualsIdentity(feature))
            return SetOwnedRenderingRaw(value);
        if (SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering.EqualsIdentity(feature))
            return SetReferencedRenderingRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetOwnedRendering(out _))
            result.Add(SysmlLanguage.Instance.ViewRenderingMembership_ownedRendering);
        if (TryGetReferencedRendering(out _))
            result.Add(SysmlLanguage.Instance.ViewRenderingMembership_referencedRendering);
        return result;
    }
}

