<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LionWeb-CSharp" Version="0.4.0" />
    <PackageVersion Include="LionWeb-CSharp-Generator" Version="0.4.0" />
    <PackageVersion Include="LionWeb-CSharp-Generator-MpsSpecific" Version="0.4.0" />
    <PackageVersion Include="LionWeb-LionWeb-CSharp-Generator-MpsSpecific" Version="0.4.0" />
  </ItemGroup>
</Project>