<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="LionWeb-CSharp" Version="0.4.0-alpha.8.9" />
		<PackageVersion Include="LionWeb-CSharp-Generator" Version="0.4.0-alpha.8.9" />
	</ItemGroup>
</Project>