@startuml
hide empty members

' qualified name: "types"


class "Boolean" <<primitive type>>
class "Integer" <<primitive type>>
class "Real" <<primitive type>>
class "String" <<primitive type>>
class "UnlimitedNatural" <<primitive type>>


' relations:







@enduml
