// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-AliasIdsContainer")]
public partial class AliasIdsContainer : ConceptInstanceBase
{
    private string? _aliasIds = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-AliasIdsContainer-aliasIds")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? AliasIds { get => _aliasIds; set => SetAliasIds(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetAliasIds([NotNullWhenAttribute(true)] out string? aliasIds)
    {
        aliasIds = _aliasIds;
        return aliasIds != null;
    }

    private bool SetAliasIdsRaw(string? value)
    {
        if (value == _aliasIds)
            return false;
        _aliasIds = value;
        return true;
    }

    /// <remarks>Optional Property</remarks>
    public AliasIdsContainer SetAliasIds(string? value)
    {
        SetOptionalReferenceTypeProperty<string>(value, KermlLanguage.Instance.AliasIdsContainer_aliasIds, _aliasIds, SetAliasIdsRaw);
        return this;
    }

    public AliasIdsContainer(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.AliasIdsContainer;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.AliasIdsContainer_aliasIds.EqualsIdentity(feature))
        {
            result = AliasIds;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.AliasIdsContainer_aliasIds.EqualsIdentity(feature))
        {
            result = _aliasIds;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.AliasIdsContainer_aliasIds.EqualsIdentity(feature))
        {
            if (value is null or string)
            {
                SetAliasIds((string? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.AliasIdsContainer_aliasIds.EqualsIdentity(feature) && value is null or string)
            return SetAliasIdsRaw((string? )value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetAliasIds(out _))
            result.Add(KermlLanguage.Instance.AliasIdsContainer_aliasIds);
        return result;
    }
}

