// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-Disjoining")]
public partial class Disjoining : ConceptInstanceBase, IRelationship
{
    private ReferenceTarget? _disjoiningType = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If DisjoiningType has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-Disjoining-disjoiningType")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IType DisjoiningType { get => ReferenceTargetNonNullTarget<IType>(_disjoiningType, KermlLanguage.Instance.Disjoining_disjoiningType) ?? throw new UnsetFeatureException(KermlLanguage.Instance.Disjoining_disjoiningType); set => SetDisjoiningType(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetDisjoiningType([NotNullWhenAttribute(true)] out IType? disjoiningType)
    {
        disjoiningType = ReferenceTargetNullableTarget<IType>(_disjoiningType, KermlLanguage.Instance.Disjoining_disjoiningType);
        return disjoiningType != null;
    }

    private Disjoining SetDisjoiningType(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IType>(value, KermlLanguage.Instance.Disjoining_disjoiningType, _disjoiningType, SetDisjoiningTypeRaw);
        return this;
    }

    private bool SetDisjoiningTypeRaw(ReferenceTarget? value)
    {
        if (value == _disjoiningType)
            return false;
        _disjoiningType = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public Disjoining SetDisjoiningType(IType value)
    {
        return SetDisjoiningType(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _owningType = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-Disjoining-owningType")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IType? OwningType { get => ReferenceTargetNonNullTarget<IType>(_owningType, KermlLanguage.Instance.Disjoining_owningType); set => SetOwningType(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetOwningType([NotNullWhenAttribute(true)] out IType? owningType)
    {
        owningType = ReferenceTargetNullableTarget<IType>(_owningType, KermlLanguage.Instance.Disjoining_owningType);
        return owningType != null;
    }

    private Disjoining SetOwningType(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IType>(value, KermlLanguage.Instance.Disjoining_owningType, _owningType, SetOwningTypeRaw);
        return this;
    }

    private bool SetOwningTypeRaw(ReferenceTarget? value)
    {
        if (value == _owningType)
            return false;
        _owningType = value;
        return true;
    }

    /// <remarks>Optional Single Reference</remarks>
    public Disjoining SetOwningType(IType? value)
    {
        return SetOwningType(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _typeDisjoined = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If TypeDisjoined has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-Disjoining-typeDisjoined")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IType TypeDisjoined { get => ReferenceTargetNonNullTarget<IType>(_typeDisjoined, KermlLanguage.Instance.Disjoining_typeDisjoined) ?? throw new UnsetFeatureException(KermlLanguage.Instance.Disjoining_typeDisjoined); set => SetTypeDisjoined(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetTypeDisjoined([NotNullWhenAttribute(true)] out IType? typeDisjoined)
    {
        typeDisjoined = ReferenceTargetNullableTarget<IType>(_typeDisjoined, KermlLanguage.Instance.Disjoining_typeDisjoined);
        return typeDisjoined != null;
    }

    private Disjoining SetTypeDisjoined(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IType>(value, KermlLanguage.Instance.Disjoining_typeDisjoined, _typeDisjoined, SetTypeDisjoinedRaw);
        return this;
    }

    private bool SetTypeDisjoinedRaw(ReferenceTarget? value)
    {
        if (value == _typeDisjoined)
            return false;
        _typeDisjoined = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public Disjoining SetTypeDisjoined(IType value)
    {
        return SetTypeDisjoined(ReferenceTarget.FromNodeOptional(value));
    }

    private bool SetAliasIdsContainerRaw(List<AliasIdsContainer> nodes) => ExchangeChildrenRaw(nodes, _aliasIdsContainer);
    private bool AddAliasIdsContainerRaw(AliasIdsContainer? value) => AddChildRaw(value, _aliasIdsContainer);
    private bool InsertAliasIdsContainerRaw(int index, AliasIdsContainer? value) => InsertChildRaw(index, value, _aliasIdsContainer);
    private bool RemoveAliasIdsContainerRaw(AliasIdsContainer? value) => RemoveChildRaw(value, _aliasIdsContainer);
    private readonly List<AliasIdsContainer> _aliasIdsContainer = [];
    /// <remarks>Optional Multiple Containment</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-aliasIdsContainer")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
    public IReadOnlyList<AliasIdsContainer> AliasIdsContainer { get => _aliasIdsContainer.AsReadOnly(); init => AddAliasIdsContainer(value); }

    /// <remarks>Optional Multiple Containment</remarks>
    public bool TryGetAliasIdsContainer([NotNullWhenAttribute(true)] out IReadOnlyList<AliasIdsContainer> aliasIdsContainer)
    {
        aliasIdsContainer = _aliasIdsContainer.AsReadOnly();
        return aliasIdsContainer.Count != 0;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IElement IElement.AddAliasIdsContainer(IEnumerable<AliasIdsContainer> nodes) => AddAliasIdsContainer(nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining AddAliasIdsContainer(IEnumerable<AliasIdsContainer> nodes)
    {
        AddOptionalMultipleContainment<AliasIdsContainer>(nodes, KermlLanguage.Instance.IElement_aliasIdsContainer, _aliasIdsContainer, AddAliasIdsContainerRaw);
        return this;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IElement IElement.InsertAliasIdsContainer(int index, IEnumerable<AliasIdsContainer> nodes) => InsertAliasIdsContainer(index, nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining InsertAliasIdsContainer(int index, IEnumerable<AliasIdsContainer> nodes)
    {
        InsertOptionalMultipleContainment<AliasIdsContainer>(index, nodes, KermlLanguage.Instance.IElement_aliasIdsContainer, _aliasIdsContainer, InsertAliasIdsContainerRaw);
        return this;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IElement IElement.RemoveAliasIdsContainer(IEnumerable<AliasIdsContainer> nodes) => RemoveAliasIdsContainer(nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining RemoveAliasIdsContainer(IEnumerable<AliasIdsContainer> nodes)
    {
        RemoveOptionalMultipleContainment<AliasIdsContainer>(nodes, KermlLanguage.Instance.IElement_aliasIdsContainer, _aliasIdsContainer, RemoveAliasIdsContainerRaw);
        return this;
    }

    private string? _declaredName = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-declaredName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? DeclaredName { get => _declaredName; set => SetDeclaredName(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetDeclaredName([NotNullWhenAttribute(true)] out string? declaredName)
    {
        declaredName = _declaredName;
        return declaredName != null;
    }

    private bool SetDeclaredNameRaw(string? value)
    {
        if (value == _declaredName)
            return false;
        _declaredName = value;
        return true;
    }

/// <remarks>Optional Property</remarks>
    IElement IElement.SetDeclaredName(string? value) => SetDeclaredName(value);
    /// <remarks>Optional Property</remarks>
    public Disjoining SetDeclaredName(string? value)
    {
        SetOptionalReferenceTypeProperty<string>(value, KermlLanguage.Instance.IElement_declaredName, _declaredName, SetDeclaredNameRaw);
        return this;
    }

    private string? _declaredShortName = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-declaredShortName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? DeclaredShortName { get => _declaredShortName; set => SetDeclaredShortName(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetDeclaredShortName([NotNullWhenAttribute(true)] out string? declaredShortName)
    {
        declaredShortName = _declaredShortName;
        return declaredShortName != null;
    }

    private bool SetDeclaredShortNameRaw(string? value)
    {
        if (value == _declaredShortName)
            return false;
        _declaredShortName = value;
        return true;
    }

/// <remarks>Optional Property</remarks>
    IElement IElement.SetDeclaredShortName(string? value) => SetDeclaredShortName(value);
    /// <remarks>Optional Property</remarks>
    public Disjoining SetDeclaredShortName(string? value)
    {
        SetOptionalReferenceTypeProperty<string>(value, KermlLanguage.Instance.IElement_declaredShortName, _declaredShortName, SetDeclaredShortNameRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _documentation_ = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-documentation")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Documentation> Documentation_ { get => ReferenceTargetNonNullTargets<Documentation>(_documentation_, KermlLanguage.Instance.IElement_documentation); init => AddDocumentation(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetDocumentation([NotNullWhenAttribute(true)] out IReadOnlyList<Documentation> documentation_) => TryGetReference<Documentation>(_documentation_, out documentation_);
    private bool SetDocumentationRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _documentation_);
    private bool AddDocumentationRaw(ReferenceTarget target) => AddReferencesRaw(target, _documentation_);
    private bool InsertDocumentationRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _documentation_);
    private bool RemoveDocumentationRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _documentation_);
/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.AddDocumentation(IEnumerable<Documentation> nodes) => AddDocumentation(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddDocumentation(IEnumerable<Documentation> nodes)
    {
        AddOptionalMultipleReference<Documentation>(nodes, KermlLanguage.Instance.IElement_documentation, _documentation_, AddDocumentationRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.InsertDocumentation(int index, IEnumerable<Documentation> nodes) => InsertDocumentation(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertDocumentation(int index, IEnumerable<Documentation> nodes)
    {
        InsertOptionalMultipleReference<Documentation>(index, nodes, KermlLanguage.Instance.IElement_documentation, _documentation_, InsertDocumentationRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.RemoveDocumentation(IEnumerable<Documentation> nodes) => RemoveDocumentation(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveDocumentation(IEnumerable<Documentation> nodes)
    {
        RemoveOptionalMultipleReference<Documentation>(nodes, KermlLanguage.Instance.IElement_documentation, _documentation_, RemoveDocumentationRaw);
        return this;
    }

    private string? _elementId = null;
    private bool SetElementIdRaw(string? value)
    {
        if (value == _elementId)
            return false;
        _elementId = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If ElementId has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-elementId")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public string ElementId { get => _elementId ?? throw new UnsetFeatureException(KermlLanguage.Instance.IElement_elementId); set => SetElementId(value); }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public bool TryGetElementId([NotNullWhenAttribute(true)] out string? elementId)
    {
        elementId = _elementId;
        return elementId != null;
    }

/// <remarks>Required Property</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
    IElement IElement.SetElementId(string value) => SetElementId(value);
    /// <remarks>Required Property</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public Disjoining SetElementId(string value)
    {
        SetRequiredReferenceTypeProperty<string>(value, KermlLanguage.Instance.IElement_elementId, _elementId, SetElementIdRaw);
        return this;
    }

    private bool? _isImpliedIncluded = null;
    private bool SetIsImpliedIncludedRaw(bool? value)
    {
        if (value == _isImpliedIncluded)
            return false;
        _isImpliedIncluded = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsImpliedIncluded has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-isImpliedIncluded")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsImpliedIncluded { get => _isImpliedIncluded ?? throw new UnsetFeatureException(KermlLanguage.Instance.IElement_isImpliedIncluded); set => SetIsImpliedIncluded(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsImpliedIncluded([NotNullWhenAttribute(true)] out bool? isImpliedIncluded)
    {
        isImpliedIncluded = _isImpliedIncluded;
        return isImpliedIncluded != null;
    }

/// <remarks>Required Property</remarks>
    IElement IElement.SetIsImpliedIncluded(bool value) => SetIsImpliedIncluded(value);
    /// <remarks>Required Property</remarks>
    public Disjoining SetIsImpliedIncluded(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, KermlLanguage.Instance.IElement_isImpliedIncluded, _isImpliedIncluded, SetIsImpliedIncludedRaw);
        return this;
    }

    private bool? _isLibraryElement = null;
    private bool SetIsLibraryElementRaw(bool? value)
    {
        if (value == _isLibraryElement)
            return false;
        _isLibraryElement = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsLibraryElement has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-isLibraryElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsLibraryElement { get => _isLibraryElement ?? throw new UnsetFeatureException(KermlLanguage.Instance.IElement_isLibraryElement); set => SetIsLibraryElement(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsLibraryElement([NotNullWhenAttribute(true)] out bool? isLibraryElement)
    {
        isLibraryElement = _isLibraryElement;
        return isLibraryElement != null;
    }

/// <remarks>Required Property</remarks>
    IElement IElement.SetIsLibraryElement(bool value) => SetIsLibraryElement(value);
    /// <remarks>Required Property</remarks>
    public Disjoining SetIsLibraryElement(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, KermlLanguage.Instance.IElement_isLibraryElement, _isLibraryElement, SetIsLibraryElementRaw);
        return this;
    }

    private string? _name = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-name")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? Name { get => _name; set => SetName(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetName([NotNullWhenAttribute(true)] out string? name)
    {
        name = _name;
        return name != null;
    }

    private bool SetNameRaw(string? value)
    {
        if (value == _name)
            return false;
        _name = value;
        return true;
    }

/// <remarks>Optional Property</remarks>
    IElement IElement.SetName(string? value) => SetName(value);
    /// <remarks>Optional Property</remarks>
    public Disjoining SetName(string? value)
    {
        SetOptionalReferenceTypeProperty<string>(value, KermlLanguage.Instance.IElement_name, _name, SetNameRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _ownedAnnotation = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-ownedAnnotation")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Annotation> OwnedAnnotation { get => ReferenceTargetNonNullTargets<Annotation>(_ownedAnnotation, KermlLanguage.Instance.IElement_ownedAnnotation); init => AddOwnedAnnotation(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetOwnedAnnotation([NotNullWhenAttribute(true)] out IReadOnlyList<Annotation> ownedAnnotation) => TryGetReference<Annotation>(_ownedAnnotation, out ownedAnnotation);
    private bool SetOwnedAnnotationRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _ownedAnnotation);
    private bool AddOwnedAnnotationRaw(ReferenceTarget target) => AddReferencesRaw(target, _ownedAnnotation);
    private bool InsertOwnedAnnotationRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _ownedAnnotation);
    private bool RemoveOwnedAnnotationRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _ownedAnnotation);
/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.AddOwnedAnnotation(IEnumerable<Annotation> nodes) => AddOwnedAnnotation(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddOwnedAnnotation(IEnumerable<Annotation> nodes)
    {
        AddOptionalMultipleReference<Annotation>(nodes, KermlLanguage.Instance.IElement_ownedAnnotation, _ownedAnnotation, AddOwnedAnnotationRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.InsertOwnedAnnotation(int index, IEnumerable<Annotation> nodes) => InsertOwnedAnnotation(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertOwnedAnnotation(int index, IEnumerable<Annotation> nodes)
    {
        InsertOptionalMultipleReference<Annotation>(index, nodes, KermlLanguage.Instance.IElement_ownedAnnotation, _ownedAnnotation, InsertOwnedAnnotationRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.RemoveOwnedAnnotation(IEnumerable<Annotation> nodes) => RemoveOwnedAnnotation(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveOwnedAnnotation(IEnumerable<Annotation> nodes)
    {
        RemoveOptionalMultipleReference<Annotation>(nodes, KermlLanguage.Instance.IElement_ownedAnnotation, _ownedAnnotation, RemoveOwnedAnnotationRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _ownedElement = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-ownedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IElement> OwnedElement { get => ReferenceTargetNonNullTargets<IElement>(_ownedElement, KermlLanguage.Instance.IElement_ownedElement); init => AddOwnedElement(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetOwnedElement([NotNullWhenAttribute(true)] out IReadOnlyList<IElement> ownedElement) => TryGetReference<IElement>(_ownedElement, out ownedElement);
    private bool SetOwnedElementRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _ownedElement);
    private bool AddOwnedElementRaw(ReferenceTarget target) => AddReferencesRaw(target, _ownedElement);
    private bool InsertOwnedElementRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _ownedElement);
    private bool RemoveOwnedElementRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _ownedElement);
/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.AddOwnedElement(IEnumerable<IElement> nodes) => AddOwnedElement(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddOwnedElement(IEnumerable<IElement> nodes)
    {
        AddOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IElement_ownedElement, _ownedElement, AddOwnedElementRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.InsertOwnedElement(int index, IEnumerable<IElement> nodes) => InsertOwnedElement(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertOwnedElement(int index, IEnumerable<IElement> nodes)
    {
        InsertOptionalMultipleReference<IElement>(index, nodes, KermlLanguage.Instance.IElement_ownedElement, _ownedElement, InsertOwnedElementRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.RemoveOwnedElement(IEnumerable<IElement> nodes) => RemoveOwnedElement(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveOwnedElement(IEnumerable<IElement> nodes)
    {
        RemoveOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IElement_ownedElement, _ownedElement, RemoveOwnedElementRaw);
        return this;
    }

    private bool SetOwnedRelationshipRaw(List<IRelationship> nodes) => ExchangeChildrenRaw(nodes, _ownedRelationship);
    private bool AddOwnedRelationshipRaw(IRelationship? value) => AddChildRaw(value, _ownedRelationship);
    private bool InsertOwnedRelationshipRaw(int index, IRelationship? value) => InsertChildRaw(index, value, _ownedRelationship);
    private bool RemoveOwnedRelationshipRaw(IRelationship? value) => RemoveChildRaw(value, _ownedRelationship);
    private readonly List<IRelationship> _ownedRelationship = [];
    /// <remarks>Optional Multiple Containment</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-ownedRelationship")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
    public IReadOnlyList<IRelationship> OwnedRelationship { get => _ownedRelationship.AsReadOnly(); init => AddOwnedRelationship(value); }

    /// <remarks>Optional Multiple Containment</remarks>
    public bool TryGetOwnedRelationship([NotNullWhenAttribute(true)] out IReadOnlyList<IRelationship> ownedRelationship)
    {
        ownedRelationship = _ownedRelationship.AsReadOnly();
        return ownedRelationship.Count != 0;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IElement IElement.AddOwnedRelationship(IEnumerable<IRelationship> nodes) => AddOwnedRelationship(nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining AddOwnedRelationship(IEnumerable<IRelationship> nodes)
    {
        AddOptionalMultipleContainment<IRelationship>(nodes, KermlLanguage.Instance.IElement_ownedRelationship, _ownedRelationship, AddOwnedRelationshipRaw);
        return this;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IElement IElement.InsertOwnedRelationship(int index, IEnumerable<IRelationship> nodes) => InsertOwnedRelationship(index, nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining InsertOwnedRelationship(int index, IEnumerable<IRelationship> nodes)
    {
        InsertOptionalMultipleContainment<IRelationship>(index, nodes, KermlLanguage.Instance.IElement_ownedRelationship, _ownedRelationship, InsertOwnedRelationshipRaw);
        return this;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IElement IElement.RemoveOwnedRelationship(IEnumerable<IRelationship> nodes) => RemoveOwnedRelationship(nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining RemoveOwnedRelationship(IEnumerable<IRelationship> nodes)
    {
        RemoveOptionalMultipleContainment<IRelationship>(nodes, KermlLanguage.Instance.IElement_ownedRelationship, _ownedRelationship, RemoveOwnedRelationshipRaw);
        return this;
    }

    private ReferenceTarget? _owner = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-owner")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IElement? Owner { get => ReferenceTargetNonNullTarget<IElement>(_owner, KermlLanguage.Instance.IElement_owner); set => SetOwner(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetOwner([NotNullWhenAttribute(true)] out IElement? owner)
    {
        owner = ReferenceTargetNullableTarget<IElement>(_owner, KermlLanguage.Instance.IElement_owner);
        return owner != null;
    }

    private Disjoining SetOwner(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IElement>(value, KermlLanguage.Instance.IElement_owner, _owner, SetOwnerRaw);
        return this;
    }

    private bool SetOwnerRaw(ReferenceTarget? value)
    {
        if (value == _owner)
            return false;
        _owner = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IElement IElement.SetOwner(IElement? value) => SetOwner(value);
    /// <remarks>Optional Single Reference</remarks>
    public Disjoining SetOwner(IElement? value)
    {
        return SetOwner(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _owningMembership_ = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-owningMembership")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public OwningMembership? OwningMembership_ { get => ReferenceTargetNonNullTarget<OwningMembership>(_owningMembership_, KermlLanguage.Instance.IElement_owningMembership); set => SetOwningMembership(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetOwningMembership([NotNullWhenAttribute(true)] out OwningMembership? owningMembership_)
    {
        owningMembership_ = ReferenceTargetNullableTarget<OwningMembership>(_owningMembership_, KermlLanguage.Instance.IElement_owningMembership);
        return owningMembership_ != null;
    }

    private Disjoining SetOwningMembership(ReferenceTarget? value)
    {
        SetOptionalSingleReference<OwningMembership>(value, KermlLanguage.Instance.IElement_owningMembership, _owningMembership_, SetOwningMembershipRaw);
        return this;
    }

    private bool SetOwningMembershipRaw(ReferenceTarget? value)
    {
        if (value == _owningMembership_)
            return false;
        _owningMembership_ = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IElement IElement.SetOwningMembership(OwningMembership? value) => SetOwningMembership(value);
    /// <remarks>Optional Single Reference</remarks>
    public Disjoining SetOwningMembership(OwningMembership? value)
    {
        return SetOwningMembership(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _owningNamespace = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-owningNamespace")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public INamespace? OwningNamespace { get => ReferenceTargetNonNullTarget<INamespace>(_owningNamespace, KermlLanguage.Instance.IElement_owningNamespace); set => SetOwningNamespace(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetOwningNamespace([NotNullWhenAttribute(true)] out INamespace? owningNamespace)
    {
        owningNamespace = ReferenceTargetNullableTarget<INamespace>(_owningNamespace, KermlLanguage.Instance.IElement_owningNamespace);
        return owningNamespace != null;
    }

    private Disjoining SetOwningNamespace(ReferenceTarget? value)
    {
        SetOptionalSingleReference<INamespace>(value, KermlLanguage.Instance.IElement_owningNamespace, _owningNamespace, SetOwningNamespaceRaw);
        return this;
    }

    private bool SetOwningNamespaceRaw(ReferenceTarget? value)
    {
        if (value == _owningNamespace)
            return false;
        _owningNamespace = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IElement IElement.SetOwningNamespace(INamespace? value) => SetOwningNamespace(value);
    /// <remarks>Optional Single Reference</remarks>
    public Disjoining SetOwningNamespace(INamespace? value)
    {
        return SetOwningNamespace(ReferenceTarget.FromNodeOptional(value));
    }

    private ReferenceTarget? _owningRelationship = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-owningRelationship")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IRelationship? OwningRelationship { get => ReferenceTargetNonNullTarget<IRelationship>(_owningRelationship, KermlLanguage.Instance.IElement_owningRelationship); set => SetOwningRelationship(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetOwningRelationship([NotNullWhenAttribute(true)] out IRelationship? owningRelationship)
    {
        owningRelationship = ReferenceTargetNullableTarget<IRelationship>(_owningRelationship, KermlLanguage.Instance.IElement_owningRelationship);
        return owningRelationship != null;
    }

    private Disjoining SetOwningRelationship(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IRelationship>(value, KermlLanguage.Instance.IElement_owningRelationship, _owningRelationship, SetOwningRelationshipRaw);
        return this;
    }

    private bool SetOwningRelationshipRaw(ReferenceTarget? value)
    {
        if (value == _owningRelationship)
            return false;
        _owningRelationship = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IElement IElement.SetOwningRelationship(IRelationship? value) => SetOwningRelationship(value);
    /// <remarks>Optional Single Reference</remarks>
    public Disjoining SetOwningRelationship(IRelationship? value)
    {
        return SetOwningRelationship(ReferenceTarget.FromNodeOptional(value));
    }

    private string? _qualifiedName = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-qualifiedName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? QualifiedName { get => _qualifiedName; set => SetQualifiedName(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetQualifiedName([NotNullWhenAttribute(true)] out string? qualifiedName)
    {
        qualifiedName = _qualifiedName;
        return qualifiedName != null;
    }

    private bool SetQualifiedNameRaw(string? value)
    {
        if (value == _qualifiedName)
            return false;
        _qualifiedName = value;
        return true;
    }

/// <remarks>Optional Property</remarks>
    IElement IElement.SetQualifiedName(string? value) => SetQualifiedName(value);
    /// <remarks>Optional Property</remarks>
    public Disjoining SetQualifiedName(string? value)
    {
        SetOptionalReferenceTypeProperty<string>(value, KermlLanguage.Instance.IElement_qualifiedName, _qualifiedName, SetQualifiedNameRaw);
        return this;
    }

    private string? _shortName = null;
    /// <remarks>Optional Property</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-shortName")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
    public string? ShortName { get => _shortName; set => SetShortName(value); }

    /// <remarks>Optional Property</remarks>
    public bool TryGetShortName([NotNullWhenAttribute(true)] out string? shortName)
    {
        shortName = _shortName;
        return shortName != null;
    }

    private bool SetShortNameRaw(string? value)
    {
        if (value == _shortName)
            return false;
        _shortName = value;
        return true;
    }

/// <remarks>Optional Property</remarks>
    IElement IElement.SetShortName(string? value) => SetShortName(value);
    /// <remarks>Optional Property</remarks>
    public Disjoining SetShortName(string? value)
    {
        SetOptionalReferenceTypeProperty<string>(value, KermlLanguage.Instance.IElement_shortName, _shortName, SetShortNameRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _textualRepresentation_ = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IElement-textualRepresentation")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<TextualRepresentation> TextualRepresentation_ { get => ReferenceTargetNonNullTargets<TextualRepresentation>(_textualRepresentation_, KermlLanguage.Instance.IElement_textualRepresentation); init => AddTextualRepresentation(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetTextualRepresentation([NotNullWhenAttribute(true)] out IReadOnlyList<TextualRepresentation> textualRepresentation_) => TryGetReference<TextualRepresentation>(_textualRepresentation_, out textualRepresentation_);
    private bool SetTextualRepresentationRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _textualRepresentation_);
    private bool AddTextualRepresentationRaw(ReferenceTarget target) => AddReferencesRaw(target, _textualRepresentation_);
    private bool InsertTextualRepresentationRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _textualRepresentation_);
    private bool RemoveTextualRepresentationRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _textualRepresentation_);
/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.AddTextualRepresentation(IEnumerable<TextualRepresentation> nodes) => AddTextualRepresentation(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddTextualRepresentation(IEnumerable<TextualRepresentation> nodes)
    {
        AddOptionalMultipleReference<TextualRepresentation>(nodes, KermlLanguage.Instance.IElement_textualRepresentation, _textualRepresentation_, AddTextualRepresentationRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.InsertTextualRepresentation(int index, IEnumerable<TextualRepresentation> nodes) => InsertTextualRepresentation(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertTextualRepresentation(int index, IEnumerable<TextualRepresentation> nodes)
    {
        InsertOptionalMultipleReference<TextualRepresentation>(index, nodes, KermlLanguage.Instance.IElement_textualRepresentation, _textualRepresentation_, InsertTextualRepresentationRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IElement IElement.RemoveTextualRepresentation(IEnumerable<TextualRepresentation> nodes) => RemoveTextualRepresentation(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveTextualRepresentation(IEnumerable<TextualRepresentation> nodes)
    {
        RemoveOptionalMultipleReference<TextualRepresentation>(nodes, KermlLanguage.Instance.IElement_textualRepresentation, _textualRepresentation_, RemoveTextualRepresentationRaw);
        return this;
    }

    private bool? _isImplied = null;
    private bool SetIsImpliedRaw(bool? value)
    {
        if (value == _isImplied)
            return false;
        _isImplied = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsImplied has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IRelationship-isImplied")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsImplied { get => _isImplied ?? throw new UnsetFeatureException(KermlLanguage.Instance.IRelationship_isImplied); set => SetIsImplied(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsImplied([NotNullWhenAttribute(true)] out bool? isImplied)
    {
        isImplied = _isImplied;
        return isImplied != null;
    }

/// <remarks>Required Property</remarks>
    IRelationship IRelationship.SetIsImplied(bool value) => SetIsImplied(value);
    /// <remarks>Required Property</remarks>
    public Disjoining SetIsImplied(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, KermlLanguage.Instance.IRelationship_isImplied, _isImplied, SetIsImpliedRaw);
        return this;
    }

    private bool SetOwnedRelatedElementRaw(List<IElement> nodes) => ExchangeChildrenRaw(nodes, _ownedRelatedElement);
    private bool AddOwnedRelatedElementRaw(IElement? value) => AddChildRaw(value, _ownedRelatedElement);
    private bool InsertOwnedRelatedElementRaw(int index, IElement? value) => InsertChildRaw(index, value, _ownedRelatedElement);
    private bool RemoveOwnedRelatedElementRaw(IElement? value) => RemoveChildRaw(value, _ownedRelatedElement);
    private readonly List<IElement> _ownedRelatedElement = [];
    /// <remarks>Optional Multiple Containment</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IRelationship-ownedRelatedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
    public IReadOnlyList<IElement> OwnedRelatedElement { get => _ownedRelatedElement.AsReadOnly(); init => AddOwnedRelatedElement(value); }

    /// <remarks>Optional Multiple Containment</remarks>
    public bool TryGetOwnedRelatedElement([NotNullWhenAttribute(true)] out IReadOnlyList<IElement> ownedRelatedElement)
    {
        ownedRelatedElement = _ownedRelatedElement.AsReadOnly();
        return ownedRelatedElement.Count != 0;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IRelationship IRelationship.AddOwnedRelatedElement(IEnumerable<IElement> nodes) => AddOwnedRelatedElement(nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining AddOwnedRelatedElement(IEnumerable<IElement> nodes)
    {
        AddOptionalMultipleContainment<IElement>(nodes, KermlLanguage.Instance.IRelationship_ownedRelatedElement, _ownedRelatedElement, AddOwnedRelatedElementRaw);
        return this;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IRelationship IRelationship.InsertOwnedRelatedElement(int index, IEnumerable<IElement> nodes) => InsertOwnedRelatedElement(index, nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining InsertOwnedRelatedElement(int index, IEnumerable<IElement> nodes)
    {
        InsertOptionalMultipleContainment<IElement>(index, nodes, KermlLanguage.Instance.IRelationship_ownedRelatedElement, _ownedRelatedElement, InsertOwnedRelatedElementRaw);
        return this;
    }

/// <remarks>Optional Multiple Containment</remarks>
    IRelationship IRelationship.RemoveOwnedRelatedElement(IEnumerable<IElement> nodes) => RemoveOwnedRelatedElement(nodes);
    /// <remarks>Optional Multiple Containment</remarks>
    public Disjoining RemoveOwnedRelatedElement(IEnumerable<IElement> nodes)
    {
        RemoveOptionalMultipleContainment<IElement>(nodes, KermlLanguage.Instance.IRelationship_ownedRelatedElement, _ownedRelatedElement, RemoveOwnedRelatedElementRaw);
        return this;
    }

    private ReferenceTarget? _owningRelatedElement = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IRelationship-owningRelatedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IElement? OwningRelatedElement { get => ReferenceTargetNonNullTarget<IElement>(_owningRelatedElement, KermlLanguage.Instance.IRelationship_owningRelatedElement); set => SetOwningRelatedElement(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetOwningRelatedElement([NotNullWhenAttribute(true)] out IElement? owningRelatedElement)
    {
        owningRelatedElement = ReferenceTargetNullableTarget<IElement>(_owningRelatedElement, KermlLanguage.Instance.IRelationship_owningRelatedElement);
        return owningRelatedElement != null;
    }

    private Disjoining SetOwningRelatedElement(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IElement>(value, KermlLanguage.Instance.IRelationship_owningRelatedElement, _owningRelatedElement, SetOwningRelatedElementRaw);
        return this;
    }

    private bool SetOwningRelatedElementRaw(ReferenceTarget? value)
    {
        if (value == _owningRelatedElement)
            return false;
        _owningRelatedElement = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    IRelationship IRelationship.SetOwningRelatedElement(IElement? value) => SetOwningRelatedElement(value);
    /// <remarks>Optional Single Reference</remarks>
    public Disjoining SetOwningRelatedElement(IElement? value)
    {
        return SetOwningRelatedElement(ReferenceTarget.FromNodeOptional(value));
    }

    private readonly List<ReferenceTarget> _relatedElement = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IRelationship-relatedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IElement> RelatedElement { get => ReferenceTargetNonNullTargets<IElement>(_relatedElement, KermlLanguage.Instance.IRelationship_relatedElement); init => AddRelatedElement(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetRelatedElement([NotNullWhenAttribute(true)] out IReadOnlyList<IElement> relatedElement) => TryGetReference<IElement>(_relatedElement, out relatedElement);
    private bool SetRelatedElementRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _relatedElement);
    private bool AddRelatedElementRaw(ReferenceTarget target) => AddReferencesRaw(target, _relatedElement);
    private bool InsertRelatedElementRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _relatedElement);
    private bool RemoveRelatedElementRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _relatedElement);
/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.AddRelatedElement(IEnumerable<IElement> nodes) => AddRelatedElement(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddRelatedElement(IEnumerable<IElement> nodes)
    {
        AddOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IRelationship_relatedElement, _relatedElement, AddRelatedElementRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.InsertRelatedElement(int index, IEnumerable<IElement> nodes) => InsertRelatedElement(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertRelatedElement(int index, IEnumerable<IElement> nodes)
    {
        InsertOptionalMultipleReference<IElement>(index, nodes, KermlLanguage.Instance.IRelationship_relatedElement, _relatedElement, InsertRelatedElementRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.RemoveRelatedElement(IEnumerable<IElement> nodes) => RemoveRelatedElement(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveRelatedElement(IEnumerable<IElement> nodes)
    {
        RemoveOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IRelationship_relatedElement, _relatedElement, RemoveRelatedElementRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _source = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IRelationship-source")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IElement> Source { get => ReferenceTargetNonNullTargets<IElement>(_source, KermlLanguage.Instance.IRelationship_source); init => AddSource(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetSource([NotNullWhenAttribute(true)] out IReadOnlyList<IElement> source) => TryGetReference<IElement>(_source, out source);
    private bool SetSourceRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _source);
    private bool AddSourceRaw(ReferenceTarget target) => AddReferencesRaw(target, _source);
    private bool InsertSourceRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _source);
    private bool RemoveSourceRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _source);
/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.AddSource(IEnumerable<IElement> nodes) => AddSource(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddSource(IEnumerable<IElement> nodes)
    {
        AddOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IRelationship_source, _source, AddSourceRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.InsertSource(int index, IEnumerable<IElement> nodes) => InsertSource(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertSource(int index, IEnumerable<IElement> nodes)
    {
        InsertOptionalMultipleReference<IElement>(index, nodes, KermlLanguage.Instance.IRelationship_source, _source, InsertSourceRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.RemoveSource(IEnumerable<IElement> nodes) => RemoveSource(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveSource(IEnumerable<IElement> nodes)
    {
        RemoveOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IRelationship_source, _source, RemoveSourceRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _target = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IRelationship-target")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IElement> Target { get => ReferenceTargetNonNullTargets<IElement>(_target, KermlLanguage.Instance.IRelationship_target); init => AddTarget(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetTarget([NotNullWhenAttribute(true)] out IReadOnlyList<IElement> target) => TryGetReference<IElement>(_target, out target);
    private bool SetTargetRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _target);
    private bool AddTargetRaw(ReferenceTarget target) => AddReferencesRaw(target, _target);
    private bool InsertTargetRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _target);
    private bool RemoveTargetRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _target);
/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.AddTarget(IEnumerable<IElement> nodes) => AddTarget(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining AddTarget(IEnumerable<IElement> nodes)
    {
        AddOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IRelationship_target, _target, AddTargetRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.InsertTarget(int index, IEnumerable<IElement> nodes) => InsertTarget(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining InsertTarget(int index, IEnumerable<IElement> nodes)
    {
        InsertOptionalMultipleReference<IElement>(index, nodes, KermlLanguage.Instance.IRelationship_target, _target, InsertTargetRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    IRelationship IRelationship.RemoveTarget(IEnumerable<IElement> nodes) => RemoveTarget(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public Disjoining RemoveTarget(IEnumerable<IElement> nodes)
    {
        RemoveOptionalMultipleReference<IElement>(nodes, KermlLanguage.Instance.IRelationship_target, _target, RemoveTargetRaw);
        return this;
    }

    public Disjoining(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.Disjoining;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.Disjoining_disjoiningType.EqualsIdentity(feature))
        {
            result = DisjoiningType;
            return true;
        }

        if (KermlLanguage.Instance.Disjoining_owningType.EqualsIdentity(feature))
        {
            result = OwningType;
            return true;
        }

        if (KermlLanguage.Instance.Disjoining_typeDisjoined.EqualsIdentity(feature))
        {
            result = TypeDisjoined;
            return true;
        }

        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(feature))
        {
            result = AliasIdsContainer;
            return true;
        }

        if (KermlLanguage.Instance.IElement_declaredName.EqualsIdentity(feature))
        {
            result = DeclaredName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_declaredShortName.EqualsIdentity(feature))
        {
            result = DeclaredShortName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(feature))
        {
            result = Documentation_;
            return true;
        }

        if (KermlLanguage.Instance.IElement_elementId.EqualsIdentity(feature))
        {
            result = ElementId;
            return true;
        }

        if (KermlLanguage.Instance.IElement_isImpliedIncluded.EqualsIdentity(feature))
        {
            result = IsImpliedIncluded;
            return true;
        }

        if (KermlLanguage.Instance.IElement_isLibraryElement.EqualsIdentity(feature))
        {
            result = IsLibraryElement;
            return true;
        }

        if (KermlLanguage.Instance.IElement_name.EqualsIdentity(feature))
        {
            result = Name;
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(feature))
        {
            result = OwnedAnnotation;
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(feature))
        {
            result = OwnedElement;
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(feature))
        {
            result = OwnedRelationship;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owner.EqualsIdentity(feature))
        {
            result = Owner;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owningMembership.EqualsIdentity(feature))
        {
            result = OwningMembership_;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owningNamespace.EqualsIdentity(feature))
        {
            result = OwningNamespace;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owningRelationship.EqualsIdentity(feature))
        {
            result = OwningRelationship;
            return true;
        }

        if (KermlLanguage.Instance.IElement_qualifiedName.EqualsIdentity(feature))
        {
            result = QualifiedName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_shortName.EqualsIdentity(feature))
        {
            result = ShortName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(feature))
        {
            result = TextualRepresentation_;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_isImplied.EqualsIdentity(feature))
        {
            result = IsImplied;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(feature))
        {
            result = OwnedRelatedElement;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_owningRelatedElement.EqualsIdentity(feature))
        {
            result = OwningRelatedElement;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(feature))
        {
            result = RelatedElement;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(feature))
        {
            result = Source;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(feature))
        {
            result = Target;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.IElement_declaredName.EqualsIdentity(feature))
        {
            result = _declaredName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_declaredShortName.EqualsIdentity(feature))
        {
            result = _declaredShortName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_elementId.EqualsIdentity(feature))
        {
            result = _elementId;
            return true;
        }

        if (KermlLanguage.Instance.IElement_isImpliedIncluded.EqualsIdentity(feature))
        {
            result = _isImpliedIncluded;
            return true;
        }

        if (KermlLanguage.Instance.IElement_isLibraryElement.EqualsIdentity(feature))
        {
            result = _isLibraryElement;
            return true;
        }

        if (KermlLanguage.Instance.IElement_name.EqualsIdentity(feature))
        {
            result = _name;
            return true;
        }

        if (KermlLanguage.Instance.IElement_qualifiedName.EqualsIdentity(feature))
        {
            result = _qualifiedName;
            return true;
        }

        if (KermlLanguage.Instance.IElement_shortName.EqualsIdentity(feature))
        {
            result = _shortName;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_isImplied.EqualsIdentity(feature))
        {
            result = _isImplied;
            return true;
        }

        return false;
    }

    protected override bool TryGetContainmentsRaw(Containment feature, out IReadOnlyList<IReadableNode> result)
    {
        if (base.TryGetContainmentsRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(feature))
        {
            result = _aliasIdsContainer;
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(feature))
        {
            result = _ownedRelationship;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(feature))
        {
            result = _ownedRelatedElement;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.Disjoining_disjoiningType.EqualsIdentity(feature))
        {
            result = _disjoiningType;
            return true;
        }

        if (KermlLanguage.Instance.Disjoining_owningType.EqualsIdentity(feature))
        {
            result = _owningType;
            return true;
        }

        if (KermlLanguage.Instance.Disjoining_typeDisjoined.EqualsIdentity(feature))
        {
            result = _typeDisjoined;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owner.EqualsIdentity(feature))
        {
            result = _owner;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owningMembership.EqualsIdentity(feature))
        {
            result = _owningMembership_;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owningNamespace.EqualsIdentity(feature))
        {
            result = _owningNamespace;
            return true;
        }

        if (KermlLanguage.Instance.IElement_owningRelationship.EqualsIdentity(feature))
        {
            result = _owningRelationship;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_owningRelatedElement.EqualsIdentity(feature))
        {
            result = _owningRelatedElement;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(feature))
        {
            result = _documentation_;
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(feature))
        {
            result = _ownedAnnotation;
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(feature))
        {
            result = _ownedElement;
            return true;
        }

        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(feature))
        {
            result = _textualRepresentation_;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(feature))
        {
            result = _relatedElement;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(feature))
        {
            result = _source;
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(feature))
        {
            result = _target;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.Disjoining_disjoiningType.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.IType v)
            {
                SetDisjoiningType(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetDisjoiningType(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.Disjoining_owningType.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.IType)
            {
                SetOwningType((LionWeb.Demo.SysMl2.Languages.KerMl.IType? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwningType(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.Disjoining_typeDisjoined.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.IType v)
            {
                SetTypeDisjoined(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetTypeDisjoined(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(feature))
        {
            SetOptionalMultipleContainment<AliasIdsContainer>(value, KermlLanguage.Instance.IElement_aliasIdsContainer, _aliasIdsContainer, SetAliasIdsContainerRaw);
            return true;
        }

        if (KermlLanguage.Instance.IElement_declaredName.EqualsIdentity(feature))
        {
            if (value is null or string)
            {
                SetDeclaredName((string? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_declaredShortName.EqualsIdentity(feature))
        {
            if (value is null or string)
            {
                SetDeclaredShortName((string? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<Documentation>(value, KermlLanguage.Instance.IElement_documentation, _documentation_, SetDocumentationRaw);
            return true;
        }

        if (KermlLanguage.Instance.IElement_elementId.EqualsIdentity(feature))
        {
            if (value is string v)
            {
                SetElementId(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_isImpliedIncluded.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsImpliedIncluded(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_isLibraryElement.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsLibraryElement(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_name.EqualsIdentity(feature))
        {
            if (value is null or string)
            {
                SetName((string? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<Annotation>(value, KermlLanguage.Instance.IElement_ownedAnnotation, _ownedAnnotation, SetOwnedAnnotationRaw);
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IElement>(value, KermlLanguage.Instance.IElement_ownedElement, _ownedElement, SetOwnedElementRaw);
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(feature))
        {
            SetOptionalMultipleContainment<IRelationship>(value, KermlLanguage.Instance.IElement_ownedRelationship, _ownedRelationship, SetOwnedRelationshipRaw);
            return true;
        }

        if (KermlLanguage.Instance.IElement_owner.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.IElement)
            {
                SetOwner((LionWeb.Demo.SysMl2.Languages.KerMl.IElement? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwner(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_owningMembership.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.OwningMembership)
            {
                SetOwningMembership((LionWeb.Demo.SysMl2.Languages.KerMl.OwningMembership? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwningMembership(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_owningNamespace.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.INamespace)
            {
                SetOwningNamespace((LionWeb.Demo.SysMl2.Languages.KerMl.INamespace? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwningNamespace(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_owningRelationship.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship)
            {
                SetOwningRelationship((LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwningRelationship(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_qualifiedName.EqualsIdentity(feature))
        {
            if (value is null or string)
            {
                SetQualifiedName((string? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_shortName.EqualsIdentity(feature))
        {
            if (value is null or string)
            {
                SetShortName((string? )value);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<TextualRepresentation>(value, KermlLanguage.Instance.IElement_textualRepresentation, _textualRepresentation_, SetTextualRepresentationRaw);
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_isImplied.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsImplied(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(feature))
        {
            SetOptionalMultipleContainment<IElement>(value, KermlLanguage.Instance.IRelationship_ownedRelatedElement, _ownedRelatedElement, SetOwnedRelatedElementRaw);
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_owningRelatedElement.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.IElement)
            {
                SetOwningRelatedElement((LionWeb.Demo.SysMl2.Languages.KerMl.IElement? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetOwningRelatedElement(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IElement>(value, KermlLanguage.Instance.IRelationship_relatedElement, _relatedElement, SetRelatedElementRaw);
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IElement>(value, KermlLanguage.Instance.IRelationship_source, _source, SetSourceRaw);
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IElement>(value, KermlLanguage.Instance.IRelationship_target, _target, SetTargetRaw);
            return true;
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.IElement_declaredName.EqualsIdentity(feature) && value is null or string)
            return SetDeclaredNameRaw((string? )value);
        if (KermlLanguage.Instance.IElement_declaredShortName.EqualsIdentity(feature) && value is null or string)
            return SetDeclaredShortNameRaw((string? )value);
        if (KermlLanguage.Instance.IElement_elementId.EqualsIdentity(feature) && value is null or string)
            return SetElementIdRaw((string? )value);
        if (KermlLanguage.Instance.IElement_isImpliedIncluded.EqualsIdentity(feature) && value is null or bool)
            return SetIsImpliedIncludedRaw((bool? )value);
        if (KermlLanguage.Instance.IElement_isLibraryElement.EqualsIdentity(feature) && value is null or bool)
            return SetIsLibraryElementRaw((bool? )value);
        if (KermlLanguage.Instance.IElement_name.EqualsIdentity(feature) && value is null or string)
            return SetNameRaw((string? )value);
        if (KermlLanguage.Instance.IElement_qualifiedName.EqualsIdentity(feature) && value is null or string)
            return SetQualifiedNameRaw((string? )value);
        if (KermlLanguage.Instance.IElement_shortName.EqualsIdentity(feature) && value is null or string)
            return SetShortNameRaw((string? )value);
        if (KermlLanguage.Instance.IRelationship_isImplied.EqualsIdentity(feature) && value is null or bool)
            return SetIsImpliedRaw((bool? )value);
        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.Disjoining_disjoiningType.EqualsIdentity(feature))
            return SetDisjoiningTypeRaw(value);
        if (KermlLanguage.Instance.Disjoining_owningType.EqualsIdentity(feature))
            return SetOwningTypeRaw(value);
        if (KermlLanguage.Instance.Disjoining_typeDisjoined.EqualsIdentity(feature))
            return SetTypeDisjoinedRaw(value);
        if (KermlLanguage.Instance.IElement_owner.EqualsIdentity(feature))
            return SetOwnerRaw(value);
        if (KermlLanguage.Instance.IElement_owningMembership.EqualsIdentity(feature))
            return SetOwningMembershipRaw(value);
        if (KermlLanguage.Instance.IElement_owningNamespace.EqualsIdentity(feature))
            return SetOwningNamespaceRaw(value);
        if (KermlLanguage.Instance.IElement_owningRelationship.EqualsIdentity(feature))
            return SetOwningRelationshipRaw(value);
        if (KermlLanguage.Instance.IRelationship_owningRelatedElement.EqualsIdentity(feature))
            return SetOwningRelatedElementRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetDisjoiningType(out _))
            result.Add(KermlLanguage.Instance.Disjoining_disjoiningType);
        if (TryGetOwningType(out _))
            result.Add(KermlLanguage.Instance.Disjoining_owningType);
        if (TryGetTypeDisjoined(out _))
            result.Add(KermlLanguage.Instance.Disjoining_typeDisjoined);
        if (TryGetAliasIdsContainer(out _))
            result.Add(KermlLanguage.Instance.IElement_aliasIdsContainer);
        if (TryGetDeclaredName(out _))
            result.Add(KermlLanguage.Instance.IElement_declaredName);
        if (TryGetDeclaredShortName(out _))
            result.Add(KermlLanguage.Instance.IElement_declaredShortName);
        if (TryGetDocumentation(out _))
            result.Add(KermlLanguage.Instance.IElement_documentation);
        if (TryGetElementId(out _))
            result.Add(KermlLanguage.Instance.IElement_elementId);
        if (TryGetIsImpliedIncluded(out _))
            result.Add(KermlLanguage.Instance.IElement_isImpliedIncluded);
        if (TryGetIsLibraryElement(out _))
            result.Add(KermlLanguage.Instance.IElement_isLibraryElement);
        if (TryGetName(out _))
            result.Add(KermlLanguage.Instance.IElement_name);
        if (TryGetOwnedAnnotation(out _))
            result.Add(KermlLanguage.Instance.IElement_ownedAnnotation);
        if (TryGetOwnedElement(out _))
            result.Add(KermlLanguage.Instance.IElement_ownedElement);
        if (TryGetOwnedRelationship(out _))
            result.Add(KermlLanguage.Instance.IElement_ownedRelationship);
        if (TryGetOwner(out _))
            result.Add(KermlLanguage.Instance.IElement_owner);
        if (TryGetOwningMembership(out _))
            result.Add(KermlLanguage.Instance.IElement_owningMembership);
        if (TryGetOwningNamespace(out _))
            result.Add(KermlLanguage.Instance.IElement_owningNamespace);
        if (TryGetOwningRelationship(out _))
            result.Add(KermlLanguage.Instance.IElement_owningRelationship);
        if (TryGetQualifiedName(out _))
            result.Add(KermlLanguage.Instance.IElement_qualifiedName);
        if (TryGetShortName(out _))
            result.Add(KermlLanguage.Instance.IElement_shortName);
        if (TryGetTextualRepresentation(out _))
            result.Add(KermlLanguage.Instance.IElement_textualRepresentation);
        if (TryGetIsImplied(out _))
            result.Add(KermlLanguage.Instance.IRelationship_isImplied);
        if (TryGetOwnedRelatedElement(out _))
            result.Add(KermlLanguage.Instance.IRelationship_ownedRelatedElement);
        if (TryGetOwningRelatedElement(out _))
            result.Add(KermlLanguage.Instance.IRelationship_owningRelatedElement);
        if (TryGetRelatedElement(out _))
            result.Add(KermlLanguage.Instance.IRelationship_relatedElement);
        if (TryGetSource(out _))
            result.Add(KermlLanguage.Instance.IRelationship_source);
        if (TryGetTarget(out _))
            result.Add(KermlLanguage.Instance.IRelationship_target);
        return result;
    }

    protected override bool AddContainmentsRaw(Containment feature, IWritableNode value)
    {
        if (base.AddContainmentsRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.AliasIdsContainer v0)
            return AddAliasIdsContainerRaw(v0);
        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship v1)
            return AddOwnedRelationshipRaw(v1);
        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.IElement v2)
            return AddOwnedRelatedElementRaw(v2);
        return false;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(feature))
            return AddDocumentationRaw(value);
        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(feature))
            return AddOwnedAnnotationRaw(value);
        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(feature))
            return AddOwnedElementRaw(value);
        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(feature))
            return AddTextualRepresentationRaw(value);
        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(feature))
            return AddRelatedElementRaw(value);
        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(feature))
            return AddSourceRaw(value);
        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(feature))
            return AddTargetRaw(value);
        return false;
    }

    protected override bool InsertContainmentsRaw(Containment feature, int index, IWritableNode value)
    {
        if (base.InsertContainmentsRaw(feature, index, value))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.AliasIdsContainer v0)
            return InsertAliasIdsContainerRaw(index, v0);
        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship v1)
            return InsertOwnedRelationshipRaw(index, v1);
        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.IElement v2)
            return InsertOwnedRelatedElementRaw(index, v2);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(feature))
            return InsertDocumentationRaw(index, value);
        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(feature))
            return InsertOwnedAnnotationRaw(index, value);
        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(feature))
            return InsertOwnedElementRaw(index, value);
        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(feature))
            return InsertTextualRepresentationRaw(index, value);
        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(feature))
            return InsertRelatedElementRaw(index, value);
        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(feature))
            return InsertSourceRaw(index, value);
        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(feature))
            return InsertTargetRaw(index, value);
        return false;
    }

    protected override bool RemoveContainmentsRaw(Containment feature, IWritableNode value)
    {
        if (base.RemoveContainmentsRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.AliasIdsContainer v0)
            return RemoveAliasIdsContainerRaw(v0);
        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship v1)
            return RemoveOwnedRelationshipRaw(v1);
        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(feature) && value is LionWeb.Demo.SysMl2.Languages.KerMl.IElement v2)
            return RemoveOwnedRelatedElementRaw(v2);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(feature))
            return RemoveDocumentationRaw(value);
        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(feature))
            return RemoveOwnedAnnotationRaw(value);
        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(feature))
            return RemoveOwnedElementRaw(value);
        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(feature))
            return RemoveTextualRepresentationRaw(value);
        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(feature))
            return RemoveRelatedElementRaw(value);
        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(feature))
            return RemoveSourceRaw(value);
        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(feature))
            return RemoveTargetRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(link))
        {
            AddAliasIdsContainer(KermlLanguage.Instance.IElement_aliasIdsContainer.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.AliasIdsContainer>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(link))
        {
            AddDocumentation(KermlLanguage.Instance.IElement_documentation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Documentation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(link))
        {
            AddOwnedAnnotation(KermlLanguage.Instance.IElement_ownedAnnotation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Annotation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(link))
        {
            AddOwnedElement(KermlLanguage.Instance.IElement_ownedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(link))
        {
            AddOwnedRelationship(KermlLanguage.Instance.IElement_ownedRelationship.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(link))
        {
            AddTextualRepresentation(KermlLanguage.Instance.IElement_textualRepresentation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.TextualRepresentation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(link))
        {
            AddOwnedRelatedElement(KermlLanguage.Instance.IRelationship_ownedRelatedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(link))
        {
            AddRelatedElement(KermlLanguage.Instance.IRelationship_relatedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(link))
        {
            AddSource(KermlLanguage.Instance.IRelationship_source.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(link))
        {
            AddTarget(KermlLanguage.Instance.IRelationship_target.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(link))
        {
            InsertAliasIdsContainer(index, KermlLanguage.Instance.IElement_aliasIdsContainer.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.AliasIdsContainer>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(link))
        {
            InsertDocumentation(index, KermlLanguage.Instance.IElement_documentation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Documentation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(link))
        {
            InsertOwnedAnnotation(index, KermlLanguage.Instance.IElement_ownedAnnotation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Annotation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(link))
        {
            InsertOwnedElement(index, KermlLanguage.Instance.IElement_ownedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(link))
        {
            InsertOwnedRelationship(index, KermlLanguage.Instance.IElement_ownedRelationship.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(link))
        {
            InsertTextualRepresentation(index, KermlLanguage.Instance.IElement_textualRepresentation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.TextualRepresentation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(link))
        {
            InsertOwnedRelatedElement(index, KermlLanguage.Instance.IRelationship_ownedRelatedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(link))
        {
            InsertRelatedElement(index, KermlLanguage.Instance.IRelationship_relatedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(link))
        {
            InsertSource(index, KermlLanguage.Instance.IRelationship_source.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(link))
        {
            InsertTarget(index, KermlLanguage.Instance.IRelationship_target.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(link))
        {
            RemoveAliasIdsContainer(KermlLanguage.Instance.IElement_aliasIdsContainer.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.AliasIdsContainer>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_documentation.EqualsIdentity(link))
        {
            RemoveDocumentation(KermlLanguage.Instance.IElement_documentation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Documentation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedAnnotation.EqualsIdentity(link))
        {
            RemoveOwnedAnnotation(KermlLanguage.Instance.IElement_ownedAnnotation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Annotation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedElement.EqualsIdentity(link))
        {
            RemoveOwnedElement(KermlLanguage.Instance.IElement_ownedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(link))
        {
            RemoveOwnedRelationship(KermlLanguage.Instance.IElement_ownedRelationship.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IRelationship>(value));
            return true;
        }

        if (KermlLanguage.Instance.IElement_textualRepresentation.EqualsIdentity(link))
        {
            RemoveTextualRepresentation(KermlLanguage.Instance.IElement_textualRepresentation.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.TextualRepresentation>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(link))
        {
            RemoveOwnedRelatedElement(KermlLanguage.Instance.IRelationship_ownedRelatedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_relatedElement.EqualsIdentity(link))
        {
            RemoveRelatedElement(KermlLanguage.Instance.IRelationship_relatedElement.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_source.EqualsIdentity(link))
        {
            RemoveSource(KermlLanguage.Instance.IRelationship_source.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_target.EqualsIdentity(link))
        {
            RemoveTarget(KermlLanguage.Instance.IRelationship_target.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IElement>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool DetachChild(INode child)
    {
        if (base.DetachChild(child))
            return true;
        Containment? c = GetContainmentOf(child);
        if (KermlLanguage.Instance.IElement_aliasIdsContainer.EqualsIdentity(c))
        {
            RemoveSelfParent(child, _aliasIdsContainer, KermlLanguage.Instance.IElement_aliasIdsContainer);
            return true;
        }

        if (KermlLanguage.Instance.IElement_ownedRelationship.EqualsIdentity(c))
        {
            RemoveSelfParent(child, _ownedRelationship, KermlLanguage.Instance.IElement_ownedRelationship);
            return true;
        }

        if (KermlLanguage.Instance.IRelationship_ownedRelatedElement.EqualsIdentity(c))
        {
            RemoveSelfParent(child, _ownedRelatedElement, KermlLanguage.Instance.IRelationship_ownedRelatedElement);
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    public override Containment? GetContainmentOf(INode child)
    {
        Containment? result = base.GetContainmentOf(child);
        if (result != null)
            return result;
        if (child is AliasIdsContainer child0 && _aliasIdsContainer.Contains(child0))
            return KermlLanguage.Instance.IElement_aliasIdsContainer;
        if (child is IRelationship child1 && _ownedRelationship.Contains(child1))
            return KermlLanguage.Instance.IElement_ownedRelationship;
        if (child is IElement child2 && _ownedRelatedElement.Contains(child2))
            return KermlLanguage.Instance.IRelationship_ownedRelatedElement;
        return null;
    }
}

