// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-Documentation")]
public partial class Documentation : Comment
{
    private ReferenceTarget? _documentedElement = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If DocumentedElement has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-Documentation-documentedElement")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IElement DocumentedElement { get => ReferenceTargetNonNullTarget<IElement>(_documentedElement, KermlLanguage.Instance.Documentation_documentedElement) ?? throw new UnsetFeatureException(KermlLanguage.Instance.Documentation_documentedElement); set => SetDocumentedElement(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetDocumentedElement([NotNullWhenAttribute(true)] out IElement? documentedElement)
    {
        documentedElement = ReferenceTargetNullableTarget<IElement>(_documentedElement, KermlLanguage.Instance.Documentation_documentedElement);
        return documentedElement != null;
    }

    private Documentation SetDocumentedElement(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IElement>(value, KermlLanguage.Instance.Documentation_documentedElement, _documentedElement, SetDocumentedElementRaw);
        return this;
    }

    private bool SetDocumentedElementRaw(ReferenceTarget? value)
    {
        if (value == _documentedElement)
            return false;
        _documentedElement = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public Documentation SetDocumentedElement(IElement value)
    {
        return SetDocumentedElement(ReferenceTarget.FromNodeOptional(value));
    }

    public Documentation(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.Documentation;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.Documentation_documentedElement.EqualsIdentity(feature))
        {
            result = DocumentedElement;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.Documentation_documentedElement.EqualsIdentity(feature))
        {
            result = _documentedElement;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.Documentation_documentedElement.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.IElement v)
            {
                SetDocumentedElement(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetDocumentedElement(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.Documentation_documentedElement.EqualsIdentity(feature))
            return SetDocumentedElementRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetDocumentedElement(out _))
            result.Add(KermlLanguage.Instance.Documentation_documentedElement);
        return result;
    }
}

