// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureValue")]
public partial class FeatureValue : OwningMembership
{
    private ReferenceTarget? _featureWithValue = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If FeatureWithValue has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureValue-featureWithValue")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature FeatureWithValue { get => ReferenceTargetNonNullTarget<IFeature>(_featureWithValue, KermlLanguage.Instance.FeatureValue_featureWithValue) ?? throw new UnsetFeatureException(KermlLanguage.Instance.FeatureValue_featureWithValue); set => SetFeatureWithValue(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetFeatureWithValue([NotNullWhenAttribute(true)] out IFeature? featureWithValue)
    {
        featureWithValue = ReferenceTargetNullableTarget<IFeature>(_featureWithValue, KermlLanguage.Instance.FeatureValue_featureWithValue);
        return featureWithValue != null;
    }

    private FeatureValue SetFeatureWithValue(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IFeature>(value, KermlLanguage.Instance.FeatureValue_featureWithValue, _featureWithValue, SetFeatureWithValueRaw);
        return this;
    }

    private bool SetFeatureWithValueRaw(ReferenceTarget? value)
    {
        if (value == _featureWithValue)
            return false;
        _featureWithValue = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public FeatureValue SetFeatureWithValue(IFeature value)
    {
        return SetFeatureWithValue(ReferenceTarget.FromNodeOptional(value));
    }

    private bool? _isDefault = null;
    private bool SetIsDefaultRaw(bool? value)
    {
        if (value is null && _isDefault is null || value is not null && value.Equals(_isDefault))
            return false;
        _isDefault = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsDefault has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureValue-isDefault")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsDefault { get => _isDefault ?? throw new UnsetFeatureException(KermlLanguage.Instance.FeatureValue_isDefault); set => SetIsDefault(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsDefault([NotNullWhenAttribute(true)] out bool? isDefault)
    {
        isDefault = _isDefault;
        return isDefault != null;
    }

    /// <remarks>Required Property</remarks>
    public FeatureValue SetIsDefault(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, KermlLanguage.Instance.FeatureValue_isDefault, _isDefault, SetIsDefaultRaw);
        return this;
    }

    private bool? _isInitial = null;
    private bool SetIsInitialRaw(bool? value)
    {
        if (value is null && _isInitial is null || value is not null && value.Equals(_isInitial))
            return false;
        _isInitial = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If IsInitial has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureValue-isInitial")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public bool IsInitial { get => _isInitial ?? throw new UnsetFeatureException(KermlLanguage.Instance.FeatureValue_isInitial); set => SetIsInitial(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetIsInitial([NotNullWhenAttribute(true)] out bool? isInitial)
    {
        isInitial = _isInitial;
        return isInitial != null;
    }

    /// <remarks>Required Property</remarks>
    public FeatureValue SetIsInitial(bool value)
    {
        SetRequiredValueTypeProperty<bool>(value, KermlLanguage.Instance.FeatureValue_isInitial, _isInitial, SetIsInitialRaw);
        return this;
    }

    private ReferenceTarget? _value = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If Value has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureValue-value")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public Expression Value { get => ReferenceTargetNonNullTarget<Expression>(_value, KermlLanguage.Instance.FeatureValue_value) ?? throw new UnsetFeatureException(KermlLanguage.Instance.FeatureValue_value); set => SetValue(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetValue([NotNullWhenAttribute(true)] out Expression? value)
    {
        value = ReferenceTargetNullableTarget<Expression>(_value, KermlLanguage.Instance.FeatureValue_value);
        return value != null;
    }

    private FeatureValue SetValue(ReferenceTarget? value)
    {
        SetRequiredSingleReference<Expression>(value, KermlLanguage.Instance.FeatureValue_value, _value, SetValueRaw);
        return this;
    }

    private bool SetValueRaw(ReferenceTarget? value)
    {
        if (value == _value)
            return false;
        _value = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public FeatureValue SetValue(Expression value)
    {
        return SetValue(ReferenceTarget.FromNodeOptional(value));
    }

    public FeatureValue(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.FeatureValue;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.FeatureValue_featureWithValue.EqualsIdentity(feature))
        {
            result = FeatureWithValue;
            return true;
        }

        if (KermlLanguage.Instance.FeatureValue_isDefault.EqualsIdentity(feature))
        {
            result = IsDefault;
            return true;
        }

        if (KermlLanguage.Instance.FeatureValue_isInitial.EqualsIdentity(feature))
        {
            result = IsInitial;
            return true;
        }

        if (KermlLanguage.Instance.FeatureValue_value.EqualsIdentity(feature))
        {
            result = Value;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.FeatureValue_isDefault.EqualsIdentity(feature))
        {
            result = _isDefault;
            return true;
        }

        if (KermlLanguage.Instance.FeatureValue_isInitial.EqualsIdentity(feature))
        {
            result = _isInitial;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.FeatureValue_featureWithValue.EqualsIdentity(feature))
        {
            result = _featureWithValue;
            return true;
        }

        if (KermlLanguage.Instance.FeatureValue_value.EqualsIdentity(feature))
        {
            result = _value;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.FeatureValue_featureWithValue.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.IFeature v)
            {
                SetFeatureWithValue(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetFeatureWithValue(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.FeatureValue_isDefault.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsDefault(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.FeatureValue_isInitial.EqualsIdentity(feature))
        {
            if (value is bool v)
            {
                SetIsInitial(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.FeatureValue_value.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.Expression v)
            {
                SetValue(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetValue(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.FeatureValue_isDefault.EqualsIdentity(feature) && value is null or bool)
            return SetIsDefaultRaw((bool? )value);
        if (KermlLanguage.Instance.FeatureValue_isInitial.EqualsIdentity(feature) && value is null or bool)
            return SetIsInitialRaw((bool? )value);
        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.FeatureValue_featureWithValue.EqualsIdentity(feature))
            return SetFeatureWithValueRaw(value);
        if (KermlLanguage.Instance.FeatureValue_value.EqualsIdentity(feature))
            return SetValueRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetFeatureWithValue(out _))
            result.Add(KermlLanguage.Instance.FeatureValue_featureWithValue);
        if (TryGetIsDefault(out _))
            result.Add(KermlLanguage.Instance.FeatureValue_isDefault);
        if (TryGetIsInitial(out _))
            result.Add(KermlLanguage.Instance.FeatureValue_isInitial);
        if (TryGetValue(out _))
            result.Add(KermlLanguage.Instance.FeatureValue_value);
        return result;
    }
}

