// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureReferenceExpression")]
public partial class FeatureReferenceExpression : Expression
{
    private ReferenceTarget? _referent = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If Referent has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-FeatureReferenceExpression-referent")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature Referent { get => ReferenceTargetNonNullTarget<IFeature>(_referent, KermlLanguage.Instance.FeatureReferenceExpression_referent) ?? throw new UnsetFeatureException(KermlLanguage.Instance.FeatureReferenceExpression_referent); set => SetReferent(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetReferent([NotNullWhenAttribute(true)] out IFeature? referent)
    {
        referent = ReferenceTargetNullableTarget<IFeature>(_referent, KermlLanguage.Instance.FeatureReferenceExpression_referent);
        return referent != null;
    }

    private FeatureReferenceExpression SetReferent(ReferenceTarget? value)
    {
        SetRequiredSingleReference<IFeature>(value, KermlLanguage.Instance.FeatureReferenceExpression_referent, _referent, SetReferentRaw);
        return this;
    }

    private bool SetReferentRaw(ReferenceTarget? value)
    {
        if (value == _referent)
            return false;
        _referent = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public FeatureReferenceExpression SetReferent(IFeature value)
    {
        return SetReferent(ReferenceTarget.FromNodeOptional(value));
    }

    public FeatureReferenceExpression(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.FeatureReferenceExpression;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.FeatureReferenceExpression_referent.EqualsIdentity(feature))
        {
            result = Referent;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.FeatureReferenceExpression_referent.EqualsIdentity(feature))
        {
            result = _referent;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.FeatureReferenceExpression_referent.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.IFeature v)
            {
                SetReferent(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetReferent(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.FeatureReferenceExpression_referent.EqualsIdentity(feature))
            return SetReferentRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetReferent(out _))
            result.Add(KermlLanguage.Instance.FeatureReferenceExpression_referent);
        return result;
    }
}

