// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IClassifier")]
public partial interface IClassifier : IType
{
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IClassifier-ownedSubclassification")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Subclassification> OwnedSubclassification { get; init; }

    /// <remarks>Optional Multiple Reference</remarks>
    public IClassifier AddOwnedSubclassification(IEnumerable<Subclassification> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IClassifier InsertOwnedSubclassification(int index, IEnumerable<Subclassification> nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public IClassifier RemoveOwnedSubclassification(IEnumerable<Subclassification> nodes);
}

