// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IFeaturing")]
public partial interface IFeaturing : IRelationship
{
    /// <remarks>Required Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IFeaturing-feature")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IFeature Feature { get; set; }

    /// <remarks>Required Single Reference</remarks>
    public IFeaturing SetFeature(IFeature value);
    /// <remarks>Required Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-IFeaturing-type")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public IType Type { get; set; }

    /// <remarks>Required Single Reference</remarks>
    public IFeaturing SetType(IType value);
}

