// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

public class KermlFactory : AbstractBaseNodeFactory, IKermlFactory
{
    private readonly KermlLanguage _language;
    public KermlFactory(KermlLanguage language) : base(language)
    {
        _language = language;
    }

    /// <inheritdoc/>
    public override INode CreateNode(string id, global::LionWeb.Core.M3.Classifier classifier)
    {
        if (_language.AliasIdsContainer.EqualsIdentity(classifier))
            return NewAliasIdsContainer(id);
        if (_language.AnnotatingElement.EqualsIdentity(classifier))
            return NewAnnotatingElement(id);
        if (_language.Annotation.EqualsIdentity(classifier))
            return NewAnnotation(id);
        if (_language.Association.EqualsIdentity(classifier))
            return NewAssociation(id);
        if (_language.AssociationStructure.EqualsIdentity(classifier))
            return NewAssociationStructure(id);
        if (_language.Behavior.EqualsIdentity(classifier))
            return NewBehavior(id);
        if (_language.BindingConnector.EqualsIdentity(classifier))
            return NewBindingConnector(id);
        if (_language.BooleanExpression.EqualsIdentity(classifier))
            return NewBooleanExpression(id);
        if (_language.Class.EqualsIdentity(classifier))
            return NewClass(id);
        if (_language.Classifier.EqualsIdentity(classifier))
            return NewClassifier(id);
        if (_language.CollectExpression.EqualsIdentity(classifier))
            return NewCollectExpression(id);
        if (_language.Comment.EqualsIdentity(classifier))
            return NewComment(id);
        if (_language.Conjugation.EqualsIdentity(classifier))
            return NewConjugation(id);
        if (_language.Connector.EqualsIdentity(classifier))
            return NewConnector(id);
        if (_language.DataType.EqualsIdentity(classifier))
            return NewDataType(id);
        if (_language.Dependency.EqualsIdentity(classifier))
            return NewDependency(id);
        if (_language.Differencing.EqualsIdentity(classifier))
            return NewDifferencing(id);
        if (_language.Disjoining.EqualsIdentity(classifier))
            return NewDisjoining(id);
        if (_language.Documentation.EqualsIdentity(classifier))
            return NewDocumentation(id);
        if (_language.Element.EqualsIdentity(classifier))
            return NewElement(id);
        if (_language.ElementFilterMembership.EqualsIdentity(classifier))
            return NewElementFilterMembership(id);
        if (_language.EndFeatureMembership.EqualsIdentity(classifier))
            return NewEndFeatureMembership(id);
        if (_language.Expression.EqualsIdentity(classifier))
            return NewExpression(id);
        if (_language.Feature.EqualsIdentity(classifier))
            return NewFeature(id);
        if (_language.FeatureChainExpression.EqualsIdentity(classifier))
            return NewFeatureChainExpression(id);
        if (_language.FeatureChaining.EqualsIdentity(classifier))
            return NewFeatureChaining(id);
        if (_language.FeatureInverting.EqualsIdentity(classifier))
            return NewFeatureInverting(id);
        if (_language.FeatureMembership.EqualsIdentity(classifier))
            return NewFeatureMembership(id);
        if (_language.FeatureReferenceExpression.EqualsIdentity(classifier))
            return NewFeatureReferenceExpression(id);
        if (_language.FeatureTyping.EqualsIdentity(classifier))
            return NewFeatureTyping(id);
        if (_language.FeatureValue.EqualsIdentity(classifier))
            return NewFeatureValue(id);
        if (_language.Featuring.EqualsIdentity(classifier))
            return NewFeaturing(id);
        if (_language.Function.EqualsIdentity(classifier))
            return NewFunction(id);
        if (_language.Interaction.EqualsIdentity(classifier))
            return NewInteraction(id);
        if (_language.Intersecting.EqualsIdentity(classifier))
            return NewIntersecting(id);
        if (_language.Invariant.EqualsIdentity(classifier))
            return NewInvariant(id);
        if (_language.InvocationExpression.EqualsIdentity(classifier))
            return NewInvocationExpression(id);
        if (_language.ItemFeature.EqualsIdentity(classifier))
            return NewItemFeature(id);
        if (_language.ItemFlow.EqualsIdentity(classifier))
            return NewItemFlow(id);
        if (_language.ItemFlowEnd.EqualsIdentity(classifier))
            return NewItemFlowEnd(id);
        if (_language.LibraryPackage.EqualsIdentity(classifier))
            return NewLibraryPackage(id);
        if (_language.LiteralBoolean.EqualsIdentity(classifier))
            return NewLiteralBoolean(id);
        if (_language.LiteralExpression.EqualsIdentity(classifier))
            return NewLiteralExpression(id);
        if (_language.LiteralInfinity.EqualsIdentity(classifier))
            return NewLiteralInfinity(id);
        if (_language.LiteralInteger.EqualsIdentity(classifier))
            return NewLiteralInteger(id);
        if (_language.LiteralRational.EqualsIdentity(classifier))
            return NewLiteralRational(id);
        if (_language.LiteralString.EqualsIdentity(classifier))
            return NewLiteralString(id);
        if (_language.Membership.EqualsIdentity(classifier))
            return NewMembership(id);
        if (_language.MembershipImport.EqualsIdentity(classifier))
            return NewMembershipImport(id);
        if (_language.Metaclass.EqualsIdentity(classifier))
            return NewMetaclass(id);
        if (_language.MetadataAccessExpression.EqualsIdentity(classifier))
            return NewMetadataAccessExpression(id);
        if (_language.MetadataFeature.EqualsIdentity(classifier))
            return NewMetadataFeature(id);
        if (_language.Multiplicity.EqualsIdentity(classifier))
            return NewMultiplicity(id);
        if (_language.MultiplicityRange.EqualsIdentity(classifier))
            return NewMultiplicityRange(id);
        if (_language.Namespace.EqualsIdentity(classifier))
            return NewNamespace(id);
        if (_language.NamespaceImport.EqualsIdentity(classifier))
            return NewNamespaceImport(id);
        if (_language.NullExpression.EqualsIdentity(classifier))
            return NewNullExpression(id);
        if (_language.OperatorExpression.EqualsIdentity(classifier))
            return NewOperatorExpression(id);
        if (_language.OwningMembership.EqualsIdentity(classifier))
            return NewOwningMembership(id);
        if (_language.Package.EqualsIdentity(classifier))
            return NewPackage(id);
        if (_language.ParameterMembership.EqualsIdentity(classifier))
            return NewParameterMembership(id);
        if (_language.Predicate.EqualsIdentity(classifier))
            return NewPredicate(id);
        if (_language.Redefinition.EqualsIdentity(classifier))
            return NewRedefinition(id);
        if (_language.ReferenceSubsetting.EqualsIdentity(classifier))
            return NewReferenceSubsetting(id);
        if (_language.Relationship.EqualsIdentity(classifier))
            return NewRelationship(id);
        if (_language.ResultExpressionMembership.EqualsIdentity(classifier))
            return NewResultExpressionMembership(id);
        if (_language.ReturnParameterMembership.EqualsIdentity(classifier))
            return NewReturnParameterMembership(id);
        if (_language.SelectExpression.EqualsIdentity(classifier))
            return NewSelectExpression(id);
        if (_language.Specialization.EqualsIdentity(classifier))
            return NewSpecialization(id);
        if (_language.Step.EqualsIdentity(classifier))
            return NewStep(id);
        if (_language.Structure.EqualsIdentity(classifier))
            return NewStructure(id);
        if (_language.Subclassification.EqualsIdentity(classifier))
            return NewSubclassification(id);
        if (_language.Subsetting.EqualsIdentity(classifier))
            return NewSubsetting(id);
        if (_language.Succession.EqualsIdentity(classifier))
            return NewSuccession(id);
        if (_language.SuccessionItemFlow.EqualsIdentity(classifier))
            return NewSuccessionItemFlow(id);
        if (_language.TextualRepresentation.EqualsIdentity(classifier))
            return NewTextualRepresentation(id);
        if (_language.Type.EqualsIdentity(classifier))
            return NewType(id);
        if (_language.TypeFeaturing.EqualsIdentity(classifier))
            return NewTypeFeaturing(id);
        if (_language.Unioning.EqualsIdentity(classifier))
            return NewUnioning(id);
        throw new UnsupportedClassifierException(classifier);
    }

    /// <inheritdoc/>
    public override Enum GetEnumerationLiteral(EnumerationLiteral literal)
    {
        if (_language.FeatureDirectionKind.EqualsIdentity(literal.GetEnumeration()))
            return EnumValueFor<FeatureDirectionKind>(literal);
        if (_language.VisibilityKind.EqualsIdentity(literal.GetEnumeration()))
            return EnumValueFor<VisibilityKind>(literal);
        throw new UnsupportedEnumerationLiteralException(literal);
    }

    /// <inheritdoc/>
    public override IStructuredDataTypeInstance CreateStructuredDataTypeInstance(StructuredDataType structuredDataType, IFieldValues fieldValues)
    {
        throw new UnsupportedStructuredDataTypeException(structuredDataType);
    }

    public virtual AliasIdsContainer NewAliasIdsContainer(string id) => new(id);
    public virtual AliasIdsContainer CreateAliasIdsContainer() => NewAliasIdsContainer(GetNewId());
    public virtual AnnotatingElement NewAnnotatingElement(string id) => new(id);
    public virtual AnnotatingElement CreateAnnotatingElement() => NewAnnotatingElement(GetNewId());
    public virtual Annotation NewAnnotation(string id) => new(id);
    public virtual Annotation CreateAnnotation() => NewAnnotation(GetNewId());
    public virtual Association NewAssociation(string id) => new(id);
    public virtual Association CreateAssociation() => NewAssociation(GetNewId());
    public virtual AssociationStructure NewAssociationStructure(string id) => new(id);
    public virtual AssociationStructure CreateAssociationStructure() => NewAssociationStructure(GetNewId());
    public virtual Behavior NewBehavior(string id) => new(id);
    public virtual Behavior CreateBehavior() => NewBehavior(GetNewId());
    public virtual BindingConnector NewBindingConnector(string id) => new(id);
    public virtual BindingConnector CreateBindingConnector() => NewBindingConnector(GetNewId());
    public virtual BooleanExpression NewBooleanExpression(string id) => new(id);
    public virtual BooleanExpression CreateBooleanExpression() => NewBooleanExpression(GetNewId());
    public virtual Class NewClass(string id) => new(id);
    public virtual Class CreateClass() => NewClass(GetNewId());
    public virtual Classifier NewClassifier(string id) => new(id);
    public virtual Classifier CreateClassifier() => NewClassifier(GetNewId());
    public virtual CollectExpression NewCollectExpression(string id) => new(id);
    public virtual CollectExpression CreateCollectExpression() => NewCollectExpression(GetNewId());
    public virtual Comment NewComment(string id) => new(id);
    public virtual Comment CreateComment() => NewComment(GetNewId());
    public virtual Conjugation NewConjugation(string id) => new(id);
    public virtual Conjugation CreateConjugation() => NewConjugation(GetNewId());
    public virtual Connector NewConnector(string id) => new(id);
    public virtual Connector CreateConnector() => NewConnector(GetNewId());
    public virtual DataType NewDataType(string id) => new(id);
    public virtual DataType CreateDataType() => NewDataType(GetNewId());
    public virtual Dependency NewDependency(string id) => new(id);
    public virtual Dependency CreateDependency() => NewDependency(GetNewId());
    public virtual Differencing NewDifferencing(string id) => new(id);
    public virtual Differencing CreateDifferencing() => NewDifferencing(GetNewId());
    public virtual Disjoining NewDisjoining(string id) => new(id);
    public virtual Disjoining CreateDisjoining() => NewDisjoining(GetNewId());
    public virtual Documentation NewDocumentation(string id) => new(id);
    public virtual Documentation CreateDocumentation() => NewDocumentation(GetNewId());
    public virtual Element NewElement(string id) => new(id);
    public virtual Element CreateElement() => NewElement(GetNewId());
    public virtual ElementFilterMembership NewElementFilterMembership(string id) => new(id);
    public virtual ElementFilterMembership CreateElementFilterMembership() => NewElementFilterMembership(GetNewId());
    public virtual EndFeatureMembership NewEndFeatureMembership(string id) => new(id);
    public virtual EndFeatureMembership CreateEndFeatureMembership() => NewEndFeatureMembership(GetNewId());
    public virtual Expression NewExpression(string id) => new(id);
    public virtual Expression CreateExpression() => NewExpression(GetNewId());
    public virtual Feature NewFeature(string id) => new(id);
    public virtual Feature CreateFeature() => NewFeature(GetNewId());
    public virtual FeatureChainExpression NewFeatureChainExpression(string id) => new(id);
    public virtual FeatureChainExpression CreateFeatureChainExpression() => NewFeatureChainExpression(GetNewId());
    public virtual FeatureChaining NewFeatureChaining(string id) => new(id);
    public virtual FeatureChaining CreateFeatureChaining() => NewFeatureChaining(GetNewId());
    public virtual FeatureInverting NewFeatureInverting(string id) => new(id);
    public virtual FeatureInverting CreateFeatureInverting() => NewFeatureInverting(GetNewId());
    public virtual FeatureMembership NewFeatureMembership(string id) => new(id);
    public virtual FeatureMembership CreateFeatureMembership() => NewFeatureMembership(GetNewId());
    public virtual FeatureReferenceExpression NewFeatureReferenceExpression(string id) => new(id);
    public virtual FeatureReferenceExpression CreateFeatureReferenceExpression() => NewFeatureReferenceExpression(GetNewId());
    public virtual FeatureTyping NewFeatureTyping(string id) => new(id);
    public virtual FeatureTyping CreateFeatureTyping() => NewFeatureTyping(GetNewId());
    public virtual FeatureValue NewFeatureValue(string id) => new(id);
    public virtual FeatureValue CreateFeatureValue() => NewFeatureValue(GetNewId());
    public virtual Featuring NewFeaturing(string id) => new(id);
    public virtual Featuring CreateFeaturing() => NewFeaturing(GetNewId());
    public virtual Function NewFunction(string id) => new(id);
    public virtual Function CreateFunction() => NewFunction(GetNewId());
    public virtual Interaction NewInteraction(string id) => new(id);
    public virtual Interaction CreateInteraction() => NewInteraction(GetNewId());
    public virtual Intersecting NewIntersecting(string id) => new(id);
    public virtual Intersecting CreateIntersecting() => NewIntersecting(GetNewId());
    public virtual Invariant NewInvariant(string id) => new(id);
    public virtual Invariant CreateInvariant() => NewInvariant(GetNewId());
    public virtual InvocationExpression NewInvocationExpression(string id) => new(id);
    public virtual InvocationExpression CreateInvocationExpression() => NewInvocationExpression(GetNewId());
    public virtual ItemFeature NewItemFeature(string id) => new(id);
    public virtual ItemFeature CreateItemFeature() => NewItemFeature(GetNewId());
    public virtual ItemFlow NewItemFlow(string id) => new(id);
    public virtual ItemFlow CreateItemFlow() => NewItemFlow(GetNewId());
    public virtual ItemFlowEnd NewItemFlowEnd(string id) => new(id);
    public virtual ItemFlowEnd CreateItemFlowEnd() => NewItemFlowEnd(GetNewId());
    public virtual LibraryPackage NewLibraryPackage(string id) => new(id);
    public virtual LibraryPackage CreateLibraryPackage() => NewLibraryPackage(GetNewId());
    public virtual LiteralBoolean NewLiteralBoolean(string id) => new(id);
    public virtual LiteralBoolean CreateLiteralBoolean() => NewLiteralBoolean(GetNewId());
    public virtual LiteralExpression NewLiteralExpression(string id) => new(id);
    public virtual LiteralExpression CreateLiteralExpression() => NewLiteralExpression(GetNewId());
    public virtual LiteralInfinity NewLiteralInfinity(string id) => new(id);
    public virtual LiteralInfinity CreateLiteralInfinity() => NewLiteralInfinity(GetNewId());
    public virtual LiteralInteger NewLiteralInteger(string id) => new(id);
    public virtual LiteralInteger CreateLiteralInteger() => NewLiteralInteger(GetNewId());
    public virtual LiteralRational NewLiteralRational(string id) => new(id);
    public virtual LiteralRational CreateLiteralRational() => NewLiteralRational(GetNewId());
    public virtual LiteralString NewLiteralString(string id) => new(id);
    public virtual LiteralString CreateLiteralString() => NewLiteralString(GetNewId());
    public virtual Membership NewMembership(string id) => new(id);
    public virtual Membership CreateMembership() => NewMembership(GetNewId());
    public virtual MembershipImport NewMembershipImport(string id) => new(id);
    public virtual MembershipImport CreateMembershipImport() => NewMembershipImport(GetNewId());
    public virtual Metaclass NewMetaclass(string id) => new(id);
    public virtual Metaclass CreateMetaclass() => NewMetaclass(GetNewId());
    public virtual MetadataAccessExpression NewMetadataAccessExpression(string id) => new(id);
    public virtual MetadataAccessExpression CreateMetadataAccessExpression() => NewMetadataAccessExpression(GetNewId());
    public virtual MetadataFeature NewMetadataFeature(string id) => new(id);
    public virtual MetadataFeature CreateMetadataFeature() => NewMetadataFeature(GetNewId());
    public virtual Multiplicity NewMultiplicity(string id) => new(id);
    public virtual Multiplicity CreateMultiplicity() => NewMultiplicity(GetNewId());
    public virtual MultiplicityRange NewMultiplicityRange(string id) => new(id);
    public virtual MultiplicityRange CreateMultiplicityRange() => NewMultiplicityRange(GetNewId());
    public virtual Namespace NewNamespace(string id) => new(id);
    public virtual Namespace CreateNamespace() => NewNamespace(GetNewId());
    public virtual NamespaceImport NewNamespaceImport(string id) => new(id);
    public virtual NamespaceImport CreateNamespaceImport() => NewNamespaceImport(GetNewId());
    public virtual NullExpression NewNullExpression(string id) => new(id);
    public virtual NullExpression CreateNullExpression() => NewNullExpression(GetNewId());
    public virtual OperatorExpression NewOperatorExpression(string id) => new(id);
    public virtual OperatorExpression CreateOperatorExpression() => NewOperatorExpression(GetNewId());
    public virtual OwningMembership NewOwningMembership(string id) => new(id);
    public virtual OwningMembership CreateOwningMembership() => NewOwningMembership(GetNewId());
    public virtual Package NewPackage(string id) => new(id);
    public virtual Package CreatePackage() => NewPackage(GetNewId());
    public virtual ParameterMembership NewParameterMembership(string id) => new(id);
    public virtual ParameterMembership CreateParameterMembership() => NewParameterMembership(GetNewId());
    public virtual Predicate NewPredicate(string id) => new(id);
    public virtual Predicate CreatePredicate() => NewPredicate(GetNewId());
    public virtual Redefinition NewRedefinition(string id) => new(id);
    public virtual Redefinition CreateRedefinition() => NewRedefinition(GetNewId());
    public virtual ReferenceSubsetting NewReferenceSubsetting(string id) => new(id);
    public virtual ReferenceSubsetting CreateReferenceSubsetting() => NewReferenceSubsetting(GetNewId());
    public virtual Relationship NewRelationship(string id) => new(id);
    public virtual Relationship CreateRelationship() => NewRelationship(GetNewId());
    public virtual ResultExpressionMembership NewResultExpressionMembership(string id) => new(id);
    public virtual ResultExpressionMembership CreateResultExpressionMembership() => NewResultExpressionMembership(GetNewId());
    public virtual ReturnParameterMembership NewReturnParameterMembership(string id) => new(id);
    public virtual ReturnParameterMembership CreateReturnParameterMembership() => NewReturnParameterMembership(GetNewId());
    public virtual SelectExpression NewSelectExpression(string id) => new(id);
    public virtual SelectExpression CreateSelectExpression() => NewSelectExpression(GetNewId());
    public virtual Specialization NewSpecialization(string id) => new(id);
    public virtual Specialization CreateSpecialization() => NewSpecialization(GetNewId());
    public virtual Step NewStep(string id) => new(id);
    public virtual Step CreateStep() => NewStep(GetNewId());
    public virtual Structure NewStructure(string id) => new(id);
    public virtual Structure CreateStructure() => NewStructure(GetNewId());
    public virtual Subclassification NewSubclassification(string id) => new(id);
    public virtual Subclassification CreateSubclassification() => NewSubclassification(GetNewId());
    public virtual Subsetting NewSubsetting(string id) => new(id);
    public virtual Subsetting CreateSubsetting() => NewSubsetting(GetNewId());
    public virtual Succession NewSuccession(string id) => new(id);
    public virtual Succession CreateSuccession() => NewSuccession(GetNewId());
    public virtual SuccessionItemFlow NewSuccessionItemFlow(string id) => new(id);
    public virtual SuccessionItemFlow CreateSuccessionItemFlow() => NewSuccessionItemFlow(GetNewId());
    public virtual TextualRepresentation NewTextualRepresentation(string id) => new(id);
    public virtual TextualRepresentation CreateTextualRepresentation() => NewTextualRepresentation(GetNewId());
    public virtual Type NewType(string id) => new(id);
    public virtual Type CreateType() => NewType(GetNewId());
    public virtual TypeFeaturing NewTypeFeaturing(string id) => new(id);
    public virtual TypeFeaturing CreateTypeFeaturing() => NewTypeFeaturing(GetNewId());
    public virtual Unioning NewUnioning(string id) => new(id);
    public virtual Unioning CreateUnioning() => NewUnioning(GetNewId());
}

