// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-LiteralInteger")]
public partial class LiteralInteger : LiteralExpression
{
    private int? _value = null;
    private bool SetValueRaw(int? value)
    {
        if (value is null && _value is null || value is not null && value.Equals(_value))
            return false;
        _value = value;
        return true;
    }

    /// <remarks>Required Property</remarks>
    /// <exception cref = "UnsetFeatureException">If Value has not been set</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-LiteralInteger-value")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
    public int Value { get => _value ?? throw new UnsetFeatureException(KermlLanguage.Instance.LiteralInteger_value); set => SetValue(value); }

    /// <remarks>Required Property</remarks>
    public bool TryGetValue([NotNullWhenAttribute(true)] out int? value)
    {
        value = _value;
        return value != null;
    }

    /// <remarks>Required Property</remarks>
    public LiteralInteger SetValue(int value)
    {
        SetRequiredValueTypeProperty<int>(value, KermlLanguage.Instance.LiteralInteger_value, _value, SetValueRaw);
        return this;
    }

    public LiteralInteger(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.LiteralInteger;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.LiteralInteger_value.EqualsIdentity(feature))
        {
            result = Value;
            return true;
        }

        return false;
    }

    protected override bool TryGetPropertyRaw(Property feature, out object? result)
    {
        if (base.TryGetPropertyRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.LiteralInteger_value.EqualsIdentity(feature))
        {
            result = _value;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.LiteralInteger_value.EqualsIdentity(feature))
        {
            if (value is int v)
            {
                SetValue(v);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetPropertyRaw(Property feature, object? value)
    {
        if (base.SetPropertyRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.LiteralInteger_value.EqualsIdentity(feature) && value is null or int)
            return SetValueRaw((int? )value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetValue(out _))
            result.Add(KermlLanguage.Instance.LiteralInteger_value);
        return result;
    }
}

