// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-MembershipImport")]
public partial class MembershipImport : Import
{
    private ReferenceTarget? _importedMembership = null;
    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "UnsetFeatureException">If ImportedMembership has not been set</exception>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-MembershipImport-importedMembership")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = false, Multiple = false)]
    public Membership ImportedMembership { get => ReferenceTargetNonNullTarget<Membership>(_importedMembership, KermlLanguage.Instance.MembershipImport_importedMembership) ?? throw new UnsetFeatureException(KermlLanguage.Instance.MembershipImport_importedMembership); set => SetImportedMembership(value); }

    /// <remarks>Required Single Reference</remarks>
    public bool TryGetImportedMembership([NotNullWhenAttribute(true)] out Membership? importedMembership)
    {
        importedMembership = ReferenceTargetNullableTarget<Membership>(_importedMembership, KermlLanguage.Instance.MembershipImport_importedMembership);
        return importedMembership != null;
    }

    private MembershipImport SetImportedMembership(ReferenceTarget? value)
    {
        SetRequiredSingleReference<Membership>(value, KermlLanguage.Instance.MembershipImport_importedMembership, _importedMembership, SetImportedMembershipRaw);
        return this;
    }

    private bool SetImportedMembershipRaw(ReferenceTarget? value)
    {
        if (value == _importedMembership)
            return false;
        _importedMembership = value;
        return true;
    }

    /// <remarks>Required Single Reference</remarks>
    /// <exception cref = "InvalidValueException">If set to null</exception>
    public MembershipImport SetImportedMembership(Membership value)
    {
        return SetImportedMembership(ReferenceTarget.FromNodeOptional(value));
    }

    public MembershipImport(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.MembershipImport;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.MembershipImport_importedMembership.EqualsIdentity(feature))
        {
            result = ImportedMembership;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.MembershipImport_importedMembership.EqualsIdentity(feature))
        {
            result = _importedMembership;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.MembershipImport_importedMembership.EqualsIdentity(feature))
        {
            if (value is LionWeb.Demo.SysMl2.Languages.KerMl.Membership v)
            {
                SetImportedMembership(v);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetImportedMembership(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.MembershipImport_importedMembership.EqualsIdentity(feature))
            return SetImportedMembershipRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetImportedMembership(out _))
            result.Add(KermlLanguage.Instance.MembershipImport_importedMembership);
        return result;
    }
}

