// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace LionWeb.Demo.SysMl2.Languages.KerMl;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-SuccessionItemFlow")]
public partial class SuccessionItemFlow : ItemFlow, ISuccession
{
    private readonly List<ReferenceTarget> _effectStep = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-ISuccession-effectStep")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IStep> EffectStep { get => ReferenceTargetNonNullTargets<IStep>(_effectStep, KermlLanguage.Instance.ISuccession_effectStep); init => AddEffectStep(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetEffectStep([NotNullWhenAttribute(true)] out IReadOnlyList<IStep> effectStep) => TryGetReference<IStep>(_effectStep, out effectStep);
    private bool SetEffectStepRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _effectStep);
    private bool AddEffectStepRaw(ReferenceTarget target) => AddReferencesRaw(target, _effectStep);
    private bool InsertEffectStepRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _effectStep);
    private bool RemoveEffectStepRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _effectStep);
/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.AddEffectStep(IEnumerable<IStep> nodes) => AddEffectStep(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow AddEffectStep(IEnumerable<IStep> nodes)
    {
        AddOptionalMultipleReference<IStep>(nodes, KermlLanguage.Instance.ISuccession_effectStep, _effectStep, AddEffectStepRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.InsertEffectStep(int index, IEnumerable<IStep> nodes) => InsertEffectStep(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow InsertEffectStep(int index, IEnumerable<IStep> nodes)
    {
        InsertOptionalMultipleReference<IStep>(index, nodes, KermlLanguage.Instance.ISuccession_effectStep, _effectStep, InsertEffectStepRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.RemoveEffectStep(IEnumerable<IStep> nodes) => RemoveEffectStep(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow RemoveEffectStep(IEnumerable<IStep> nodes)
    {
        RemoveOptionalMultipleReference<IStep>(nodes, KermlLanguage.Instance.ISuccession_effectStep, _effectStep, RemoveEffectStepRaw);
        return this;
    }

    private readonly List<ReferenceTarget> _guardExpression = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-ISuccession-guardExpression")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<Expression> GuardExpression { get => ReferenceTargetNonNullTargets<Expression>(_guardExpression, KermlLanguage.Instance.ISuccession_guardExpression); init => AddGuardExpression(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetGuardExpression([NotNullWhenAttribute(true)] out IReadOnlyList<Expression> guardExpression) => TryGetReference<Expression>(_guardExpression, out guardExpression);
    private bool SetGuardExpressionRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _guardExpression);
    private bool AddGuardExpressionRaw(ReferenceTarget target) => AddReferencesRaw(target, _guardExpression);
    private bool InsertGuardExpressionRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _guardExpression);
    private bool RemoveGuardExpressionRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _guardExpression);
/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.AddGuardExpression(IEnumerable<Expression> nodes) => AddGuardExpression(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow AddGuardExpression(IEnumerable<Expression> nodes)
    {
        AddOptionalMultipleReference<Expression>(nodes, KermlLanguage.Instance.ISuccession_guardExpression, _guardExpression, AddGuardExpressionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.InsertGuardExpression(int index, IEnumerable<Expression> nodes) => InsertGuardExpression(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow InsertGuardExpression(int index, IEnumerable<Expression> nodes)
    {
        InsertOptionalMultipleReference<Expression>(index, nodes, KermlLanguage.Instance.ISuccession_guardExpression, _guardExpression, InsertGuardExpressionRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.RemoveGuardExpression(IEnumerable<Expression> nodes) => RemoveGuardExpression(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow RemoveGuardExpression(IEnumerable<Expression> nodes)
    {
        RemoveOptionalMultipleReference<Expression>(nodes, KermlLanguage.Instance.ISuccession_guardExpression, _guardExpression, RemoveGuardExpressionRaw);
        return this;
    }

    private ReferenceTarget? _transitionStep = null;
    /// <remarks>Optional Single Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-ISuccession-transitionStep")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
    public IStep? TransitionStep { get => ReferenceTargetNonNullTarget<IStep>(_transitionStep, KermlLanguage.Instance.ISuccession_transitionStep); set => SetTransitionStep(value); }

    /// <remarks>Optional Single Reference</remarks>
    public bool TryGetTransitionStep([NotNullWhenAttribute(true)] out IStep? transitionStep)
    {
        transitionStep = ReferenceTargetNullableTarget<IStep>(_transitionStep, KermlLanguage.Instance.ISuccession_transitionStep);
        return transitionStep != null;
    }

    private SuccessionItemFlow SetTransitionStep(ReferenceTarget? value)
    {
        SetOptionalSingleReference<IStep>(value, KermlLanguage.Instance.ISuccession_transitionStep, _transitionStep, SetTransitionStepRaw);
        return this;
    }

    private bool SetTransitionStepRaw(ReferenceTarget? value)
    {
        if (value == _transitionStep)
            return false;
        _transitionStep = value;
        return true;
    }

/// <remarks>Optional Single Reference</remarks>
    ISuccession ISuccession.SetTransitionStep(IStep? value) => SetTransitionStep(value);
    /// <remarks>Optional Single Reference</remarks>
    public SuccessionItemFlow SetTransitionStep(IStep? value)
    {
        return SetTransitionStep(ReferenceTarget.FromNodeOptional(value));
    }

    private readonly List<ReferenceTarget> _triggerStep = [];
    /// <remarks>Optional Multiple Reference</remarks>
    [LionCoreMetaPointer(Language = typeof(KermlLanguage), Key = "kerml-ISuccession-triggerStep")]
    [LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    public IReadOnlyList<IStep> TriggerStep { get => ReferenceTargetNonNullTargets<IStep>(_triggerStep, KermlLanguage.Instance.ISuccession_triggerStep); init => AddTriggerStep(value); }

    /// <remarks>Optional Multiple Reference</remarks>
    public bool TryGetTriggerStep([NotNullWhenAttribute(true)] out IReadOnlyList<IStep> triggerStep) => TryGetReference<IStep>(_triggerStep, out triggerStep);
    private bool SetTriggerStepRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _triggerStep);
    private bool AddTriggerStepRaw(ReferenceTarget target) => AddReferencesRaw(target, _triggerStep);
    private bool InsertTriggerStepRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _triggerStep);
    private bool RemoveTriggerStepRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _triggerStep);
/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.AddTriggerStep(IEnumerable<IStep> nodes) => AddTriggerStep(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow AddTriggerStep(IEnumerable<IStep> nodes)
    {
        AddOptionalMultipleReference<IStep>(nodes, KermlLanguage.Instance.ISuccession_triggerStep, _triggerStep, AddTriggerStepRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.InsertTriggerStep(int index, IEnumerable<IStep> nodes) => InsertTriggerStep(index, nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow InsertTriggerStep(int index, IEnumerable<IStep> nodes)
    {
        InsertOptionalMultipleReference<IStep>(index, nodes, KermlLanguage.Instance.ISuccession_triggerStep, _triggerStep, InsertTriggerStepRaw);
        return this;
    }

/// <remarks>Optional Multiple Reference</remarks>
    ISuccession ISuccession.RemoveTriggerStep(IEnumerable<IStep> nodes) => RemoveTriggerStep(nodes);
    /// <remarks>Optional Multiple Reference</remarks>
    public SuccessionItemFlow RemoveTriggerStep(IEnumerable<IStep> nodes)
    {
        RemoveOptionalMultipleReference<IStep>(nodes, KermlLanguage.Instance.ISuccession_triggerStep, _triggerStep, RemoveTriggerStepRaw);
        return this;
    }

    public SuccessionItemFlow(string id) : base(id)
    {
    }

    /// <inheritdoc/>
    public override Concept GetConcept() => KermlLanguage.Instance.SuccessionItemFlow;
    /// <inheritdoc/>
    protected override bool GetInternal(global::LionWeb.Core.M3.Feature? feature, out object? result)
    {
        if (base.GetInternal(feature, out result))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(feature))
        {
            result = EffectStep;
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(feature))
        {
            result = GuardExpression;
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_transitionStep.EqualsIdentity(feature))
        {
            result = TransitionStep;
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(feature))
        {
            result = TriggerStep;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
    {
        if (base.TryGetReferenceRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.ISuccession_transitionStep.EqualsIdentity(feature))
        {
            result = _transitionStep;
            return true;
        }

        return false;
    }

    protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
    {
        if (base.TryGetReferencesRaw(feature, out result))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(feature))
        {
            result = _effectStep;
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(feature))
        {
            result = _guardExpression;
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(feature))
        {
            result = _triggerStep;
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool SetInternal(global::LionWeb.Core.M3.Feature? feature, object? value)
    {
        if (base.SetInternal(feature, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IStep>(value, KermlLanguage.Instance.ISuccession_effectStep, _effectStep, SetEffectStepRaw);
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<Expression>(value, KermlLanguage.Instance.ISuccession_guardExpression, _guardExpression, SetGuardExpressionRaw);
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_transitionStep.EqualsIdentity(feature))
        {
            if (value is null or LionWeb.Demo.SysMl2.Languages.KerMl.IStep)
            {
                SetTransitionStep((LionWeb.Demo.SysMl2.Languages.KerMl.IStep? )value);
                return true;
            }

            if (value is ReferenceTarget target)
            {
                SetTransitionStep(target);
                return true;
            }

            throw new InvalidValueException(feature, value);
        }

        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(feature))
        {
            SetOptionalMultipleReference<IStep>(value, KermlLanguage.Instance.ISuccession_triggerStep, _triggerStep, SetTriggerStepRaw);
            return true;
        }

        return false;
    }

    protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
    {
        if (base.SetReferenceRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_transitionStep.EqualsIdentity(feature))
            return SetTransitionStepRaw(value);
        return false;
    }

    /// <inheritdoc/>
    public override IEnumerable<global::LionWeb.Core.M3.Feature> CollectAllSetFeatures()
    {
        List<global::LionWeb.Core.M3.Feature> result = base.CollectAllSetFeatures().ToList();
        if (TryGetEffectStep(out _))
            result.Add(KermlLanguage.Instance.ISuccession_effectStep);
        if (TryGetGuardExpression(out _))
            result.Add(KermlLanguage.Instance.ISuccession_guardExpression);
        if (TryGetTransitionStep(out _))
            result.Add(KermlLanguage.Instance.ISuccession_transitionStep);
        if (TryGetTriggerStep(out _))
            result.Add(KermlLanguage.Instance.ISuccession_triggerStep);
        return result;
    }

    protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.AddReferencesRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(feature))
            return AddEffectStepRaw(value);
        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(feature))
            return AddGuardExpressionRaw(value);
        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(feature))
            return AddTriggerStepRaw(value);
        return false;
    }

    protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
    {
        if (base.InsertReferencesRaw(feature, index, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(feature))
            return InsertEffectStepRaw(index, value);
        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(feature))
            return InsertGuardExpressionRaw(index, value);
        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(feature))
            return InsertTriggerStepRaw(index, value);
        return false;
    }

    protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
    {
        if (base.RemoveReferencesRaw(feature, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(feature))
            return RemoveEffectStepRaw(value);
        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(feature))
            return RemoveGuardExpressionRaw(value);
        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(feature))
            return RemoveTriggerStepRaw(value);
        return false;
    }

    /// <inheritdoc/>
    protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.AddInternal(link, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(link))
        {
            AddEffectStep(KermlLanguage.Instance.ISuccession_effectStep.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IStep>(value));
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(link))
        {
            AddGuardExpression(KermlLanguage.Instance.ISuccession_guardExpression.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Expression>(value));
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(link))
        {
            AddTriggerStep(KermlLanguage.Instance.ISuccession_triggerStep.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IStep>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
    {
        if (base.InsertInternal(link, index, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(link))
        {
            InsertEffectStep(index, KermlLanguage.Instance.ISuccession_effectStep.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IStep>(value));
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(link))
        {
            InsertGuardExpression(index, KermlLanguage.Instance.ISuccession_guardExpression.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Expression>(value));
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(link))
        {
            InsertTriggerStep(index, KermlLanguage.Instance.ISuccession_triggerStep.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IStep>(value));
            return true;
        }

        return false;
    }

    /// <inheritdoc/>
    protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
    {
        if (base.RemoveInternal(link, value))
            return true;
        if (KermlLanguage.Instance.ISuccession_effectStep.EqualsIdentity(link))
        {
            RemoveEffectStep(KermlLanguage.Instance.ISuccession_effectStep.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IStep>(value));
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_guardExpression.EqualsIdentity(link))
        {
            RemoveGuardExpression(KermlLanguage.Instance.ISuccession_guardExpression.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.Expression>(value));
            return true;
        }

        if (KermlLanguage.Instance.ISuccession_triggerStep.EqualsIdentity(link))
        {
            RemoveTriggerStep(KermlLanguage.Instance.ISuccession_triggerStep.AsNodes<LionWeb.Demo.SysMl2.Languages.KerMl.IStep>(value));
            return true;
        }

        return false;
    }
}

